### ISSUE TITLE
Status of the lab extension in ipywidgets 6.0.0?

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#1004]
Since jupyterlab will probably still have a few 0.X releases after ipywidgets 6.0 is released, should we declare that the jupyterlab extension is experimental when we release 6.0?

It would be nice to coordinate with the jlab team if there is a 0.x version that they expect to stay around for some time to be released soon.

**Comment by jdemeyer** [comment]
See also #1012

**Comment by jasongrout** [comment]
Yes, definitely alpha for now.

**Comment by jasongrout** [comment]
I think we shouldn't be any more finished than JLab is. When we release JLab beta, I think we can think about calling the widget extension beta.

**Comment by jasongrout** [comment]
@SylvainCorlay - do you suggest we make the package version an alpha or beta? I thought an 0.x version of lab widgets for an alpha/beta JLab project was sufficient to indicate that the extension is still experimental. At the very least, I'm happy to change the readme to indicate the experimental status.

**Comment by SylvainCorlay** [comment]
This is not so much about the version numbering as it is about the fact that jlab's fast iteration on 0.X version numbers will make our package useless in a couple of weeks after we release it...
