### ISSUE TITLE
ToggleButtons layout regression

### ISSUE THREAD

**Issue by jdemeyer** [ipython/ipywidgets#1007]
With `ipywidgets-5.2.2` + `widgetsnbextension-1.2.6`:
![buttons_old](https://cloud.githubusercontent.com/assets/3625785/21604630/81cab6c6-d1a4-11e6-8cb2-f2812cae6720.png)

With `ipywidgets-6.0.0.beta5` + `widgetsnbextension-2.0.0b7`:
![buttons_new](https://cloud.githubusercontent.com/assets/3625785/21604629/81ca8f20-d1a4-11e6-9c66-68a9df4f65e6.png)

**Comment by SylvainCorlay** [comment]
Do you think that the previous one is preferable?

**Comment by jdemeyer** [comment]
First of all, the buttons should not overlap the next input line. This is very obviously a bug.

Second, yes I do prefer the smaller buttons. IMHO, it looks better.

**Comment by SylvainCorlay** [comment]
Regarding the borders, what if I remove the right border of all non-selected buttons but the right-most one?

**Comment by SylvainCorlay** [comment]
Regarding sizes, this natural size is the one that aligns well with the other ones...

**Comment by jdemeyer** [comment]
> Regarding the borders, what if I remove the right border of all non-selected buttons but the right-most one?

I don't really care. For me, the borders are fine the way they are.

**Comment by SylvainCorlay** [comment]
I should have fixed the two other issues, and the overlap issue of this one. Can you test things out?

**Comment by SylvainCorlay** [comment]
Closing since the overlap issue is fixed and we are keeping the natural size, which is changeable with the `layout` attribute.
