### ISSUE TITLE
Label layout regression

### ISSUE THREAD

**Issue by jdemeyer** [ipython/ipywidgets#1010]
A `Label` no longer wraps long text:

With `ipywidgets-5.2.2` + `widgetsnbextension-1.2.6`:
![label_old](https://cloud.githubusercontent.com/assets/3625785/21605664/e1bb828a-d1aa-11e6-9cea-fd072aa53497.png)

With `ipywidgets-6.0.0.beta5` + `widgetsnbextension-2.0.0b7`:
![label_new](https://cloud.githubusercontent.com/assets/3625785/21605663/e1bb68ae-d1aa-11e6-9ed7-abc5a5eba9e2.png)

**Comment by jdemeyer** [comment]
With #1011, the Label text is truncated (it shows as `lorem ips...`) instead of word-wrapping or overflowing, which is IMHO worse than either other option.

**Comment by jasongrout** [comment]
The idea is that label is the thing that plays well with the layout design, and if you want something a lot longer, use the HTML widget. This should be documented in a migration guide.

**Comment by jasongrout** [comment]
Is the HTML widget sufficient for your use case?

**Comment by SylvainCorlay** [comment]
> With #1011, the Label text is truncated (it shows as lorem ips...) instead of word-wrapping or overflowing, which is IMHO worse than either other option.

This is not what I am seeing. Did you rebuild the js + css ?

**Comment by jdemeyer** [comment]
> Is the HTML widget sufficient for your use case?

Probably yes. I didn't know about the `HTML` widget.

**Comment by jdemeyer** [comment]
> Did you rebuild the js + css ?

No idea. I just ran the `dev-install.sh` script.

**Comment by SylvainCorlay** [comment]
I can't reproduce after #1011

<img width="797" alt="screen shot 2017-01-03 at 4 27 55 pm" src="https://cloud.githubusercontent.com/assets/2397974/21612473/9e975f16-d1d1-11e6-90bb-1c84620aba9a.png">

**Comment by jdemeyer** [comment]
> Did you rebuild the js + css ?

How should I do that? Is running `npm install` sufficient?

**Comment by jasongrout** [comment]
Sylvain, I still think the label should behave like the inline label on widgets... Min and Max sizes, and truncate if needed.

**Comment by SylvainCorlay** [comment]
Ok, we can revert that part of the PR then. I don't really have an opinion.

**Comment by jasongrout** [comment]
@SylvainCorlay - It seemed like lots of people were using the Label widget as an HTML widget. This makes the semantic distinction clearer. @jdemeyer - is there a need for a label widget that doesn't truncate? Can you try the HTML widget and see if that is sufficient for what you are doing?

**Comment by jdemeyer** [comment]
> @jdemeyer - is there a need for a label widget that doesn't truncate? Can you try the HTML widget and see if that is sufficient for what you are doing?

Yes, I'm happy with the `HTML` widget. Like I said before, I just didn't know that it existed.

**Comment by jasongrout** [comment]
> we can revert that part of the PR then

This is now #1016

**Comment by britishbadger** [comment]
Would it be possible to clarify what the expected behaviour of the Label widget is? We have lots of notebooks, all with truncated labels following the upgrade to ipywidgets 6 and it isn't clear as to whether the pull request that enables was reverted or not based on the above. If it was reverted, which release would this be included with ?

I've used the latest jupyter/minimal-notebook docker stack, pip installed latest widgets, enabled the plugin and ran the following:

```
widgets.Label(
    value="A reallly long piece of text",
)
```

I get the output
`A reallly lo...
`

**Comment by jasongrout** [comment]
> Would it be possible to clarify what the expected behaviour of the Label widget is?

(discussion and answer over on #1010)

**Comment by jasongrout** [comment]
I'm convinced now that we should take off the width constraint in the Label widget, so I'm putting in a PR taking it off in #1269.
