### ISSUE TITLE
X is not version compatible with installed JupyterLab version 0.12.1

### ISSUE THREAD

**Issue by hainm** [ipython/ipywidgets#1025]
hi,

When install the labextension from the newest commit 76da87bc0b2f882dca8027a8fc9a48c34935a350

```bash
ipywidgets/jupyterlab_widgets (master) $ jupyter labextension install --sys-prefix --py jupyterlab_widgets
```

I got the error

```bash
X is not version compatible with installed JupyterLab version 0.12.1
Expects JupyterLab version ^0.12.1 from packaged module @jupyterlab/nbwidgets@0.6.4/lib/plugin.js
Expects JupyterLab version ^0.12.1 from packaged module @jupyterlab/nbwidgets@0.6.4/lib/output.js
```

any idea why? thanks.

**Comment by jasongrout** [comment]
@hainm - is it working now? We've now updated to version JLab 0.13.x

**Comment by hainm** [comment]
Hi, I am not sure what I did or if `ipywidgets` was not happy about cached files. I still got the similiar error.

Just tried pull `jupyterlab` and `ipywidgets`

```bash
        X is not version compatible with installed JupyterLab version 0.15.0
            Expects JupyterLab version ^0.13.1 from packaged module @jupyterlab/nbwidgets@0.6.6/lib/plugin.js
            Expects JupyterLab version ^0.13.1 from packaged module @jupyterlab/nbwidgets@0.6.6/lib/output.js

```

May be I just wait for the release versions. :D

**Comment by jasongrout** [comment]
You need to rebuild the javascript - master should be compatible with 0.15.0 now. (I know, things are evolving quickly, and versions keep changing...)

If you want to ping me on gitter, I can try to work through this in real-time with you to help resolve this.

**Comment by hainm** [comment]
thanks. I am having some deadlines so I won't be available to test. I will
wait for the official release version. cheers.

Hai

**Comment by jasongrout** [comment]
Hopefully that's really soon, or at least a more stable beta or RC.

**Comment by hainm** [comment]
yeah. I am very excited about `ipywidgets` in `jupyterlab`. :D

**Comment by hainm** [comment]
@jasongrout I've tried with you new note in `dev-install.sh` and it does help. thanks.
