### ISSUE TITLE
Clear error when using widgets outside kernel

### ISSUE THREAD

**Issue by takluyver** [ipython/ipywidgets#1037]
From ipython/ipython#10087, a user tried to use widgets in IPython terminal and got a cryptic error:

```
AttributeError: 'NoneType' object has no attribute 'session'
```

I just tried with the beta and got a warning rather than an error:

```
 3│ interact(f, x=10)
[TerminalIPythonApp] WARNING | Widget Javascript not detected.  It may not be installed or enabled properly.
Widget Javascript not detected.  It may not be installed or enabled properly.
10
 3> <function __main__.f>
```

If the widgets aren't even in a kernel, trying to use them should fail straight away with a clear error message describing what's required.

**Comment by SylvainCorlay** [comment]
This is already solved in master. Now people can instantiate interactive widgets from any python context. Obviously they will not show...

**Comment by takluyver** [comment]
Right, I found that with the beta. But instantiating something that can't do anything doesn't seem very useful, and the error about not finding javascript isn't very clear if you don't know that it needs the notebook.

**Comment by jasongrout** [comment]
Do you suggest we modify the message to say something like:

> WARNING | Widget frontend components not detected.  They may not be installed or enabled properly in a notebook, or your frontend may not support widgets.

**Comment by takluyver** [comment]
Something like that. Maybe a separate warning if it's not even running inside a kernel?

I was thinking that it should be an error to use them outside the kernel, but I can see why you might want to be able to do so for testing.
