### ISSUE TITLE
Attempting to remove a Dropdown Widget results in error 

### ISSUE THREAD

**Issue by jdetle** [ipython/ipywidgets#1039]
```javascript
 DropdownView.prototype.remove = function () {
        document.body.removeChild(this.droplist);
        _super.prototype.remove.call(this);
    };
```
This code in `widget_selection.js` currently does not work. Attempting to remove a dropdown widget by clicking the fontAwesome 'X' to the left of it results in this error:

>Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Along the same lines, I would expect Clear Outputs in the Notebook Cell menu to remove widgets, is this the expected experience?

I'm opening this issue with the intention of fixing it.

**Comment by jasongrout** [comment]
Thanks!

Removing a dropdown works now in master - I think it may have been fixed in #1053.

The "Clear Outputs should clear widgets" is #637.

**Comment by jasongrout** [comment]
![cleardropdown](https://cloud.githubusercontent.com/assets/192614/22478377/95a8fe2c-e7b7-11e6-9332-08e3d691897c.gif)

**Comment by jdetle** [comment]
Thanks @jasongrout, I appreciate the fix and I'm sorry I couldn't get to this sooner!
