### ISSUE TITLE
Dropdown widget steals [ESC] key

### ISSUE THREAD

**Issue by jdemeyer** [ipython/ipywidgets#1049]
1) In the Jupyter notebook, type
```
Dropdown(options=["abc"])
```

2) Click on the widget

3) Move focus to another cell in the notebook

4) Press [ESC]. This key will be captured by the Dropdown widget instead of the notebook cell.

**Comment by SylvainCorlay** [comment]
@jasongrout I discussed this with @jdemeyer in person and it looks like a phosphorjs issue, pretty serious.

**Comment by jasongrout** [comment]
Fixed (temporarily) by #1057.

**Comment by SylvainCorlay** [comment]
thanks
