### ISSUE TITLE
Widget send() doesn't check the buffers type

### ISSUE THREAD

**Issue by martinal** [ipython/ipywidgets#1059]
This can crash the kernel:
```
from ipywidgets import IntSlider
w = IntSlider()  # any widget will do
w.send({},
    buffers=[b"buf"])  # works, memoryview(b"buf") is correct
#    buffers=[1])  # fails correctly with TypeError: object of type 'int' has no len()
#    buffers=[u"buf"])  # crashes because len("buf") is valid but memoryview("buf") is not
#    buffers={u"buf": None})  # crashes for same reason because iteration over dict yields keys
```
The main error is this: (from the `[u"buf"]` case):
```
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/.../env/lib/python3.5/site-packages/zmq/sugar/socket.py", line 356, in send_multipart
    _buffer_type(msg)
TypeError: memoryview: a bytes-like object is required, not 'str'
```

**Comment by jasongrout** [comment]
I agree: we should be checking the type, and definitely don't make the kernel crash.

**Comment by jasongrout** [comment]
This error is at the lowest level we deal with (i.e., directly in the zmq socket). @minrk - at what level do you think we should check that the buffers provided really are buffers (e.g., `isinstance(buffer, memoryview)`? Maybe in the session send at https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/session.py#L701 ?

**Comment by minrk** [comment]
@jasongrout I think you're spot on that Session.send the right place. The check should be if it's buffer-interface-providing, so the obvious test is:

```python
if not isinstance(buf, memoryview):
    try:
        memoryview(buf)
    except Exception:
        raise TypeError("Buffers must provide buffer interface...")
```

I don't know if creating an unused memoryview can ever be expensive.
