### ISSUE TITLE
Play widget is not triggering handler from observe.

### ISSUE THREAD

**Issue by starhel** [ipython/ipywidgets#1060]
Play widget is not triggering handler, when value is changed. It's same as #676, but for me still not working. I've tried with last stable: 5.2.2 and latest beta: 6.0.0.beta6 from pypi. Unfortunately workaround proposed in previous issue  doesn't work either. In 6.0.0.beta6 my own widget stop working too. Any idea for workaround in 5.2.2? 

```from ipywidgets import Play
play = Play(max=10)
play.observe(lambda hello: print(hello))
play
```
ipywidgets: 5.2.2, 6.0.0.beta6
jupyter-client: 4.4.0

**Comment by SylvainCorlay** [comment]
Hi, this is a known issue. Since the timer is global to the notebook, the print statements don't have a cell to be displayed under.

A solution is to use the output widget for printing.

**Comment by starhel** [comment]
Thank you very much for info! It's working now :)
