### ISSUE TITLE
is there a way to increase a widget's size or open it fullscreen in a new window?

### ISSUE THREAD

**Issue by cornhundred** [ipython/ipywidgets#1063]

**Comment by jasongrout** [comment]
Not in the current stock notebook. In JupyterLab, it will be possible to drag a widget out of the notebook into a tab of its own, which could take up the full screen.

If you are running a widget from a webpage, not in a notebook, then of course it can be as big as you want.

**Comment by cornhundred** [comment]
Okay, thanks.

**Comment by anentropic** [comment]
It would be nice to have something like you have when eg watching videos on YouTube... where you can click a button to expand the widget to full-screen, then hit Esc to go back to the notebook in browser window

**Comment by jasongrout** [comment]
Others have also suggested having a 'full screen' widget, i.e., basically a Box widget which can have children, but also has a small icon that triggers the browser full-screen mode. Can you file an issue for this? We can help you get started implementing it if you'd like too.
