### ISSUE TITLE
Tab widget's internal _titles dictionary has its keys changed from int type to unicode

### ISSUE THREAD

**Issue by mgeplf** [ipython/ipywidgets#1065]
After a state change (ie: a different tab is selected), the tab widget's internal `_titles` dictionary's keys get changed from type int to type unicode. 

This happens because `ipywidgets/widgets/widget.py:Widget.set_state` uses a de-serialized json update that has unicode keys instead of integers.

This probably applies to all the `_SelectionContainer` classes.

Any 'easy' fix would be to `index = unicode(int(index))` in the set_title and get_title methods, but I find this too hacky.

Attached is a notebook which exhibits the behavior: Out [2] shows the `_titles` dict before any tabs have been clicked, and the last output is after a tab has been clicked:
[tab_widget.zip](https://github.com/ipython/ipywidgets/files/742233/tab_widget.zip)

**Comment by jasongrout** [comment]
Thanks! To reproduce:

```
from ipywidgets import Tab, IntSlider

t = Tab([IntSlider(), IntSlider()])
t.set_title(0, 'tab1')
t.set_title(1, 'tab2')
t
```
```
t._titles
```

**Comment by jasongrout** [comment]
The problem here is that in javascript:

```
> var s = {1: 'hi', 2: 'bye'}; s
Object {1: "hi", 2: "bye"}
> JSON.stringify(s)
"{"1":"hi","2":"bye"}"
```
Indeed, looking at the JSON spec (http://www.json.org/), we see that dictionaries will *always* have string keys.

**Comment by jasongrout** [comment]
@mgeplf - how does #1066 look to you? I think your solution is the best way to go, since the widget protocol spec will have to have string keys.

**Comment by mgeplf** [comment]
Looks good to me.  Thanks for the quick response, appreciated.
