### ISSUE TITLE
Widget layout with respect to an image

### ISSUE THREAD

**Issue by amoghskulkarni** [ipython/ipywidgets#1067]
Is there a way to render widgets (horizontally) adjacent to a plot? I have had a look at `VBox` and `HBox` widgets [here](http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#Box) to get the similar result, but these seem to accept only a list of other widgets, not plots.

**Comment by jasongrout** [comment]
You could either use an OutputWidget to contain the plot (or any output), or you could use a plotting library like bqplot that generates widgets, which you could directly embed in an hbox or vbox.

**Comment by jasongrout** [comment]
Here's an example using OutputWidget in JupyterLab. The OutputWidget may not work in 5.2.2 (it was experimental at that time.)

```
from matplotlib import pyplot as plt
import ipywidgets as w
from IPython.display import display, clear_output
from traitlets import observe

sliders = [w.IntSlider(), w.IntSlider(), w.IntSlider()]
o = w.Output()

def update_chart(change):
    with o:
        clear_output()
        plt.plot([s.value for s in sliders])
        plt.show()
for s in sliders:
    s.observe(update_chart, 'value')
update_chart(None)
w.HBox([w.VBox(sliders), o])
```
<img width="950" alt="screen shot 2017-02-02 at 2 06 42 pm" src="https://cloud.githubusercontent.com/assets/192614/22564058/ff5f7324-e950-11e6-989a-b4d35b342036.png">

**Comment by SylvainCorlay** [comment]
Also, with ipympl, matplotlib figures are proper widgets that can be used
with HBox and VBox and they have all the mouse interactions working.

**Comment by jasongrout** [comment]
the bqplot package (https://github.com/bloomberg/bqplot, docs at http://bqplot.readthedocs.io/en/stable/) lets you do plotting in a widget framework, and works in the current notebook. Also, the updates are much smoother with bqplot.

```
from bqplot import pyplot as plt
import ipywidgets as w

sliders = [w.IntSlider(), w.IntSlider(), w.IntSlider()]
fig = plt.figure()
plot = plt.plot([s.value for s in sliders])

def update_chart(change):
    plot.y = [s.value for s in sliders]
for s in sliders:
    s.observe(update_chart, 'value')
update_chart(None)
w.HBox([w.VBox(sliders), fig])
```
<img width="901" alt="screen shot 2017-02-02 at 2 14 54 pm" src="https://cloud.githubusercontent.com/assets/192614/22564302/05513c44-e952-11e6-9dad-d9bbb42b975a.png">

**Comment by jasongrout** [comment]
CC @dmadeka ^

**Comment by jasongrout** [comment]
Does that answer your question?

**Comment by amoghskulkarni** [comment]
Yes, it does. Thank you @jasongrout and @SylvainCorlay for the pointers. Will try out these things and get back to this issue if needed.

**Comment by amoghskulkarni** [comment]
@jasongrout Sorry, but I am having some trouble to get the widgets working with bqplots. When I try to run the following code, the widgets are not getting rendered in the notebook.
```
from bqplot import pyplot as plt
import ipywidgets as widgets
from pandas import DataFrame

parseutils = SqliteParseUtils(top)

data = DataFrame({'timestamps': parseutils.getTimestampValues(),
                  'Adder.sum': parseutils.getUnknownValues('Adder.sum'),
                  'Adder.a': parseutils.getUnknownValues('desvar_a.a'),
                  'Adder.b': parseutils.getUnknownValues('desvar_b.b')})

# step config
Adder_a__step = 0.1
Adder_b__step = 0.1

# axes configuration
x_axis_values = data['Adder.a']
y_axis_values = data['Adder.sum']

fig = plt.figure(title='AdderDOEProblem')
p = plt.plot(x_axis_values, y_axis_values)
domain_options = ['Adder.a', 'Adder.b']
range_options = ['Adder.sum']

widgets_list = [widgets.Dropdown(options=domain_options, value=domain_options[0], description='domain'),
                widgets.Dropdown(options=range_options, value=range_options[0], description='range'),
                widgets.FloatSlider(value=0, min=0, max=1, step=Adder_a__step, description='Adder.a'),
                widgets.Checkbox(description='Adder.a (all values)', value=True),
                widgets.FloatSlider(value=0, min=0, max=1, step=Adder_b__step, description='Adder.b'),
                widgets.Checkbox(description='Adder.b (all values)', value=True)]

def update(change):
    # Dummy logic
    p.y = [i+1 for i in p.y]

for w in widgets_list:
    w.observe(update, 'value')
update(None)
widgets.HBox([fig, widgets.VBox(widgets_list)])
plt.show()
```

My output is this -

![output](https://cloud.githubusercontent.com/assets/11549656/22764140/7949966a-ee2e-11e6-9d03-635f39a753dd.PNG)

What am I missing?
