### ISSUE TITLE
widgets.Label initialisation problem with Latex

### ISSUE THREAD

**Issue by mikecroucher** [ipython/ipywidgets#1068]
The following code fails with `[Math Processing Error]` but as soon as I move the slider, it works as expected. Is this a mistake on my part or a bug?

I'm using ipywidgets 5.2.2

```
from sympy import Symbol, sin, series, init_printing,Eq,latex
from ipywidgets import interact,widgets
x = Symbol('x')

def expand_sin(num_terms=2):
    return(Eq(sin(x),series(sin(x),x,n=num_terms)))

slider = widgets.IntSlider(value=2,min=1,max=20,step=1)
equation = widgets.Label(
    value="$$"+latex(expand_sin(2))+"$$",
    disabled=False
)

interaction = widgets.VBox([slider,equation])

def callback(*args):
    latex_eq = latex(expand_sin(slider.value))
    equation.value='$$' + latex_eq + '$$'

slider.observe(callback)

interaction
```

**Comment by jasongrout** [comment]
Thanks for the report. This is fixed in master (cf. #550, #560). I just verified it too.

**Comment by jasongrout** [comment]
I did notice when testing this that the Label widget (with its new strict size limits) probably isn't appropriate for rendering arbitrary math anymore. I've opened #1072 for a discussion.
