### ISSUE TITLE
Widget to render html + math?

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipywidgets#1072]
Since we don't have a Latex widget anymore, and the Label widget now has strict size limits, the HTML widget seems like the appropriate widget to render math in. However, it doesn't, it just puts the raw html on the page without typesetting it.

Should we (a) enable math rendering (b) make an option on the html widget to render math, or (c) make a new HTMLMath widget?

It's a one-line change to render math, but I think it makes sense to keep the stock HTML widget as plain as we can. I think having a new HTMLMath widget makes sense.

CC @SylvainCorlay.

**Comment by SylvainCorlay** [comment]
What about a multiple-lines label widget? `Caption`.

**Comment by jasongrout** [comment]
The use case I'm thinking of is an interact that has output that may include lots of text and formulas. It's not so much a caption or label, just a block of text with math.

**Comment by jasongrout** [comment]
(of course, an actual interact works fine since the output rendering handles math; this is more like just an html widget that also typesets math...)

**Comment by mikecroucher** [comment]
I think a HTMLMath widget is a great idea.  The use case I have in mind is when you want a widget to  have multiple outputs.  

For example, you might be using sympy to perform a series expansion of sin(x). Outputs would include the rendered mathematics, a plot of sin(x) overlayed with a plot of the power series.  

The way I currently think about doing this is to use a Vbox output widget that contains the mathematics in one cell and the plot (as an image) in another.  

This pattern probably comes from my days as a Mathematica user where I'd write a `Manipulate` that had several outputs which I'd organise with a [Pane](http://reference.wolfram.com/language/ref/Pane.html)

**Comment by jasongrout** [comment]
Should we just call it `Math`, or `HTMLMath`?

**Comment by jasongrout** [comment]
I'm leaning towards `HTMLMath`, since `Math` sounds like it would be *just* the mathematics, e.g., the value would be just `\frac{x^2+x+1}{x+1}`.
