### ISSUE TITLE
Web3 example failing due to new security settings in notebook

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#1076]
The command used to start the notebook server is

`python -m notebook --no-browser --NotebookApp.allow_origin="*"`

- first, REST api calls are redirected to the login page, unless token and password are disabled.
- second, even when disabling token/password, the REST call to `api/kernel` returns a 403 (forbidden).

Ping @minrk.

**Comment by minrk** [comment]
I think the fix should be to use a token, which would also make the `allow_origin` option unnecessary.

**Comment by SylvainCorlay** [comment]
`api/kernel` would be made available when using a token?

**Comment by minrk** [comment]
Yes, everything ought to work.

**Comment by SylvainCorlay** [comment]
This is going to require a UI in the Web3 example to provide the token in addition to the server URL, or parse a url with `token='sdhkjshd'`...
