### ISSUE TITLE
Dropdown checklist possible (multiple selection dropdown)?

### ISSUE THREAD

**Issue by reckoner** [ipython/ipywidgets#1080]
Hi,

Is it possible to create a dropdown, but one that allows more than one element to be selected?

Thanks!

**Comment by jasongrout** [comment]
Not using the current set of widgets we provide. You'd have to use the MultipleSelect (not a dropdown), or you could use a series of checkboxes. Or write a custom widget.

**Comment by jasongrout** [comment]
Happy to discuss further if you'd like...

**Comment by reckoner** [comment]
I think you mean [SelectMultiple](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html?highlight=SelectMultiple) right?

Let me look into it.  Thanks!

**Comment by jasongrout** [comment]
> I think you mean SelectMultiple right?

Yes, thanks.

**Comment by danish-monu** [comment]
@jasongrout is such a dropdown menu as suggested by @reckoner foreseen in future. That would really cool to have. Currently, if I have 100s of options, it looks ugly to show all the options in a big selection list. ofcouse, i can make it shorter by passing the row paramter. but still that would look good either in a notebook where i have multiple such selection dropdowns.

**Comment by jasongrout** [comment]
We've tried to keep the base controls set to be basic html controls, and encourage people to have custom widget libraries for more advanced things (like maps, 2d plots, 3d plots, etc.). @maartenbreddels is working on a set of controls based on materialui, for example, that would have more advanced controls.

So in summary, sure, definitely possible to have widgets like that. Whether they are in the basic controls package or in another widget package is a different question.
