### ISSUE TITLE
"Save notebook with widgets" doesn't seem to work

### ISSUE THREAD

**Issue by ketch** [ipython/ipywidgets#1085]
I have set up a simple notebook with a widget (which works fine locally), clicked the "save with widgets" menu option, uploaded, and viewed on nbviewer.  No widget appears in the notebook (although I can see the widget data in the .ipynb file, at the bottom).  Here it is:

http://nbviewer.jupyter.org/gist/ketch/36daf198782102a30f318d38fa5ae13a

I am running ipywidgets 6.0.0.beta7 and widgetsnbextension 2.0.0.beta14.  I've tried with both Chrome and Safari browsers.

**Comment by fperez** [comment]
Can you test again? Playing with Randy, I made [this gist](https://gist.github.com/fperez/b969f848726cb1e697ad1b8902d6e59e), which seems to [render fine on nbviewer](http://nbviewer.jupyter.org/gist/fperez/b969f848726cb1e697ad1b8902d6e59e?flush_cache=true).

If it works for you, we can close.

**Comment by ketch** [comment]
After updating everything today, it seems gives me this:
<img width="405" alt="screen shot 2017-03-04 at 2 10 08 pm" src="https://cloud.githubusercontent.com/assets/697763/23582677/7276f4d6-00e4-11e7-8b7d-ab8c2bec54c4.png">

If that is the intended behavior, then you can close this.

In practical terms for widgets controlling plots, it seems that Staticwidget was removed and has not been replaced by anything; correct?

**Comment by ketch** [comment]
By the way, the kind of output in that screenshots also appears in various places in the docs.  Is that intended?

**Comment by SylvainCorlay** [comment]
The output widget used by `@interact` has no counterpart in the static web contexts. So this is the expected behavior as of now.

**Comment by ketch** [comment]
By the way, @fperez when I look at the gist on nbviewer, the print statement in the second widget does not work.  Instead there is the same "could not create model" message.  Do you see something different?

**Comment by SylvainCorlay** [comment]
Same comment as above. Output widgets generated by `@interact` are not yet supported in static web pages.

**Comment by ketch** [comment]
Okay, thank you for the helpful explanations.  I'll go ahead and close.

**Comment by SylvainCorlay** [comment]
It seems that the use of interact + static embedding is something people want. I will go ahead and make an output widget for the static embedder for 6.0.1.

**Comment by ketch** [comment]
@SylvainCorlay That would be highly appreciated!

**Comment by SylvainCorlay** [comment]
No problem. We can most likely reuse a lot of what we did for jupyterlab there.
