### ISSUE TITLE
'Select' widget does not support empty list in options any more

### ISSUE THREAD

**Issue by ChakriCherukuri** [ipython/ipywidgets#1086]
Previously *Select* widget supported empty list in the options. Now it throws a TraitError saying "'options' must not be empty"!

Please enable Select to get initialized with an empty list (and have value attribute initialized to None). We have use cases where the Select list has no options initially and later gets populated based on some event.

**Comment by jasongrout** [comment]
The design constraint we're up against here is that `None` could be a valid option as well as signifying no option selected (e.g., `s=Select(options=[None])` is perfectly valid, and `s.value` is then `None`). Instead, we suggest that you create your own sentinel value for no option selected, such as `Select(options=[''])`.

**Comment by jasongrout** [comment]
(I talked with @ChakriCherukuri about this and he agreed that closing was fine)

**Comment by jasongrout** [comment]
We talked a bit more about this, after @ChakriCherukuri kept running into corner cases, and decided that it was fine to implement an empty options list. If the options list is empty, then the value is set to None as a convention. If the options list has things in it, then value should be one of the things in the list (which could possibly be None).

**Comment by SylvainCorlay** [comment]
I wonder what would be the semantic of that.

**Comment by jasongrout** [comment]
I have a WIP PR coming up.
