### ISSUE TITLE
WeakMap is not defined

### ISSUE THREAD

**Issue by ivanov** [ipython/ipywidgets#1095]
Even after the changes in #1094, as best as I can tell, the webpacking process introduces a dependency on WeakMap, which is not available in older browser. 

I think there's a way of polyfilling WeakMap, but I'm not sure how to best proceed to do that.

**Comment by jasongrout** [comment]
What browsers are we going after here?

**Comment by ivanov** [comment]
An older version of Chromium... I'll send you a MSG

**Comment by jasongrout** [comment]
Nominally, I think we're shooting for similar requirements to JLab: Firefox 49+, Chrome 39+, Safari 10+, but also IE 11 for widgetsnbextension.

**Comment by ivanov** [comment]
Ah, ok, closing this then. Thanks for the details, @jasongrout
