### ISSUE TITLE
wishlist: 2-axis X-Y slider

### ISSUE THREAD

**Issue by keithw-integris** [ipython/ipywidgets#1105]
Imagine a widget that presents a square (or rectangular) area (like a drawing canvas), inside of which the user can click and drag to move a knob, essentially a solid black disk or a 'plus-sign' X-Y coordinate marker.  This would enable simultaneous X-Y control of two variables, much like a joystick.  It would essentially combine a pair of horizontal and vertical _IntSliders_ (or _FloatSliders_) into a single control widget.

I see the _Controller_ widget, which relies on third party physical hardware, a gamepad of some sort.  I honestly don't know how that works since I don't even own such a device, but it would be nice to have a (presumably comparable) option that doesn't require additional hardware, but rather which utilizes the computer's already available 2-axis input (mouse, trackpad, trackball, etc.).

**Comment by SylvainCorlay** [comment]
@keithw-integris it is already possible with libraries that are built upon ipywidgets such as bqplot

**Moving points around:**

![move](https://cloud.githubusercontent.com/assets/2397974/22906401/97acd3be-f244-11e6-9a4e-5f0427b59113.gif)

The benefit over a regular 2-D slider is that you could have any scale, even a log scale...

**You can also select intervals:**

![draw](https://cloud.githubusercontent.com/assets/2397974/22906427/aedad84c-f244-11e6-856f-75549f956653.gif)

**Or draw:**

![draw](https://cloud.githubusercontent.com/assets/2397974/22906489/f9cb4c10-f244-11e6-8874-d290a6b240be.gif)

And register handlers to changes just like you do with the sliders...

I don't think that a 2-D slider is in scope for ipywidgets core, but more than a collection of widgets it is a framework to build upon.

**Comment by keithw-integris** [comment]
Thank you.  I will look into these other options.

I'm not sure I agree that it is out-of-scope (there is the gamepad controller after all, which is if anything a **more** eccentric approach to the same user interaction).  Furthermore, any interface that assists developers in creating GUIs might be considered good fodder for notebook GUI widgets in general, even if a bit esoteric).

On the other hand, I admit that such a 2-axis tool is rare in general (the core UI elements provided by Mac and Windows libraries don't offer such a tool).  On the other **other** hand, the notion isn't completely alien either.  It is a popular GUI tool in 3D modeling programs for example.  Bryce comes to mind as an example.

I appreciate you going to the trouble to show me the alternative options.  I'll try to adapt those to my needs.

Thanks again.

Cheers!

**Comment by SylvainCorlay** [comment]
@keithw-integris these are not so much alternative in that they are built upon ipywidgets. I agree that Controller was more esoteric though :)

**Comment by keithw-integris** [comment]
Not to turn the comments section into a discussion forum (for which it may not be the best format), but I'm not certain I know how to replicate those code snippets above.  I clearly need to add some additional code to make them work.  May I contact you off-git for further assistance if I get stuck?

**Comment by SylvainCorlay** [comment]
You can check out the example notebooks for bqplot which probably cover these examples.

GH issues are a good place for specific questions because they are easily addressable compared to mailing lists and chat rooms.

**Comment by jasongrout** [comment]
I would love to see a simple standard 2d slider widget - I wouldn't be opposed to it in core, but it could be fine as a separate 3rd party widget too. We've experimented with such things in Sage interacts for years.

Even though it's not a standard browser control, the scientific bent of the Jupyter I think could justify such a widget in the core framework.

However, to Sylvain's point, many needs for a 2d slider may be more intuitively filled by actually picking a 2d point on a graph or image.

**Comment by OliverEvans96** [comment]
I agree that this would be a great feature and suitable for core - Mathematica has [`Slider2D`](http://reference.wolfram.com/language/ref/Slider2D.html?view=all).
