### ISSUE TITLE
UI review

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipywidgets#1110]
This is a placeholder for a UI review by @cameronoelsen (and @ellisonbg?) for all of the changes we've made for 6.0.

**Comment by jasongrout** [comment]
@cameronoelsen - I updated the dev-install script to contain some instructions about creating a clean environment: https://github.com/ipython/ipywidgets/blob/master/dev-install.sh

**Comment by jasongrout** [comment]
One major thing that comes up almost immediately when I've put these widgets in front of someone is that they want to make the textbox, dropdown, and similar widgets shorter. I think the length and tight vertical spacing between widgets contributes to the feeling that the widgets are a bit wide. One option is to maybe make the widget width, say, 400px (so a bit more room for the slider), and make the text, dropdowns, etc. 200px, and maybe the buttons 100px (they seem a bit wide as-is as well, I think). Or maybe the slider at 360 px (lots of divisors!!!), the inputs at 180px, and the buttons at 120px.

**Comment by SylvainCorlay** [comment]
I think that changing default dimensions of widgets at this stage is likely to cause lots of issues with alignment i combinations of boxes and custom widgets etc...

**Comment by cameronoelsen** [comment]
http://nbviewer.jupyter.org/gist/cameronoelsen/a5520188d8f9afd4ef8e7c8f204788c4/Widget%20List.ipynb
