### ISSUE TITLE
Date range picker (feature request)

### ISSUE THREAD

**Issue by jbednar** [ipython/ipywidgets#1118]
The DatePicker looks very useful.  Would having a DateRangePicker be too much to ask? :-)  Often one wants to visualize data from a certain range of dates, and it would be nice to select that range visually (e.g. by dragging over the date range) rather than as a difference between two separate date pickers...

**Comment by jasongrout** [comment]
Thanks, I'm glad the date picker looks interesting to you. It's really just a thin wrapper around the browser date input, which cannot represent a range (in fact, the date control itself is not even supported by firefox yet, see https://developer.mozilla.org/en-US/Firefox/Experimental_features) or apparently even IE.)

I think this would be a great idea for a third party widget distributed as a separate package, built on top of ipywidgets. It will likely need to use some other date picker package.

**Comment by dmadeka** [comment]
This is very easy to do in bqplot @jbednat .. just create a Figure with no marks and an x scale that has your dates as the domain, and use a brush selector to select the Interval. Since bqplot is built on the widget framework, it's easy to integrate with other widgets
