### ISSUE TITLE
request_state promise and update message

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#112]
When requesting state from the back-end, a regular `update` message is sent back, and a complicated logic to match the message id is applied to resolve the promise correctly. Another consequence is that the resolution of the `request_state` promise is external to the promise code itself.

I think that the response to a request state should not be a regular update but a separate message type.

**Comment by jdfreder** [comment]
> When requesting state from the back-end, a regular update message is sent back, and a complicated logic to match the message id is applied to resolve the promise correctly. Another consequence is that the resolution of the request_state promise is external to the promise code itself.
> 
> I think that the response to a request state should not be a regular update but a separate message type.

I don't see how a separate message type will solve these problems.  Because the notebook doesn't have request/reply messaging, we'll still need to map the responses ourselves.

**Comment by jdfreder** [comment]
@SylvainCorlay ?

**Comment by SylvainCorlay** [comment]
I was trying to push for request/reply messages in comm, but I think that it is not going to happen in a near future.

**Comment by jdfreder** [comment]
I pushed the target to 4.2, so we can keep it on our plate for when request/reply messages get added.

**Comment by SylvainCorlay** [comment]
Should we consider this one solved?
