### ISSUE TITLE
Dependent version of jupyterlab not released

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipywidgets#1126]
Confused, the version of jupyterlab that ipywidgets depends on hasn't been released, at least not in a form that works:

https://github.com/jupyterlab/jupyterlab/blob/master/package.json#L3

@blink1073 can you clarify the status of 0.16.2?

**Comment by blink1073** [comment]
Ohh, I know what is happening.  This is probably what caused Grant's error in the json renderer as well.  I made a patch release which is tagged but the version in master still says 0.16.0.  I will address when I get back home.

**Comment by blink1073** [comment]
Cf https://github.com/jupyterlab/jupyterlab/issues/1732#issuecomment-280683864

**Comment by ellisonbg** [comment]
Thanks, sounds like this is on jlab then...

**Comment by blink1073** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/issues/1739.
