### ISSUE TITLE
Run all example notebooks and save widget state

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipywidgets#1132]
Before we cut 6.0 we will need to rerun all of the example notebooks and save widget state. I haven't done that before so am not sure how it all works. Also, I need to switch gears over to helping with the 5.0 notebook release.

**Comment by SylvainCorlay** [comment]
I have done this for the jupyter-js-widgets prerelease.

FYI, it is not necessarily needed to re-save notebookes every time we make a release. Indeed, the widget state includes a semver range for the version of the front-end code that is required. We use this semver both in the context of Jupyterlab and static embedding.

**Comment by jasongrout** [comment]
I added this to the release process notes in #1116.
