### ISSUE TITLE
Check checkbox size on windows and linux

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipywidgets#1139]
Apparently the checkbox is abnormally large on linux and windows, but looks fine on OS X. Perhaps instead of `large` at https://github.com/ipython/ipywidgets/blob/master/jupyter-js-widgets/css/widgets-base.css#L329, we should give a specific percentage, like 120%.

**Comment by maartenbreddels** [comment]
Here is my screenshot
 * OS: scientific linux 7
 * Browser: Chrome Version 56.0.2924.87 (64-bit)
![checkbox](https://cloud.githubusercontent.com/assets/1765949/23167920/952b1314-f846-11e6-9899-641e03172e84.png)

**Comment by maartenbreddels** [comment]
FWIW, it's not the `font-size: large`, but deselecting the `height: var(--jp-widgets-inline-height);` ( https://github.com/ipython/ipywidgets/blob/master/jupyter-js-widgets/css/widgets-base.css#L327 ) does make it smaller.

**Comment by jasongrout** [comment]
Weird, I'm not able to reproduce this issue on Chrome/Firefox on OS X or on Windows. However, I do see that both font-size and height affect the checkbox size on OS X in Firefox.

Let's get rid of that line, since we are also setting the line-height and aligning center.

**Comment by jasongrout** [comment]
Can you check to see if #1141 fixes the problem for you?

**Comment by maartenbreddels** [comment]
Well, if I deselect that line from the chrome developer tools, that is effectively the same, and yes, that gives me a much better/normal size, and on OS X it doesn't do anything
