### ISSUE TITLE
Dropdown button_style attribute doesn't work

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipywidgets#1142]
Since we use the select element for dropdowns now, we completely ignore the button_style attribute.

**Comment by jasongrout** [comment]
Perhaps we just delete the dropdown style attribute? We don't provide those style attributes on other input widgets, only on buttons.

Essentially this is just deleting this attribute: https://github.com/ipython/ipywidgets/blob/master/ipywidgets/widgets/widget_selection.py#L229

**Comment by jasongrout** [comment]
Actually, given our choices to (at least temporarily) change the dropdown to a select, perhaps we literally rename it and deprecate the dropdown? In the future with a custom dropdown, we can just change the select to a dropdown?

**Comment by SylvainCorlay** [comment]
I have no opinion on this.

**Comment by SylvainCorlay** [comment]
Actually I prefer to keep the dropdown. We have a phosphor implementation of it and really nice styling. I guess that it can get back in when we fix the issue.

**Comment by jasongrout** [comment]
It's broken right now, so I think we should either remove the attribute or fix it (i.e., add styles to the select widget to do fulfill this).

**Comment by jasongrout** [comment]
I'm happy to remove the attribute - any problems with that?

**Comment by SylvainCorlay** [comment]
ok I think that it is fine to remove the attribute.
