### ISSUE TITLE
ToggleButtons with icons not responding to icon click

### ISSUE THREAD

**Issue by maartenbreddels** [ipython/ipywidgets#1147]
This may be related to #220 
With this code (ipywidgets 6.0.0.beta9)
```
import ipywidgets as widgets
b = widgets.ToggleButtons(options=["a", "b", "c"], icons = ["apple", "book", "car"])
def echo(*args, **kwargs):
    print(args, kwargs)
b.observe(echo, "value")
b
```
clicking anywhere on the button except the icon works, it executes echo on click. However, clicking on an icon does make the button appear 'half' selected, but does not fire an event.

**Comment by SylvainCorlay** [comment]
Fixed. Just need to put `pointer-events: none;` in the css for the font-awesome icon.
