### ISSUE TITLE
Remove widget data from interact example

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#1154]
The output widget does not have a counterpart in web contexts at the moment.

See http://ipywidgets.readthedocs.io/en/latest/examples/Using%20Interact.html

**Comment by jasongrout** [comment]
Perhaps we should just make an output widget for the web context - the jupyterlab one should probably be very close to what we need.

**Comment by SylvainCorlay** [comment]
Yes, although this would be a 6.1 thing.
