### ISSUE TITLE
interact: tracebacks should be in the output area

### ISSUE THREAD

**Issue by jdemeyer** [ipython/ipywidgets#1155]
When an `interactive` function raises an exception, the traceback will always remain shown below the normal output area, even if some future run of the interactive function completes successfully. If several runs raise an exception, all tracebacks are shown. This is all very confusing, since it's hard to see whether the interactive function worked or raised an exception.

What should happen instead is that tracebacks while running interactive functions are treated like normal output. If the function raises an exception: show the traceback in the same output area used for normal output.

Context: In SageMath, it is quite common to use `eval()` on a `Text` widget, such that the user can input `sin(x)` and have it understood as the function `x |-> sin(x)`. Of course, something like `sin(x` will raise an exception. This is just to say that exceptions can be quite common.

**Comment by jasongrout** [comment]
Have you tried with the new ipywidgets 6.0 RC? We completely changed how output is handled, and errors *should* now appear exactly where the output would appear.

**Comment by jasongrout** [comment]
Yep, it looks like I'm reproducing your issue with widgets master. Thanks. Investigating...

**Comment by jasongrout** [comment]
@jdemeyer - thanks for noticing this. Does #1156 solve the issue for you?

**Comment by jdemeyer** [comment]
> @jdemeyer - thanks for noticing this. Does #1156 solve the issue for you?

No. In fact I see absolutely no change in behaviour when I apply those changes.

**Comment by jdemeyer** [comment]
OK. I see now why: my exception occurs in `get_interact_value`, not in the actual call of the interactive function. Pull request coming up...
