### ISSUE TITLE
Button icon has 4px margin, throwing it off center when no text

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipywidgets#1160]
When there is just an icon, and no text, the icon is off center in the button because it has a 4px right margin: https://github.com/ipython/ipywidgets/blob/master/jupyter-js-widgets/css/widgets-base.css#L121

We should figure out a way so that the icon could be centered when it is the only thing on the button.

Putting as 6.0, but could be bumped if the fix isn't easy.

**Comment by SylvainCorlay** [comment]
Adding a 4px left margin too could be good enough.

**Comment by jasongrout** [comment]
yes, though that could throw offcenter an icon+text combination.

**Comment by SylvainCorlay** [comment]
I will look at the few 6.0 issues on Monday. Will add the js logic if the
4px left margin does not look good when there is a caption.
