### ISSUE TITLE
Missing components

### ISSUE THREAD

**Issue by kersulis** [ipython/ipywidgets#117]
I have tried running `pip install -e .` both inside and outside a virtualenv (jupyter notebook is installed in both cases), and I keep getting errors. This appears to be the most relevant part of the terminal output:
```bash
    > ipython-widget-deps@4.0.0 css /home/jkersulis/Documents/ipywidgets
    > node build_css.js
    
    > lessc --include-path=./less_include ./ipywidgets/static/widgets/less/widgets.less ./ipywidgets/static/widgets/css/widgets.css
    FileError: '/components/bootstrap/less/variables.less' wasn't found. Tried - /components/bootstrap/less/variables.less,/home/jkersulis/Documents/ipywidgets/ipywidgets/static/widgets/less/components/bootstrap/less/variables.less,/home/jkersulis/Documents/ipywidgets/less_include/components/bootstrap/less/variables.less in /home/jkersulis/Documents/ipywidgets/ipywidgets/static/widgets/less/widgets.less on line 2, column 1:
    1 // minimal imports from bootstrap - only variables and mixins
    2 @import "/components/bootstrap/less/variables.less";
    3 @import "/components/bootstrap/less/mixins.less";
    
    `lessc --include-path=./less_include ./ipywidgets/static/widgets/less/widgets.less ./ipywidgets/static/widgets/css/widgets.css` failed with status=1
```
The directory `ipywidgets/static/widgets/less/components` is indeed missing, but perhaps it is supposed to be generated during the installation process. Any idea what's going on here? Thank you for your time.

**Comment by jdfreder** [comment]
The following should do the trick.

```
npm install
npm run less
```

pip should have done this for you though...  Was there any other errors during pip install?  A lot of times it's just a permission error that occurs because something was installed with sudo when it shouldn't have been.

**Comment by kersulis** [comment]
It was a permission error, good call. I got this message when I ran `npm install`:

```bash
Error: EACCES, permission denied '/home/jkersulis/.config/configstore/bower-github.yml'
You don't have access to this file.
```
So I did a chmod on the file it mentioned, and `pip install -e .` worked after that. Thanks!

**Comment by jdfreder** [comment]
Awesome, glad I could help - sorry for the painful install.  When we figure out the Python/JS packaging problem, this kind of thing should be a lot easier.
