### ISSUE TITLE
Pattern for 'synchronous code'

### ISSUE THREAD

**Issue by maartenbreddels** [ipython/ipywidgets#1188]
As in, non-asynchronous.

I'm trying to implement a [savefig in ipyvolume](https://github.com/maartenbreddels/ipyvolume/blob/master/ipyvolume/pylab.py#L316).
Since I do not want to always capture the output of the WebGL canvas for performance reasons, I have a boolean `Figure.screen_capture_enabled`, that when true, will cause it write the captured screenshot into `Figure.screen_capture_data`.
So my hope was to do this:
```python
fig.screen_capture_enabled = True # this will trigger a redraw on the JS side
png_data = fig.screen_capture_data # it all is synchronous, this should contain the screenshot
```
However, it's only after a while that the data arrives in the widget's screen_capture_data.

I could attach an observer or 'screen_capture_data', but I want to savefig(..) function to return when the figure is really saved (plan to write some tests using this pattern).

So is there a good pattern to follow to make this happen, update a property, and then wait until another property is updated? I tried using a busy loop with `ipython.kernel.do_one_iteration()` in it, but then any output produced after that is gone (`print`'s and `IPython.display.display`'s).

**Comment by SylvainCorlay** [comment]
Hum, I am not sure. Probably by hooking into the tornado event loop.

**Comment by maartenbreddels** [comment]
Ok, i'm not reinventing the wheel then. If I find a solution I'll post it here or it can be found in `ipyvolume.pylab.savefig`

**Comment by SylvainCorlay** [comment]
Blocking code requesting something from the frontend would probably work by using the webserver event look from the kernel, by scheduling a polling of the trait attribute to be updated until it is or when a timeout is reached.

However, a screenshot most likely depend on the view. How do you want to handle the case of a single visualization displayed multiple times in the browser?

Maybe the save-fig should trigger the creation of a special view in a fixed-sized div...

**Comment by maartenbreddels** [comment]
Didn't think of the multiple views. And I'll keep that last idea in mind, since it's not unlikely that a savefig will need to be of higher resolution that what you have on screen.

**Comment by jasongrout** [comment]
As I think you found out, there's not really a good pattern for asynchronous code, since the messages and interaction with the server is fundamentally asynchronous. On top of that we have the issue of multiple views and/or frontends - which one should respond? The only synchronous type execution we have in jupyter (as far as I know) is the stdin channel/messages, which prompt the user for input and then continue with the result.

Closing for now, but feel free to reopen for discussion if you see a way to handle things with multiple views.
