### ISSUE TITLE
JupyterLab: HTML elements causing shortcuts to be run

### ISSUE THREAD

**Issue by AbdealiJK** [ipython/ipywidgets#1209]
I'm trying the current jupyterlab_widgets on pypi - 0.6.15 and the compatible jupyter - 0.16.2 and am seeing this:

On running:
```
from ipywidgets import *
HTML("<input></input>")
```

I click on the input box and type `m` and the code cell converts to a markdown cell.

Seems like the notebook event is being triggered

Note: This works fine in Jupyter Notebook - so, it's a feature parity issue

**Comment by jasongrout** [comment]
I just tried with ipywidgets master and jlab 0.17, and it works great for me. Let us get a pre-release out and try this again.

**Comment by AbdealiJK** [comment]
Seems like this is an issue with JLab and not ipywidgets.
Also it's been fixed in 0.17 👏 
https://github.com/jupyterlab/jupyterlab/issues/1630

**Comment by AbdealiJK** [comment]
@jasongrout would it still be possible to create a release though? Would be useful to have a release for 0.17 - the last release before the big split

**Comment by jasongrout** [comment]
@AbdealiJK - I worked on trying to get something for you together for a while - it's too complicated to put up on pypi, and we've moved past 0.17 already in master. If you want to run from source, you can clone the repo, checkout the new jlab0.17 branch I just uploaded, and install ipywidgets from there (`pip install -e ipywidgets`). Then you'll need to go into the jupyter-js-widgets, `npm install; npm run build`. Then you'll need to go into jupyterlab_widgets and it gets a bit tricky here: do something like `npm install ../jupyter-js-widgets` then `npm install; npm run build`, then `pip install -e .` to install the jupyterlab_widgets package. Then you'll need to install the labextension and enable it: `jupyter labextension install --sys-prefix --py jupyterlab_widgets`, `jupyter labextension enable --sys-prefix --py jupyterlab_widgets`. I think that should work (but I haven't tested it completely).

**Comment by AbdealiJK** [comment]
Hi @jasongrout Thanks for the instructions, but I can't get it to work :(

I'm running:
```
conda create -n testipy python=3.5 pip
source activate testipy

pip install jupyterlab==0.17.5
# Installed: MarkupSafe-1.0 appnope-0.1.0 bleach-2.0.0 decorator-4.0.11 entrypoints-0.2.2 html5lib-0.999999999 ipykernel-4.5.2 ipython-5.3.0 ipython-genutils-0.2.0 jinja2-2.9.5 jsonschema-2.6.0 jupyter-client-5.0.0 jupyter-core-4.3.0 jupyterlab-0.17.5 mistune-0.7.4 nbconvert-5.1.1 nbformat-4.3.0 notebook-4.4.1 pandocfilters-1.4.1 pexpect-4.2.1 pickleshare-0.7.4 prompt-toolkit-1.0.13 ptyprocess-0.5.1 pygments-2.2.0 python-dateutil-2.6.0 pyzmq-16.0.2 simplegeneric-0.8.1 six-1.10.0 terminado-0.6 testpath-0.3 tornado-4.4.2 traitlets-4.3.2 wcwidth-0.1.7 webencodings-0.5

git clone https://github.com/ipython/ipywidgets.git
cd ipywidgets
git fetch
git checkout jlab0.17
pip install -v -e .
# Installed: ipywidgets widgetsnbextension-2.0.0

cd jupyter-js-widgets
npm install
npm run build
cd ..

cd jupyterlab_widgets
npm install ../jupyter-js-widgets
npm install
npm run update
npm run build
pip install -e .
# Installed: jupyterlab-widgets
jupyter labextension install --py jupyterlab_widgets
# Says:
# X is not version compatible with installed JupyterLab version 0.17.5
#            Expects JupyterLab version ^0.16.2 from packaged module @jupyterlab/nbwidgets@0.6.15/lib/output.js
# but still copies the files

jupyter labextension enable --py jupyterlab_widgets
cd ..

jupyter lab
```

And getting:
<img width="888" alt="screen shot 2017-03-19 at 10 49 49 am" src="https://cloud.githubusercontent.com/assets/2200743/24078395/501a5108-0c92-11e7-9e23-9070dd64a935.png">

**Comment by jasongrout** [comment]
I'm really sorry - apparently I forgot to push my final changes to that branch on github! I just pushed, and tried your commands, and it works. Can you try rerunning your commands you listed above?

Thanks for giving a clear and comprehensive reproducible environment showing the problem!

**Comment by jasongrout** [comment]
@AbdealiJK ^

**Comment by AbdealiJK** [comment]
@jasongrout Thanks a lot ! worked like a charm :)
