### ISSUE TITLE
Removing styling attributes from the base DOMWidget model?

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#121]
The following attributes are accessible in the base widget model:

```JavaScript
'color'
'background'
'width'
'height'
'border-color'
'border-width'
'border-style'
'font-style'
'font-weight'
'font-size'
'font-family'
'padding'
'margin'
'border-radius'
```

I am conflicted about exposing them because I like the idea of widget models to only contain the relevant information. Besides, these names can be quite overloaded, and you could imagine a 'color' or 'margin' attribute name having nothing to do with a styling attribute.

**Comment by jasongrout** [comment]
Regardless of how we come out with this discussion, I think border-radius is going a bit far and should be removed.

**Comment by jdfreder** [comment]
> base widget model:

You mean the DOM widget?  It's not the base widget model.

> Regardless of how we come out with this discussion, I think border-radius is going a bit far and should be removed.

Maybe we should revisit the removal of get/set_css and exposure of `_css`.  `_css` feels kind of slimy, for lack of better words, when you actually use it.  Instead of re-adding them though, maybe we can come up with a better stateful mechanism.  I remember the issue was selectors.

**Comment by SylvainCorlay** [comment]
>> base widget model:

>You mean the DOM widget?  It's not the base widget model.

That's right.

>> Regardless of how we come out with this discussion, I think border-radius is going a bit far and should be removed.

> Maybe we should revisit the removal of get/set_css and exposure of `_css`.  `_css` feels kind of slimy, for lack of better words, when you actually use it.  Instead of re-adding them though, maybe we can come up with a better stateful mechanism.  I remember the issue was selectors.

It sounds like a good idea. Maybe simply adding convenience functions to edit `_css` or use an eventful dict.

**Comment by ellisonbg** [comment]
Another thing that might help us would be to build a more complex layer of
frontend classes:

* Model
* ViewModel (state related to the view only)
* View

Not sure how we would expose that in python, but the ViewModel layer would
be a perfect place to put the CSS stateful things that are related to the
view only.

Cheers,

Brian

On Mon, Aug 10, 2015 at 10:12 AM, Sylvain Corlay <notifications@github.com>
wrote:

> base widget model:
>
> You mean the DOM widget? It's not the base widget model.
>
> That's right.
>
> Regardless of how we come out with this discussion, I think border-radius
> is going a bit far and should be removed.
>
> Maybe we should revisit the removal of get/set_css and exposure of _css.
> _css feels kind of slimy, for lack of better words, when you actually use
> it. Instead of re-adding them though, maybe we can come up with a better
> stateful mechanism. I remember the issue was selectors.
>
> It sounds like a good idea. Maybe simply adding convenience functions to
> edit _css or use an eventful dict.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/issues/121#issuecomment-129529270>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
I understand why a view model is useful in cases when you need to distinguish state, but I'm not seeing why distinguishing state would be useful here.  The state that our widgets have currently represents the view.  If it didn't, most of the widgets would only be a model with a single `value` trait.

Another layer of inheritance may be useful.  Is that what you were getting at?

**Comment by jdfreder** [comment]
Because this would be backwards incompatible, I'm marking this as 5.0. 

Also, bumping the discussion, here's a possible path forward:

- Add a class called `StyledWidget`  
- Move all aforementioned traits to `StyledWidget`, including `_css`  
- All of our precanned widgets would inherit from `StyledWidget`  
- Remove border radius from `StyledWidget`  
- Reintroduce helper methods for _css in `StyledWidget`.  Even though they are a leaky abstraction, they help more than they hurt.

**Comment by ellisonbg** [comment]
Good thoughts!

On Tue, Oct 13, 2015 at 12:16 PM, Jonathan Frederic <
notifications@github.com> wrote:

> Because this would be backwards incompatible, I'm marking this as 5.0.
>
> Also, bumping the discussion, here's a possible path forward:
>
>    - Add a class called StyledWidget
>    - Move all aforementioned traits to StyledWidget, including _css
>    - All of our precanned widgets would inherit from StyledWidget
>    - Remove border radius from StyledWidget
>    - Reintroduce helper methods for _css in StyledWidget. Even though
>    they are a leaky abstraction, they help more than they hurt.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/issues/121#issuecomment-147765524>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ibigpapa** [comment]
I can't get the width / height attributes to make a difference.

**Comment by SylvainCorlay** [comment]
@ibigpapa which version are you using.

**Comment by ibigpapa** [comment]
4.1.1

**Comment by ibigpapa** [comment]
c44c3588b26bc569a5be767f3d5e91264af8cac2  looks like the 4.2.0 "dev" fixed it
will try that and see

**Comment by SylvainCorlay** [comment]
Yes this all was fixed in the dev version. Hopefully we will release ipywidgets 5.0 soon.
