### ISSUE TITLE
JupyterLab: HTML needs double click to select

### ISSUE THREAD

**Issue by AbdealiJK** [ipython/ipywidgets#1210]
I'm trying the current jupyterlab_widgets on pypi - 0.6.15 and the compatible jupyter - 0.16.2 and am seeing this:

Try running:
```
from ipywidgets import *
HTML("<input></input> <br /> <input></input>")
```

 - Click on the first input tag - it comes into focus immediately
 - Click on the second input tag - it defocuses form the first but does not focus on the second tag
 - Click on the second input tag again -  it focuses on the second input tag

Seems like the clicks first defocus from the input tag and focuses on the cell. And then the second input tag gets focused.

Note: This works fine in Jupyter Notebook - so, it's a feature parity issue

**Comment by blink1073** [comment]
Moved to https://github.com/jupyterlab/jupyterlab/issues/1948.
