### ISSUE TITLE
remove method not called for children views

### ISSUE THREAD

**Issue by maartenbreddels** [ipython/ipywidgets#1214]
When a VBox is removed (say you click the close button), it will not invoke `.remove()` on it's children. This makes it impossible to do cleanups (or as I need, a correct view count).

**Comment by jasongrout** [comment]
IIRC, the phosphor widget should be disposing the children, which should call the children's remove. Perhaps the close button is not appropriately removing the widget to begin with.

**Comment by maartenbreddels** [comment]
I thought that by calling `children_views.remove()` it would be solved, but also that didn't seem to work, so I'm lost here.

**Comment by jasongrout** [comment]
Yes, it's a bit tricky now. When the element is removed from the DOM, the view's remove method is called from phosphor. You can see this if you do:

```python
from ipywidgets import *
x = VBox([IntSlider()])
y=HBox([x])
y
```
set a breakpoint in the DOMWidgetView's remove method, and then do:
```python
y.children = []
```
and you'll see that the `x` VBox view's remove is called, and the child IntSlider's remove method is called.

In fact, it seems that clicking the 'x' next to the widget also triggers the DOMWidgetView's remove method for each child widget.

Can you tell me how you see that the remove method is not getting called for children? What commit are you using? I'm (essentially) using efefafdb2d2bfbdaaffd04890ae84461796e46db.

**Comment by maartenbreddels** [comment]
Ok, I'll try that, but appearently it's not in ipywidgets then, could be in bqplot, or something I'm doing wrong, I'll close it for the moment then.
