### ISSUE TITLE
Why are we using the global widget registry

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#122]
We could as well use the `_view_module` and `_view_name` as we recommend for custom widgets.

**Comment by jdfreder** [comment]
One nice thing about using the registry is that the users can override the views without writing any Python - i.e.`widgetmanager.WidgetManager.register_widget_view('ButtonView', myCoolCustomButtonView);`

**Comment by SylvainCorlay** [comment]
That said, you can also override the view and view module on definition of the widget instance.

`widget = Button(_view_module='''nbextensions/foobar/baz')`

Although it is an instance by instance thing.

**Comment by SylvainCorlay** [comment]
We are not using the global registry anymore. Closing.
