### ISSUE TITLE
Persistence issues with widgets holding other widgets

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#133]
#### Re-instantiating all valid widget models
Let' s say that we have a container widget with id `id1` holding two widgets of id `id2` and `id3`. (For example, `HBox([Button(), Button()]))`. We save the notebook and the states of the three widgets are saved to the local storage.

``` Python
id1
 |
 +--- id2
 |
 +--- id3
```

Then we change the content initial container wigdet, so that we are in the situation

``` Python
id1
 |
 +--- id4
 |
 +--- id5
```

then, without saving the notebook, we reload the page.

Since `id1` is a valid comm, we request it' s state, but when de-serializing its state, we fail at instantiating the widget models `id4` , `id5` because they were not recreated. (more precisely, get_model will return undefined.) Errors are displayed in the console.

This shows that we should re-instantiate all the valid widget models regardless of whether they were in the local storage. 

#### External state request

The issue is that we need to retrieve the `_model_name` and the `_model_module`, which are part of the state to instantiate the model and make a state request.

Hence, the state request should probably be external to the widget, and sent via the bare comm object.

**Comment by jdfreder** [comment]
Hmmm, I thought this would have been fixed by your comm alive work, but it seems like it's still an issue.  I'll try to fix it...

**Comment by SylvainCorlay** [comment]
What do you think of this?

1. request the valid comms for the `ipython.widget` target
2. request the model state for these comms (but we don't know yet how to de-serialize those yet, since no js-side model is.)
3. from the `model_name`, `model_module` we got in step 2, instantiate the widget models with the latest state from the backend.
4. look into the local storage for other models that were not in that list to create comm-less (broken-link) widgets.

**Comment by jdfreder** [comment]
> This shows that we should re-instantiate all the valid widget models regardless of whether they were in the local storage.

The strange thing is, it looks like the code is already attempting to do this. 

> What do you think of this?
> 
> request the valid comms for the ipython.widget target
> request the model state for these comms (but we don't know yet how to de-serialize those yet, since no js-side model is.)
> from the model_name, model_module we got in step 2, instantiate the widget models with the latest state from the backend.
> look into the local storage for other models that were not in that list to create comm-less (broken-link) widgets.

I think this is a really good idea.  I'll take a go at implementing it.

**Comment by SylvainCorlay** [comment]
> > This shows that we should re-instantiate all the valid widget models regardless of whether they were in the local storage.

> The strange thing is, it looks like the code is already attempting to do this. 

I think that the `model_name` are only fetched from the local storage. The list of valid comm is only used to check whether a comm object should be created for it.

> > What do you think of this?
> > 
> > request the valid comms for the ipython.widget target
> > request the model state for these comms (but we don't know yet how to de-serialize those yet, since no js-side model is.)
> > from the model_name, model_module we got in step 2, instantiate the widget models with the latest state from the backend.
> > look into the local storage for other models that were not in that list to create comm-less (broken-link) widgets.

> I think this is a really good idea.  I'll take a go at implementing it.

**Comment by jdfreder** [comment]
AH yes, sorry I misread that line of yours that I quoted.  Yes- we should reinstantiate all models regardless if persisted.
