### ISSUE TITLE
Output widget appears to size itself smaller than its contents

### ISSUE THREAD

**Issue by kh90909** [ipython/ipywidgets#135]
This seems to be a regression (or new feature!) as it does not happen with 3.0.0 (Anaconda on Windows with 3.0.0 ipython, ipython-notebook packages).

This can be highlighted by displaying an inline matplotlib plot, rendered by default with the png backend:
```python
%matplotlib inline
import matplotlib.pyplot as plt

from IPython.html import widgets
from IPython.display import display

out=widgets.Output()
display(out)

with out:
    plt.plot([0,1],[0,1])
    display(plt.gcf())
    
plt.plot([0,1],[0,1]);
```
In my tests with Anaconda on Windows and the 3.2.1 IPython packages, the plot in the output widget gets scaled down:
![image](https://cloud.githubusercontent.com/assets/7075951/9092296/4cd4a2f6-3b73-11e5-9fe8-27fed9e7be15.png)

This doesn't happen with 3.0.0:
![image](https://cloud.githubusercontent.com/assets/7075951/9092271/1551050e-3b73-11e5-9a00-8c7f1c41fdf4.png)

A variation can be seen by switching to the svg backend with:
```python
%config InlineBackend.figure_formats=set(['svg'])
```
In this case, the plot is not resized, but scrollbars appear on the output widget:
![image](https://cloud.githubusercontent.com/assets/7075951/9092309/66043656-3b73-11e5-8217-93845b30276f.png)

**Comment by jdfreder** [comment]
> (or new feature!)

I choose this one. :wink:

**Comment by kh90909** [comment]
Tracked this down the the jupyter commit jupyter/notebook@dd41d9f, which changes the css for `div.output_subarea` as follows:
```
-    max-width: 100%;
+    max-width: calc(~"100% - 14ex");
```

Reverting `max-width` to 100% resolves this issue. Don't know if it would have unintended consequences elsewhere.

**Comment by minrk** [comment]
@kh90909 unfortunately, Firefox sizes it wrong when it's 100% and *not* calculated to take the prompt into account. Or at least that was true at the time.

**Comment by kh90909** [comment]
It looks okay with `max-width` set to 100% for my test case in Firefox 40.0 on Windows, but maybe this issue only crops up for specific outputs?

![image](https://cloud.githubusercontent.com/assets/7075951/9292027/b10d3988-43af-11e5-85ed-df2edf695201.png)

**Comment by minrk** [comment]
max-width is only relevant when it's clipping - make the window narrow until it starts shrinking the image to test.

**Comment by kh90909** [comment]
Ah, I see. Is this the symptom (in the red box)?

![image](https://cloud.githubusercontent.com/assets/7075951/9292081/67ab0006-43b2-11e5-8083-298b8f3500fa.png)

I see the same behavior in Chrome 43 on Windows.

**Comment by minrk** [comment]
Ah, maybe it's not Firefox specific, then. But it still means that the width needs the calc value.

**Comment by kh90909** [comment]
Delving further with Firefox's Inspector, it looks like the issue may be that content within an output widget is displayed inside a widget-subarea div, so the 100% max-width is not referencing the full width of the column, but something else. Take a look at the difference between the output_wrapper divs in both cases below.

Plot inside output widget:
![image](https://cloud.githubusercontent.com/assets/7075951/9292119/bbf6fcb2-43b4-11e5-8759-60ad74769ba1.png)

Regular plot:
![image](https://cloud.githubusercontent.com/assets/7075951/9292120/ce4d2cb0-43b4-11e5-8d7a-4346dcbf5742.png)

**Comment by jdfreder** [comment]
I've seen a change in the layout behavior of the ipywidgets widget subarea recently, and I'm not quite sure what commit caused it, but it seems to be closing a lot of layout issues.  I just checked this issue and I'm not seeing the problem with the subarea not filling the width of the page on either Chrome or Firefox:

Code:

```python
from ipywidgets import *
from IPython.display import display
display(Box(background_color='red', height='10px', width='100%'))
```

Ping back if this is still an issue (in master) and I'll reopen the issue.  Thanks!

**Comment by yoavram** [comment]
For lack of documentation right now, I want to add here that adding `width='80%'` etc. works for other widgets, too - for example, a `DropDown` widget.
