### ISSUE TITLE
Plot showing more often than it should

### ISSUE THREAD

**Issue by jdfreder** [ipython/ipywidgets#136]
@ahhsia originally reported:

---

I  get an every increasing set of plots from a single interact cell in the notebook when running a SelectWidget and changing the plot function.

Originally, I was using subplot instead of just plot because I was attempting to get 2 different types graphs to change simultaneously with the interactive widgets. So, while the test case below doesn't really need subplot, it is the simplest testcase I have that showcases the odd behavior.

If I run this:

```python
w1= widgets.SelectWidget(values=[4,5,6], value=4)
```

```python
@interact(a = w1)
def viewer(a):
    fig,ax=plt.subplots()
    #ax.plot(range(a))
    ax.plot(range(a+1))
````

And then go back and change the ax.plot command,(e.g. reverse the commenting on the ax.plot commands shown here), rerun the cell and select a new value, I will end up with 2 figures.
The more times I change the plot command, the longer the chain of figures I will end up with.

![ghost](https://cloud.githubusercontent.com/assets/2042495/4534573/4df428e2-4da7-11e4-9c75-81a133339d52.png)

**Comment by jdfreder** [comment]
My guess is that this is also related to #5006 , and some matplotlib post or pre exec hook isn't getting ran....

**Comment by SylvainCorlay** [comment]
This seems to be solved in master.

Updated version of the code:

```python
import ipywidgets as widgets
from matplotlib import pyplot as plt
from IPython.display import display

w1= widgets.Select(options=[4,5,6], value=4)

@widgets.interact(a = w1)
def viewer(a):
    fig,ax=plt.subplots()
    #ax.plot(range(a))
    ax.plot(range(a+1))
    display(fig)
```
