### ISSUE TITLE
upgraded to ipywidgets 4.0, now only widget for first argument is displayed

### ISSUE THREAD

**Issue by denfromufa** [ipython/ipywidgets#138]
https://github.com/ipython/ipython/issues/8698

**Comment by jasongrout** [comment]
I'm not sure how to reproduce this.  I've attached a screenshot for what happens for me, on ipywidgets 4.0.2
![capture](https://cloud.githubusercontent.com/assets/192614/9177809/9a9864d6-3f61-11e5-8b16-8fad3d68a1e2.PNG)

**Comment by jdfreder** [comment]
@denfromufa would you mind uploading a notebook (gist may be easiest) that reproduces this?

**Comment by denfromufa** [comment]
I check with latest again and see no problem! It looks like the problem appeared when I did:

pip install ipywidgets

which upgrade to ipython/jupyter 4.0 beta. Now I upgraded using:

pip install jupyter

**Comment by jdfreder** [comment]
Thanks!
