### ISSUE TITLE
HTML outputs suppressed by widgets

### ISSUE THREAD

**Issue by blink1073** [ipython/ipywidgets#141]
It looks like `display(*widgets)` suppresses any other html outputs:

```python
from IPython.html.widgets import Button
from IPython.display import HTML, display
b = Button(description='Say Hello')
def cb(value):
    HTML('<h1>hello</h1>')
    print('hello')
    
b.on_click(cb)
display(b)
```

Clicking the button does not produce the HTML output:

<img width="457" alt="screen shot 2015-08-10 at 6 06 43 pm" src="https://cloud.githubusercontent.com/assets/2096628/9186463/9fe2dd94-3f8a-11e5-9496-861ef7a7d60a.png">

**Comment by jdfreder** [comment]
Hey @blink1073 , you need to `display(HTML('<h1>hello</h1>'))`.  HTML alone does not display.

**Comment by blink1073** [comment]
Awesome!  I love when the mistake is between my ears.  Thanks @jdfreder.
