### ISSUE TITLE
Widget-subarea does not enlarge if widget does not have a fixed weight

### ISSUE THREAD

**Issue by jgosmann** [ipython/ipywidgets#143]
With IPython 3 the `widget-subarea` div would enlarge to use up the whole available width. With IPython 4 this doesn't happen and the width is super narrow. Only by setting a fixed width on the widget itself it will be displayed correctly.

IPython used to have the CSS property `flex: 2 1 0%;` on `widget-subarea` which is gone now. If I re-add temporarily in the browser's developer tools, the sizing works again as expected.

**Comment by SylvainCorlay** [comment]
Ouch this had been solved has apparently reappeared. From what I recall, css minifying might be breaking things.

**Comment by jdfreder** [comment]
I checked, and this is no longer an issue in ipywidgets master.  @SylvainCorlay do you know what commit fixed this?  Seems like because of it, I've been able to close 3 issues today! :dancer:

**Comment by SylvainCorlay** [comment]
I don't know. I currently have this issue in my local install but not in the bqplot binder.

**Comment by jdfreder** [comment]
Just checked out master and rebuilt my CSS, it's definitely not a problem:

![screenshot from 2015-10-14 12 27 28](https://cloud.githubusercontent.com/assets/3292874/10495126/1058702c-726f-11e5-8649-26defcdd2010.png)

**Comment by jdfreder** [comment]
test code:

```python
from ipywidgets import *
from IPython.display import display
display(Box(background_color='red', height='10px', width='100%'))
```

**Comment by SylvainCorlay** [comment]
The red box does not show for me.

**Comment by jdfreder** [comment]
Master and rebuilt CSS?

**Comment by jdfreder** [comment]
Ah - are you running notebook master too?  I'll try updating notebook master and rebuilding the notebook's css too

**Comment by jdfreder** [comment]
@SylvainCorlay I updated all of my remotes and checked out the latest master of everything.  Here are my commits:

```
jon@jon-OEM:~/jupyter/notebook$ pur git rev-parse --short HEAD
meow!🐱
0: /home/jon/ipython/ipykernel/ hub rev-parse,--short,HEAD
1: /home/jon/ipython/ipython/ hub rev-parse,--short,HEAD
2: /home/jon/ipython/ipywidgets/ hub rev-parse,--short,HEAD
3: /home/jon/ipython/traitlets/ hub rev-parse,--short,HEAD
4: /home/jon/jupyter/jupyter_client/ hub rev-parse,--short,HEAD
5: /home/jon/jupyter/jupyter_console/ hub rev-parse,--short,HEAD
6: /home/jon/jupyter/jupyter_core/ hub rev-parse,--short,HEAD
7: /home/jon/jupyter/jupyter-js-input-area/ hub rev-parse,--short,HEAD
8: /home/jon/jupyter/nbconvert/ hub rev-parse,--short,HEAD
9: /home/jon/jupyter/nbformat/ hub rev-parse,--short,HEAD
10: /home/jon/jupyter/notebook/ hub rev-parse,--short,HEAD
11: /home/jon/jupyter/qtconsole/ hub rev-parse,--short,HEAD
  0  /home/jon/ipython/ipykernel/
     34466bc
     
  1  /home/jon/ipython/ipython/
     e530247
     
  2  /home/jon/ipython/ipywidgets/
     6138032
     
  3  /home/jon/ipython/traitlets/
     b70b9cf
     
  4  /home/jon/jupyter/jupyter_client/
     d82793d
     
  5  /home/jon/jupyter/jupyter_console/
     83ad838
     
  6  /home/jon/jupyter/jupyter_core/
     dd1bdd0
     
  7  /home/jon/jupyter/jupyter-js-input-area/
     ed65007
     
  9  /home/jon/jupyter/nbformat/
     ff5965a
     
  8  /home/jon/jupyter/nbconvert/
     b3a179f
     
 11  /home/jon/jupyter/qtconsole/
     d8ad4d1
     
 10  /home/jon/jupyter/notebook/
     d375942  
```

I've also rebuilt the CSS in `jupyter/notebook` and `ipython\ipywidgets`

Screenshot of an incognito tab on Chrome Version 45.0.2454.101 (64-bit):

![screenshot from 2015-10-14 12 41 57](https://cloud.githubusercontent.com/assets/3292874/10495752/46d91fb8-7272-11e5-93b6-3d51224fbaec.png)

**Comment by SylvainCorlay** [comment]
The problem seems to be coming from my css minifier. If I replace the minified css with the original one, everything works as expected.

**Comment by jdfreder** [comment]
There is a minifier specified with the widget's package.json, are you using that one?

**Comment by jdfreder** [comment]
ooh, just looked.  Looks like it's not locked to a specific minor...  I'll open a PR to fix that.

**Comment by SylvainCorlay** [comment]
@jdfreder thanks!
