### ISSUE TITLE
Interact with simple plot function now flickers on update

### ISSUE THREAD

**Issue by flutefreak7** [ipython/ipywidgets#145]
The commit 68f771f on `interact` now displays the functions return value, which has the side-effect of causing "flickering" when interacting with a simple matplotlib plot.

Here's an example that used to be a smooth interactive plot with sliders:

    %matplotlib inline
    import numpy as np
    import matplotlib.pyplot as plt
    from ipywidgets import interact, HTML, FloatSlider
    from IPython.display import clear_output, display

    def make_plot(magnitude=5.0, phase=0.0):
        x = np.arange(0, 10, 0.1)
        y = magnitude*np.sin(x+phase)
        plt.plot(x, y)
        plt.ylim(-10, 10)
        
    interact(make_plot, magnitude=(0, 10, 0.1), phase=(0, 4*np.pi, 0.1))

Unfortunately, because make_plot returns `None`, None is printed, which somehow breaks the smooth updating that interact previously exhibited.  Now the plot is erased, the rest of the web interface jumps up to fill the gap, then the plot is replaced... repeatedly and rapidly while the slider is being interacted with.  This drastically reduces the interactivity and aesthetic appeal of simple tools like this.

Here is an example without interact which currently runs fine and demonstrates the smooth behavior that interact previously had:

    %matplotlib inline
    import numpy as np
    import matplotlib.pyplot as plt
    from ipywidgets import interact, HTML, FloatSlider
    from IPython.display import clear_output, display
    
    slider1 = FloatSlider(description='magnitude', min=0, max=10, step=0.1)
    slider2 = FloatSlider(description='phase', min=0, max=4*np.pi, step=0.1)
    
    def update_plot():
        magnitude = slider1.value
        phase = slider2.value
        x = np.arange(0, 10, 0.1)
        y = magnitude*np.sin(x+phase)
        fig = plt.figure()
        plt.plot(x, y)
        plt.ylim(-10, 10)
        
        clear_output(True)
        
    slider1.on_trait_change(update_plot, 'value')
    slider2.on_trait_change(update_plot, 'value')

    display(slider1, slider2)
    update_plot()

Interestingly, adding `display(None)` to the end of update_plot() brings back the flickering from the interact example, demonstrating that the display of text is causing the flicker.  Hmmm... apparently displaying an empty HTML object removes the flicker... I guess that would be the workaround.  If I add `return HTML()` to the first example's make_plot() function, it updates smoothly now.

I don't know if there is a better solution to this.  I wish text and figures could both be updated smoothly without the "flickering effect," but until that is implemented, I'd at least like the option to turn off display of function output for interact or perhaps not display output when output is `None` so that the smooth behavior isn't disrupted simply to display `None`.  Documenting the workaround of returning `HTML()` in an example might be useful in lieu of other solutions (I haven't searched thoroughly to see if this has been done/documented before...).

edit: fixed 2nd example - had left out the slider definitions

**Comment by flutefreak7** [comment]
Hmm, after looking at the Lorenz example I see that adding `plt.show()` to the function allows the figure to appear above the return value, which preserves the smooth figure updates (the return value still flickers, but that's expected I guess since any secondary item, like a second figure, results in flickery updates).

**Comment by jasongrout** [comment]
Thanks for catching this.  You're right, this is pretty unusable right now in the case you pointed out above.

**Comment by ellisonbg** [comment]
Could you submit a pr to the ipython kernel to fix this?

**Comment by flutefreak7** [comment]
I've never submitted a PR or even used Git in any real fashion - I'm an Aerospace Engineer who is a  user/consumer of these fantastic tools.  Sorry to say that being an early adopter and bug reporter is the extent of my helpfulness.

**Comment by DavidPowell** [comment]
@ellisonbg Why a PR to the IPython kernel and not ipywidgets? Shouldn't it just be a matter of adding `if container.result is not None:` to `interact.py`?

It was easy enough to implement this myself. However, I cannot easily test it, because installing ipywidgets from source fails under windows at the point of rebuilding the js and css files.

**Comment by leo-smi** [comment]
Thank you so much, this was the only worked in google colab
