### ISSUE TITLE
Upload docs

### ISSUE THREAD

**Issue by flying-sheep** [ipython/ipywidgets#146]
just like the [qtconsole](http://jupyter.org/qtconsole/stable/), ipywidgets should have sphinx docs hosted.

**Comment by jdfreder** [comment]
+1 , right now we only have notebook docs - but that shouldn't be a problem.  We should be able to use the same nbconvert approach we did for the jupyter/notebook example docs.

**Comment by willingc** [comment]
Closing this issue.

Docs using sphinx are hosted here: http://ipywidgets.readthedocs.io/en/latest/index.html
