### ISSUE TITLE
Interact in notebook hangs if ipywidgets is not installed in python which runs the notebook

### ISSUE THREAD

**Issue by jorisvandenbossche** [ipython/ipywidgets#148]
When you have the following situation:

- using a non-default kernel (eg a conda env) in jupyter notebook
- you installed `ipywidgets` in this environment (but not in the python which runs jupyter)

then you can import `ipywidgets` (since it is installed in that kernel), but when using `interact` the notebook just hangs (kernel is busy but does not do anything, restarting the kernel does not solve it).

In the webconsole of firefox, I can see that there is a message like 'ipywidgets is not installed'. When I installed `ipywidgets` also in the python which runs jupyter notebook, the problem is solved (and you get a message like "Loaded extension: widgets/notebook/js/extension. loaded widgets" in the webconsole)

The problem is that it seems that things should work (as you can import ipywidgets), but when using interact it just hangs. And it is not really obvious what the reason is. 
Would it be possible to detect this and eg raise a warning?

**Comment by jasongrout** [comment]
Here's a think we could check: if a comm error indicates that the widget comm target is not installed, then print out an error to the user saying that the widgets are not installed and/or enabled for the notebook.

**Comment by rgbkrk** [comment]
That idea sounds good @jasongrout

**Comment by jakevdp** [comment]
I ran into this today. Took a while to find this issue and figure out the problem.

**Comment by SylvainCorlay** [comment]
A first step to avoid crashing the notebook would be to have [`load_class`](https://github.com/jupyter/notebook/blob/2f0f3987b1b79fbc323d7555b16a9e1bf4566155/notebook/static/base/js/utils.js#L701) function handl errors and get these errors to be displayed in stderr.

**Comment by jdfreder** [comment]
This will be solved once we agree on how to server kernel static assets to the front-end.

**Comment by jdfreder** [comment]
I went ahead and implemented the solution @jasongrout suggested in #303
