### ISSUE TITLE
Test framework improvements or total redesign.

### ISSUE THREAD

**Issue by jdfreder** [ipython/ipywidgets#15]
The tests should
- always show the notebook Python output / error on failure
- javascript console output / error on failure
- test error on failure
- should use promises if written in Javascript
- should be clearer about the three contexts (kernel, browser, and tests)
- if written in javascript, ES6 template strings or something better should be used for embedding python
- should have an easy way to expose/export the test notebook, so the dev can interact with the tests to see why they are failing
- should have nice mechanisms for debugging

**Comment by minrk** [comment]
All of those sounds like good things.
