### ISSUE TITLE
__version__ attribute not accessible

### ISSUE THREAD

**Issue by zivy** [ipython/ipywidgets#154]
The __version__ attribute doesn't appear to be part of the module. The issue happens with the following code:

import ipywidgets
ipywidgets.__version__

Result is:
AttributeError: 'module' object has no attribute '__version__'

Anaconda environment:
ipython                   4.0.0                    py27_0  
ipywidgets                4.0.2                    py27_0

I believe the __version__ attribute should be there and that this is some sort of bug.

**Comment by egentry** [comment]
To add a bit more clarity, `ipywidgets.__version__` was added by #147, but `ipywidgets.version` does not exist. (And if you don't escape `__version__` markdown makes it look like __version__)

**Comment by minrk** [comment]
So this is closed by #147?

**Comment by zivy** [comment]
This should be closed by  #147 . 

What confused me was that the version in _version.py on master is still 4.0.2. This is the version I have installed and it doesn't include the fix. I am not sure about the versioning conventions in ipywidgets, but once a version is released the version number on master should probably be modified?
