### ISSUE TITLE
reconnect to widget

### ISSUE THREAD

**Issue by flying-sheep** [ipython/ipywidgets#155]
currently, when starting a long-running process i’d like to close my laptop lid, open it later, and see my progressbar jump to its current position.

the notebook itself handles reconnection well, but the widgets simply vanish.

**Comment by jdfreder** [comment]
Hmm I thought the persistence was supposed to address this.  It's possible that something is broken.  Marking this as a bug.

**Comment by jdfreder** [comment]
@flying-sheep when #174 is merged your wish will be granted.

However!  The steps for this to work are actually:
1. Save the notebook
2. Close the laptop lid
3. Open the laptop lid
4. Refresh page (DON'T CLEAR YOUR CACHE, THE WIDGETS ARE PERSISTED TO localStorage)

**Comment by flying-sheep** [comment]
oh nice! :bow:
