### ISSUE TITLE
widget result appears after plot

### ISSUE THREAD

**Issue by guidov** [ipython/ipywidgets#158]
The result returned as a widget attribute (widget.result) shows up after the plot, so when the sliders are adjusted the text output makes for messy animation. How can this np.array text be removed?
![widget_result](https://cloud.githubusercontent.com/assets/2983984/9819242/d9ecdc0c-587a-11e5-9655-db51058f3226.png)

This happens in the Lorenz example notebook

**Comment by jdfreder** [comment]
If the function that interact is called on returns a value, that value will be displayed in addition to any other things that are explicitly displayed.  Try removing the `return` statement from the function.

**Comment by guidov** [comment]
Thanks
