### ISSUE TITLE
option to transmit slider value on release, rather than on drag

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipywidgets#160]
The code at https://github.com/ipython/ipywidgets/blob/master/ipywidgets/static/widgets/js/widget_int.js#L176 executes the slider change handler anytime the slider is dragged, while it is being dragged.  Often a calculation takes so much time that it's better to only update when the slider is released.  It would be great to have an option to the slider so that it updates only on mouse release, rather than mouse drag.

Thanks to @suhr for bringing this up on gitter

**Comment by ellisonbg** [comment]
+1

On Mon, Sep 14, 2015 at 8:46 AM, Jason Grout <notifications@github.com>
wrote:

> The code at
> https://github.com/ipython/ipywidgets/blob/master/ipywidgets/static/widgets/js/widget_int.js#L176
> executes the slider change handler anytime the slider is dragged, while it
> is being dragged. Often a calculation takes so much time that it's better
> to only update when the slider is released. It would be great to have an
> option to the slider so that it updates only on mouse release, rather than
> mouse drag.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/issues/160>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
I think this is a good idea.  However, I'd like to note, our original response to this, because someone asked for it 1/2 a year ago or so, was to subclass the slider JS.

**Comment by rsignell-usgs** [comment]
Oh, yes please!   The function we are controlling with our slider widget actually extracts a specific time step of model data from a web service, which we really don't want to do until the slider is released.
