### ISSUE TITLE
displaying results of interactive widgets

### ISSUE THREAD

**Issue by martin-hunt** [ipython/ipywidgets#162]
Between 3.2 and 4.0, most of my interactive plotting notebooks broke due to a change where the fuinction return value is automatically displayed. A good example of what this looks like is in ipywidgets/examples/Lorenz Differential Equations.ipynb, the interactive plot in cell 6 has a large array of numbers instead of just a nice plot.

The change that caused this is in interaction.py, function interactive(), 
       try:
            container.result = f(**container.kwargs)
            display(container.result)

Removing the display() restores the previous behaviour.

**Comment by martin-hunt** [comment]
I could not find any discussion of this, but it appears tha tthis is the designed new behaviour.  The examples should be updated to reflect this.

**Comment by ellisonbg** [comment]
It is the new desired behavior - but there is one problem with how it works
in 4.0 that we have fixed in master of ipywidgets. If the return value of
the function of None 4.0 will display that, but it shouldn't (and won't in
4.1).



On Mon, Sep 21, 2015 at 6:02 AM, martin-hunt <notifications@github.com>
wrote:

> I could not find any discussion of this, but it appears tha tthis is the
> designed new behaviour. The examples should be updated to reflect this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/issues/162#issuecomment-141967816>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
Here's the discussion regarding this new behavior: https://github.com/ipython/ipywidgets/pull/68
Here's the `none` fix that @ellisonbg mentions: https://github.com/ipython/ipywidgets/pull/152

**Comment by ellisonbg** [comment]
@jdfreder - this is sort of a show stopper for the 4.0 release of
ipywidgets. How hard would it be to put out a 4.0.1 release of just the
widgets that has this fix (and any other simple bug fixes)? Remember
ipywidgets releases don't have to follow the notebook now :)

On Mon, Sep 21, 2015 at 8:20 AM, Jonathan Frederic <notifications@github.com
> wrote:

> Here's the discussion regarding this new behavior: #68
> <https://github.com/ipython/ipywidgets/pull/68>
> Here's the none fix that @ellisonbg <https://github.com/ellisonbg>
> mentions: #152 <https://github.com/ipython/ipywidgets/pull/152>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/issues/162#issuecomment-142013220>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
Yeah, that's easy to do.  I'll do that now

**Comment by jdfreder** [comment]
https://pypi.python.org/pypi/ipywidgets/4.0.3

**Comment by SylvainCorlay** [comment]
@jdfreder the four-minutes release! :+1:

**Comment by ellisonbg** [comment]
Awesome! Many thanks!

On Mon, Sep 21, 2015 at 9:12 AM, Sylvain Corlay <notifications@github.com>
wrote:

> @jdfreder <https://github.com/jdfreder> the four-minutes release! [image:
> :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/issues/162#issuecomment-142030709>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
Also, @jdfreder can you ping someone from Continuum to make sure that conda
gets this update as many folks are getting it from there.

On Mon, Sep 21, 2015 at 9:51 AM, Brian Granger <ellisonbg@gmail.com> wrote:

> Awesome! Many thanks!
>
> On Mon, Sep 21, 2015 at 9:12 AM, Sylvain Corlay <notifications@github.com>
> wrote:
>
>> @jdfreder <https://github.com/jdfreder> the four-minutes release! [image:
>> :+1:]
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ipython/ipywidgets/issues/162#issuecomment-142030709>
>> .
>>
>
>
>
> --
> Brian E. Granger
> Associate Professor of Physics and Data Science
> Cal Poly State University, San Luis Obispo
> @ellisonbg on Twitter and GitHub
> bgranger@calpoly.edu and ellisonbg@gmail.com
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
Sure, maybe @asmeurer and @ilanschnell can update the Anaconda package.

**Comment by ilanschnell** [comment]
I just updated `ipywidgets` in Anaconda to version 4.0.3

**Comment by ellisonbg** [comment]
Thanks!

On Mon, Sep 21, 2015 at 12:28 PM, Ilan Schnell <notifications@github.com>
wrote:

> I just updated ipywidgets in Anaconda to version 4.0.3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/issues/162#issuecomment-142085412>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
Thanks!

**Comment by asmeurer** [comment]
@ilanschnell the jupyter metapackage still depends on ipywidgets 4.0.2.

**Comment by jfbercher** [comment]
Isn't it possible/desirable to add a keyword argument to avoid displaying function return? With displaying as default behaviour?

**Comment by ellisonbg** [comment]
Hmm, I don't think that is needed. It led to poorly written code to have
functions that did the display themselves. Because passing the kwarg would
still be an API breakage, I don't think it is worth it.

On Thu, Oct 8, 2015 at 8:14 AM, jfbercher <notifications@github.com> wrote:

> Isn't it possible/desirable to add a keyword argument to avoid displaying
> function return? With displaying as default behaviour?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/issues/162#issuecomment-146519309>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jfbercher** [comment]
I thought to something like 
> f_output = kwargs.pop('f_output', True) 

which doesn't break the API, and then
> if (container.result is not None) and f_output:
>  ....... display(container.result)

Because displaying functions return is sometimes annoying, as noticed earlier in the thread (eg I have functions that selects a file + some parameters and return  huge dataframes). However this is not very important since it can always be done directly.
