### ISSUE TITLE
Same widget does not update all interact.

### ISSUE THREAD

**Issue by jdfreder** [ipython/ipywidgets#163]
Originally entered by @Carreau in https://github.com/ipython/ipython/issues/6534

---

Cf [Stackoverflow](https://stackoverflow.com/questions/25945543/can-values-from-ipython-widgets-propagate-to-other-cells/25992790#25992790) 

having the same widget (say a Checkbox) shared by 2 interact, the value of the checkbox is updated across cell, but the interactived' function not call. Ex:

![capture d ecran 2014-09-24 a 08 30 40](https://cloud.githubusercontent.com/assets/335567/4384325/e7c2de98-43b4-11e4-9264-74546270de13.png)

I clicked on first checkbox, second was highligted, but value did not changed from True to False.

**Comment by jasongrout** [comment]
This seems to work in JupyterLab, but it still does not work in the notebook:

![interactive-notebook](https://cloud.githubusercontent.com/assets/192614/20279733/b49e92ce-aa77-11e6-9c93-e01acc31b7d2.gif)

**Comment by jasongrout** [comment]
This might be related to #316.

**Comment by jasongrout** [comment]
I think fixing #316 solved this. It works in 4.x + https://github.com/jupyter/notebook/pull/2022 to enable the OutputWidget:
![checks](https://cloud.githubusercontent.com/assets/192614/22565236/72fca2f8-e955-11e6-8ec9-13474da9d9c0.gif)
