### ISSUE TITLE
Latex labels are redrawn when interacting with widget

### ISSUE THREAD

**Issue by DavidPowell** [ipython/ipywidgets#166]
I see that ipython/ipython#5937 introduced latex labels for widgets, which would greatly improve the readability of the RISE/live-reveal slides which I am producing.

However, when dragging a slider for example, the widget label also seems to be redrawn at every step, thus triggering a constant series of mathjax renderings, which results in horrible flickering. The following code is sufficient to reproduce the problem:

````
from ipywidgets import *
from IPython.display import display
display(FloatSlider(description='$x^2$'))
````

For my application this makes the latex markup unusable, so it would be great if there was a way that updating of the label could be suppressed when the widget is redrawn.

**Comment by jdfreder** [comment]
Thanks for reporting this!  This may be related to the slider readout changing, but you're right, it shouldn't be happening.  Tagged as a bug-

**Comment by DavidPowell** [comment]
After filing the bug report, I wanted to have a go at diagnosing the problem myself. However, it seems that some major refactoring was done since the PR was merged. I cannot find any reference to Mathjax within the ipywidgets repository.

Does someone know where this functionality is implemented now? Presumably it's somewhere in the jupyter notebook repository.

**Comment by jdfreder** [comment]
hmm, I thought it was in the Jupyter/notebook utils.js class (I may be totally wrong)
