### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by parashardhapola** [ipython/ipywidgets#170]
I get this error while trying to install:

    Command "/usr/bin/python -c "import setuptools, tokenize;    __file__='/home/parashar/ipywidgets/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/parashar/ipywidgets

**Comment by minrk** [comment]
What command are you using to install? Can you provide the *complete* output of the installation?

**Comment by parashardhapola** [comment]
I cloned the repository and then:

    cd ipywidgets

thereafter, as per README I used following command:

    sudo pip install -e .

Following output was obtained:

    The directory '/home/parashar/.cache/pip/http' or its parent directory is not owned by the current     user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    You are using pip version 7.0.3, however version 7.1.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    The directory '/home/parashar/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Obtaining file:///home/parashar/ipywidgets
    Requirement already satisfied (use --upgrade to upgrade): ipython>=4.0.0dev0 in /usr/local/lib/python2.7/dist-packages (from ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): ipykernel in /usr/local/lib/python2.7/dist-packages (from ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): traitlets in /usr/local/lib/python2.7/dist-packages (from ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): notebook in /usr/local/lib/python2.7/dist-packages (from ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): decorator in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0dev0->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): simplegeneric>0.8 in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0dev0->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): pexpect in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0dev0->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): pickleshare in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0dev0->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): jupyter-client in /usr/local/lib/python2.7/dist-packages (from ipykernel->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): ipython-genutils in /usr/local/lib/python2.7/dist-packages (from traitlets->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): tornado>=4 in /usr/local/lib/python2.7/dist-packages (from notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): nbformat in /usr/local/lib/python2.7/dist-packages (from notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): jupyter-core in /usr/local/lib/python2.7/dist-packages (from notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): jinja2 in /usr/local/lib/python2.7/dist-packages (from notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): terminado>=0.3.3 in /usr/local/lib/python2.7/dist-packages (from notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): nbconvert in /usr/local/lib/python2.7/dist-packages (from notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): ptyprocess>=0.5 in /usr/local/lib/python2.7/dist-packages (from pexpect->ipython>=4.0.0dev0->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): path.py in /usr/local/lib/python2.7/dist-packages (from pickleshare->ipython>=4.0.0dev0->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): pyzmq>=13 in /usr/local/lib/python2.7/dist-packages (from jupyter-client->ipykernel->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /usr/local/lib/python2.7/dist-packages (from tornado>=4->notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): certifi in /usr/local/lib/python2.7/dist-packages (from tornado>=4->notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): jsonschema!=2.5.0,>=2.0 in /usr/local/lib/python2.7/dist-packages (from nbformat->notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /usr/local/lib/python2.7/dist-packages (from jinja2->notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): pygments in /usr/local/lib/python2.7/dist-packages (from nbconvert->notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): mistune!=0.6 in /usr/local/lib/python2.7/dist-packages (from nbconvert->notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): functools32 in /usr/local/lib/python2.7/dist-packages (from jsonschema!=2.5.0,>=2.0->nbformat->notebook->ipywidgets==4.0.2)
    Installing collected packages: ipywidgets
      Running setup.py develop for ipywidgets
        Complete output from command /usr/bin/python -c "import setuptools, tokenize; __file__='/home/parashar/ipywidgets/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
        running develop
        Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
        /usr/bin/python -E -c pass
        TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support .pth files
        running jsdeps
        npm unavailable
        rebuilding js and css failed
        missing files: ['/home/parashar/ipywidgets/ipywidgets/static/widgets/css/widgets.min.css', '/home/parashar/ipywidgets/ipywidgets/tests/bin']
        error: [Errno 2] No such file or directory
        
        ----------------------------------------
    Command "/usr/bin/python -c "import setuptools, tokenize; __file__='/home/parashar/ipywidgets/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/parashar/ipywidgets

**Comment by minrk** [comment]
This is the key:

> npm unavailable

You need npm to build ipywidgets from scratch. `apt-get install nodejs nodejs-legacy` on Debian-based systems.

**Comment by parashardhapola** [comment]
after installing npm i retried and got this error:

    Obtaining file:///home/parashar/ipywidgets
    Requirement already satisfied (use --upgrade to upgrade): ipython>=4.0.0dev0 in /usr/local/lib/python2.7/dist-packages (from ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): ipykernel in /usr/local/lib/python2.7/dist-packages (from ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): traitlets in /usr/local/lib/python2.7/dist-packages (from ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): notebook in /usr/local/lib/python2.7/dist-packages (from ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): decorator in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0dev0->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): simplegeneric>0.8 in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0dev0->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): pexpect in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0dev0->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): pickleshare in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0dev0->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): jupyter-client in /usr/local/lib/python2.7/dist-packages (from ipykernel->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): ipython-genutils in /usr/local/lib/python2.7/dist-packages (from traitlets->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): tornado>=4 in /usr/local/lib/python2.7/dist-packages (from notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): nbformat in /usr/local/lib/python2.7/dist-packages (from notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): jupyter-core in /usr/local/lib/python2.7/dist-packages (from notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): jinja2 in /usr/local/lib/python2.7/dist-packages (from notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): terminado>=0.3.3 in /usr/local/lib/python2.7/dist-packages (from notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): nbconvert in /usr/local/lib/python2.7/dist-packages (from notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): ptyprocess>=0.5 in /usr/local/lib/python2.7/dist-packages (from pexpect->ipython>=4.0.0dev0->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): path.py in /usr/local/lib/python2.7/dist-packages (from pickleshare->ipython>=4.0.0dev0->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): pyzmq>=13 in /usr/local/lib/python2.7/dist-packages (from jupyter-client->ipykernel->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /usr/local/lib/python2.7/dist-packages (from tornado>=4->notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): certifi in /usr/local/lib/python2.7/dist-packages (from tornado>=4->notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): jsonschema!=2.5.0,>=2.0 in /usr/local/lib/python2.7/dist-packages (from nbformat->notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /usr/local/lib/python2.7/dist-packages (from jinja2->notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): pygments in /usr/local/lib/python2.7/dist-packages (from nbconvert->notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): mistune!=0.6 in /usr/local/lib/python2.7/dist-packages (from nbconvert->notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): functools32 in /usr/local/lib/python2.7/dist-packages (from jsonschema!=2.5.0,>=2.0->nbformat->notebook->ipywidgets==4.0.2)
    Installing collected packages: ipywidgets
      Running setup.py develop for ipywidgets
        Complete output from command /usr/bin/python -c "import setuptools, tokenize; __file__='/home/parashar/ipywidgets/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
        running develop
        Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
        /usr/bin/python -E -c pass
        TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support .pth files
        running jsdeps
        
        > ipython-widget-deps@4.0.0 build /home/parashar/ipywidgets
        > npm run css && npm run buildtests
        
        
        > ipython-widget-deps@4.0.0 precss /home/parashar/ipywidgets
        > rimraf ./ipywidgets/static/widgets/css/
        
        
        > ipython-widget-deps@4.0.0 css /home/parashar/ipywidgets
        > node build_css.js
        
        > lessc --include-path=./less_include ./ipywidgets/static/widgets/less/widgets.less ./ipywidgets/static/widgets/css/widgets.css
        [31mFileError: '/components/bootstrap/less/variables.less' wasn't found. Tried - /components/bootstrap/less/variables.less,/home/parashar/ipywidgets/ipywidgets/static/widgets/less/components/bootstrap/less/variables.less,/home/parashar/ipywidgets/less_include/components/bootstrap/less/variables.less[39m[31m in [39m/home/parashar/ipywidgets/ipywidgets/static/widgets/less/widgets.less[90m on line 2, column 1:[39m
        [90m1 // minimal imports from bootstrap - only variables and mixins[39m
        2 [7m[31m[1m@[22mimport "/components/bootstrap/less/variables.less";[39m[27m
        [90m3 @import "/components/bootstrap/less/mixins.less";[39m[0m[0m
        
        `lessc --include-path=./less_include ./ipywidgets/static/widgets/less/widgets.less ./ipywidgets/static/widgets/css/widgets.css` failed with status=1
        npm ERR! weird error 1
        npm WARN This failure might be due to the use of legacy binary "node"
        npm WARN For further explanations, please read
        /usr/share/doc/nodejs/README.Debian
        
        npm ERR! not ok code 0
        npm ERR! weird error 1
        npm WARN This failure might be due to the use of legacy binary "node"
        npm WARN For further explanations, please read
        /usr/share/doc/nodejs/README.Debian
        
        npm ERR! not ok code 0
        rebuilding js and css failed
        missing files: ['/home/parashar/ipywidgets/ipywidgets/static/widgets/css/widgets.min.css', '/home/parashar/ipywidgets/ipywidgets/tests/bin']
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/home/parashar/ipywidgets/setup.py", line 294, in <module>
            setup(**setup_args)
          File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
            dist.run_commands()
          File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
            self.run_command(cmd)
          File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
            cmd_obj.run()
          File "/home/parashar/ipywidgets/setup.py", line 159, in run
            raise e
        subprocess.CalledProcessError: Command '['npm', 'run', 'build']' returned non-zero exit status 1
        
        ----------------------------------------

**Comment by minrk** [comment]
`apt-get install nodejs-legacy` (see above)

**Comment by parashardhapola** [comment]
already installed:

    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    nodejs-legacy is already the newest version.
    0 upgraded, 0 newly installed, 0 to remove and 197 not upgraded.

**Comment by minrk** [comment]
@parashardhapola what do you get from `which -a node`? And what information do you see in the file it tells you to read (/usr/share/doc/nodejs/README.Debian)?

**Comment by parashardhapola** [comment]
```which -a node``` returns 

    /usr/bin/node

the content of this file ```/usr/share/doc/nodejs/README.Debian``` is :

    nodejs for Debian
    =================
    
    packaged modules
    ----------------
    
    The global search path for modules is
    /usr/lib/nodejs
    
    Future packages of node modules will use that directory,
    so it should be used wisely.
    
    
    user modules
    ------------
    
    Node looks for modules in ./node_modules directory first;
    please read node#modules documentation carefully for more information.
    
    Node does not look for modules in /usr/local/lib/node_modules,
    where npm put them.
    Please read npm-link(1) of npm package, to understand how to properly
    use npm-installed modules in a project.
    
    Note that require.paths is not supported in future node versions.
    See also node(1) for more information about NODE_PATH.
    
    
    nodejs command
    --------------
    
    The upstream name for the Node.js interpreter command is "node".
    In Debian the interpreter command has been changed to "nodejs".
    
    This was done to prevent a namespace collision: other commands use
    the same name in their upstreams, such as ax25-node from the "node"
    package.
    
    Scripts calling Node.js as a shell command must be changed to instead
    use the "nodejs" command.
    
#### My desktop info: ```lsb_release -a```

    No LSB modules are available.
    Distributor ID:	LinuxMint
    Description:	Linux Mint 17.1 Rebecca
    Release:	17.1
    Codename:	rebecca

**Comment by minrk** [comment]
What do you get from `node -v`? The `nodejs-legacy` package is meant to fix the `node` executable, but maybe this doesn't work on Mint for some reason. It works on Debian and Ubuntu, at least.

**Comment by parashardhapola** [comment]
```node -v``` gives: ```v0.10.25```

**Comment by minrk** [comment]
And `npm -v`?

**Comment by parashardhapola** [comment]
```npm -v``` gives  ```1.3.10```

**Comment by parashardhapola** [comment]
I upgraded node to version 4.2 by compiling from source and doing a global install.
I tried installing ipywidgets but got following error:

    Obtaining file:///home/parashar/ipywidgets
    Requirement already satisfied (use --upgrade to upgrade): ipython>=4.0.0dev0 in /usr/local/lib/python2.7/dist-packages (from ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): ipykernel in /usr/local/lib/python2.7/dist-packages (from ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): traitlets in /usr/local/lib/python2.7/dist-packages (from ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): notebook in /usr/local/lib/python2.7/dist-packages (from ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): decorator in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0dev0->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): simplegeneric>0.8 in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0dev0->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): pexpect in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0dev0->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): pickleshare in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0dev0->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): jupyter-client in /usr/local/lib/python2.7/dist-packages (from ipykernel->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): ipython-genutils in /usr/local/lib/python2.7/dist-packages (from traitlets->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): tornado>=4 in /usr/local/lib/python2.7/dist-packages (from notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): nbformat in /usr/local/lib/python2.7/dist-packages (from notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): jupyter-core in /usr/local/lib/python2.7/dist-packages (from notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): jinja2 in /usr/local/lib/python2.7/dist-packages (from notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): terminado>=0.3.3 in /usr/local/lib/python2.7/dist-packages (from notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): nbconvert in /usr/local/lib/python2.7/dist-packages (from notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): ptyprocess>=0.5 in /usr/local/lib/python2.7/dist-packages (from pexpect->ipython>=4.0.0dev0->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): path.py in /usr/local/lib/python2.7/dist-packages (from pickleshare->ipython>=4.0.0dev0->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): pyzmq>=13 in /usr/local/lib/python2.7/dist-packages (from jupyter-client->ipykernel->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /usr/local/lib/python2.7/dist-packages (from tornado>=4->notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): certifi in /usr/local/lib/python2.7/dist-packages (from tornado>=4->notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): jsonschema!=2.5.0,>=2.0 in /usr/local/lib/python2.7/dist-packages (from nbformat->notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /usr/local/lib/python2.7/dist-packages (from jinja2->notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): pygments in /usr/local/lib/python2.7/dist-packages (from nbconvert->notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): mistune!=0.6 in /usr/local/lib/python2.7/dist-packages (from nbconvert->notebook->ipywidgets==4.0.2)
    Requirement already satisfied (use --upgrade to upgrade): functools32 in /usr/local/lib/python2.7/dist-packages (from jsonschema!=2.5.0,>=2.0->nbformat->notebook->ipywidgets==4.0.2)
    Installing collected packages: ipywidgets
      Running setup.py develop for ipywidgets
        Complete output from command /usr/bin/python -c "import setuptools, tokenize; __file__='/home/parashar/ipywidgets/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
        running develop
        Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
        /usr/bin/python -E -c pass
        TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support .pth files
        running jsdeps
        
        > ipython-widget-deps@4.0.0 build /home/parashar/ipywidgets
        > npm run css && npm run buildtests
        
        
        > ipython-widget-deps@4.0.0 precss /home/parashar/ipywidgets
        > rimraf ./ipywidgets/static/widgets/css/
        
        
        > ipython-widget-deps@4.0.0 css /home/parashar/ipywidgets
        > node build_css.js
        
        > lessc --include-path=./less_include ./ipywidgets/static/widgets/less/widgets.less ./ipywidgets/static/widgets/css/widgets.css
        FileError: '/components/bootstrap/less/variables.less' wasn't found. Tried - /components/bootstrap/less/variables.less,/home/parashar/ipywidgets/ipywidgets/static/widgets/less/components/bootstrap/less/variables.less,/home/parashar/ipywidgets/less_include/components/bootstrap/less/variables.less in /home/parashar/ipywidgets/ipywidgets/static/widgets/less/widgets.less on line 2, column 1:
        1 // minimal imports from bootstrap - only variables and mixins
        2 @import "/components/bootstrap/less/variables.less";
        3 @import "/components/bootstrap/less/mixins.less";
        
        `lessc --include-path=./less_include ./ipywidgets/static/widgets/less/widgets.less ./ipywidgets/static/widgets/css/widgets.css` failed with status=1
        
        npm ERR! Linux 3.13.0-37-generic
        npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "css"
        npm ERR! node v4.2.0
        npm ERR! npm  v2.14.7
        npm ERR! code ELIFECYCLE
        npm ERR! ipython-widget-deps@4.0.0 css: `node build_css.js`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the ipython-widget-deps@4.0.0 css script 'node build_css.js'.
        npm ERR! This is most likely a problem with the ipython-widget-deps package,
        npm ERR! not with npm itself.
        npm ERR! Tell the author that this fails on your system:
        npm ERR!     node build_css.js
        npm ERR! You can get their info via:
        npm ERR!     npm owner ls ipython-widget-deps
        npm ERR! There is likely additional logging output above.
        
        npm ERR! Please include the following file with any support request:
        npm ERR!     /home/parashar/ipywidgets/npm-debug.log
        
        npm ERR! Linux 3.13.0-37-generic
        npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
        npm ERR! node v4.2.0
        npm ERR! npm  v2.14.7
        npm ERR! code ELIFECYCLE
        npm ERR! ipython-widget-deps@4.0.0 build: `npm run css && npm run buildtests`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the ipython-widget-deps@4.0.0 build script 'npm run css && npm run buildtests'.
        npm ERR! This is most likely a problem with the ipython-widget-deps package,
        npm ERR! not with npm itself.
        npm ERR! Tell the author that this fails on your system:
        npm ERR!     npm run css && npm run buildtests
        npm ERR! You can get their info via:
        npm ERR!     npm owner ls ipython-widget-deps
        npm ERR! There is likely additional logging output above.
        
        npm ERR! Please include the following file with any support request:
        npm ERR!     /home/parashar/ipywidgets/npm-debug.log
        rebuilding js and css failed
        missing files: ['/home/parashar/ipywidgets/ipywidgets/static/widgets/css/widgets.min.css', '/home/parashar/ipywidgets/ipywidgets/tests/bin']
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/home/parashar/ipywidgets/setup.py", line 294, in <module>
            setup(**setup_args)
          File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
            dist.run_commands()
          File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
            self.run_command(cmd)
          File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
            cmd_obj.run()
          File "/home/parashar/ipywidgets/setup.py", line 159, in run
            raise e
        subprocess.CalledProcessError: Command '['npm', 'run', 'build']' returned non-zero exit status 1
        
        ----------------------------------------
    Command "/usr/bin/python -c "import setuptools, tokenize; __file__='/home/parashar/ipywidgets/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/parashar/ipywidgets

**Comment by parashardhapola** [comment]
Got same result even when I removed previous node version using ```sudo apt-get remove nodejs```
This doesn't affect the version installed form source.
