### ISSUE TITLE
IntRangeSlider handles bug out when they overlap

### ISSUE THREAD

**Issue by jgoad** [ipython/ipywidgets#171]
When the handles get dragged on top of one another, they get stuck like that, requiring the widget to be reset. Would it be possible to set the min and max of each slider by setting the min and max attributes with tuples instead of ints, allowing a min and max to be set for both handles? This could also be resolved with resetting the values up or down one if they overlap (my hack).

**Comment by jgoad** [comment]
something like...

```
if self.value[0] == self.value[1]:
        if self.value[0] >= self.min and self.value[0]-1 >= self.min:
            self.value = (self.value[0]-1,self.value[1])
            
        else:
            self.value = (self.value[0],self.value[1]+1)
```

**Comment by jgoad** [comment]
Ah this only happens on the end values because the right handle is always on top, and can't move further right and is not allowed to move left.

**Comment by jdfreder** [comment]
I think I've reproduced this, but for me it only occurs on the left hand side of the slider.  Action shot:

![demo](https://cloud.githubusercontent.com/assets/3292874/10547024/8b5da6de-73e6-11e5-9f11-2a7104a81cd7.gif)

**Comment by jgoad** [comment]
In order to reproduce you have to let them overlap, click away, and then try to move them again.

**Comment by jdfreder** [comment]
I did that, and it still seems to know which one I want to click on.  If I'm at the left, it causes the rightmost handle to select when I click on them.  If I'm at the right, it causes the left most handle to select.

**Comment by jdfreder** [comment]
Trippyyyy:

![demo](https://cloud.githubusercontent.com/assets/3292874/10547263/2c16e594-73e8-11e5-88ce-d96fe3312b17.gif)

**Comment by jgoad** [comment]
^ Definitely needs to be merged. Well it's a mystery then! Unless you are using the dev version and I'm using the release version and it was fixed on yours.You are letting them overlap completely, right?

**Comment by jdfreder** [comment]
Yes.  Also I tried changing the margins so that the never could overlap, and the same Javascript that I think is making it work on my machine by guessing which handle I want to click on, makes the margin differences useless.  It may be that you and I have different versions of jquery ui.  I'll see if I can pin to the one I have.

**Comment by jdfreder** [comment]
No, the only earlier version of jquery ui that works, 1.10.3, also doesn't have this problem.  Bower should have installed 1.10.4 for you alongside the notebook.

I think the next step is to have you run master to see if that fixes your problem.  Do you need help with that?

**Comment by jasongrout** [comment]
We've now upgraded jquery ui to a much more recent version. I just checked, and it seems to work all right in master.

Closing as fixed, but if you see the same issue in master, please reopen.

![rangeslider](https://cloud.githubusercontent.com/assets/192614/20279069/0c03a7b4-aa75-11e6-9ca8-994b9ec14c43.gif)
