### ISSUE TITLE
Remove deprecated widget names

### ISSUE THREAD

**Issue by jdfreder** [ipython/ipywidgets#18]
Things like ButtonWidget, IntTextWidget, etc... were deprecated in 3.0, is 4.0 too soon to remove them?  @minrk @jasongrout @SylvainCorlay

**Comment by SylvainCorlay** [comment]
:+1:

**Comment by jasongrout** [comment]
I'm all for removing them

**Comment by jasongrout** [comment]
Actually, on second thought, we might as well make them part of the directory deprecation.  When that goes away, remove them

**Comment by jasongrout** [comment]
A corollary of my comment would be to not support the deprecated widget names from the ipython_widgets namespace, but only from the IPython.html.widgets namespace.

**Comment by minrk** [comment]
That may be tricky, given how the shims work, but a good idea in principle.

**Comment by jdfreder** [comment]
Can we just change the shim so instead of importing `ipython_widgets`, it imports, say, `ipython_widgets.deprecated_names` or something?

**Comment by SylvainCorlay** [comment]
Is it worth touching the shims to remove deprecated classes?

**Comment by jasongrout** [comment]
I would say that a deprecation period of several months is way too short (3.0->4.0 timeframe).  At least a year is better, in my opinion, especially in this case where it is easy to support the old names in the old location.

**Comment by minrk** [comment]
@jasongrout that's not how the widgets have behaved yet, though. If anything, the widgets are still in '0.x' pre-alpha territory.

**Comment by jasongrout** [comment]
@minrk: We did put a deprecation warning in, which showed some sensitivity to people using the old names.  And we support people using old locations (`IPython.html.widgets`) for the 4.0 transition.  So we are already doing a minimal amount to support 'legacy' users of widgets.

**Comment by jasongrout** [comment]
But the status quo is to just leave the deprecated names in the current codebase (in the new location) for a bit longer.  I'm fine with that too.
