### ISSUE TITLE
Spacing between widgets (esp buttons)

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipywidgets#182]
This past week in NYC I have seen a bunch of people building really cool things with widgets. The one thing that keeps coming up is the layout of things. I particular, when lots of buttons are used, then end up right next to each other, which looks really wonky. Also, overall, our layout is pretty big - we could make things a bit smaller, but add some borders. Would be fun to have @cameronoelsen take a pass at a more Material Design widget design.

**Comment by jdfreder** [comment]
I've used http://material-ui.com/#/components/appbar with great success in a phone app I've been building.

**Comment by jdfreder** [comment]
> Would be fun to have @cameronoelsen take a pass at a more Material Design widget design.

+1

**Comment by SylvainCorlay** [comment]
:+1: for giving some attention to the design.

Regarding the rich layout of widgets for visualization dashboards, this would probably require exposing much more options to the Python side than in the current implementation of the flexbox containers.

**Comment by cameronoelsen** [comment]
@jdfreder @ellisonbg What do they currently look like right now? Is there some code I can run in the notebook to use widgets or maybe a screenshot. Then I'll start right away on this :+1:

**Comment by ellisonbg** [comment]
@jdfreder where is your widget master notebook that has all widgets?

On Thu, Oct 15, 2015 at 5:03 PM, Cameron Oelsen <notifications@github.com>
wrote:

> @jdfreder <https://github.com/jdfreder> @ellisonbg
> <https://github.com/ellisonbg> What do they currently look like right
> now? Is there some code I can run in the notebook to use widgets or maybe a
> screenshot. Then I'll start right away on this [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/issues/182#issuecomment-148520639>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
Presenting Le Super Widget: https://gist.github.com/jdfreder/9103330

It renders pairs of widgets side by side.

**Comment by cameronoelsen** [comment]
![widgets](https://cloud.githubusercontent.com/assets/6437976/10653947/4c9415aa-7819-11e5-81a1-7f3f10d752b0.png)
Got halfway done with the styling of the widgets today :+1: 
The second half will be knocked out before Friday, so far they look pretty dang good!

**Comment by jdfreder** [comment]
Cool design!  Are you doing this all in sketch?

**Comment by SylvainCorlay** [comment]
@cameronoelsen this design looks really nice!
Regarding the float slider, it might be misleading to fill the left-hand side with orange since it is not a progress bar.

A widget that is not in the list is the `Controller`widget. It detects the connected gamepad and creates as many axis (sliders between -1 and 1) and buttons (boolean or trigger between 0 and 1) widgets as required.

These widgets are display-only (no mouse interactions)

- For the XBox Controller:
<img width="483" alt="xbox_controller" src="https://cloud.githubusercontent.com/assets/2397974/10656647/0d4f9302-784f-11e5-8f0f-b4b15cdf8ba2.png">

- Another example with a Saitek Joystick, which has much more axes and buttons
<img width="534" alt="saitek_controller" src="https://cloud.githubusercontent.com/assets/2397974/10656663/48329f1e-784f-11e5-8dd6-872ffcf8cd14.png">

I did not use the standard sliders and buttons thinking that they would be too big for this purpose, but it would be really nice to have a consistent design. Another issue is that certain buttons like triggers on the xbox controller have a continuous value between 0 and 1, and are not nicely represented by classical buttons.

**Comment by ellisonbg** [comment]
Cameron, thanks for working on this. Lots of great ideas here. A few
questions:

* The visual style of some of these is the MD "card" look. How do you thin
that would look if cells were also cards? Does that get to be too many
nested levels of cards? What does the MD spec say about that?
* One of the big challenges we have right now is that things start to look
ugly when you have lots of widgets right next to each other. Imagine 4
sliders in a vbox, or a bunch of buttons. Any ideas on how to get them to
look good with a bunch of them together. What type of padding would there?
How would you manage different heights/widths?

On Wed, Oct 21, 2015 at 8:30 PM, Cameron Oelsen <notifications@github.com>
wrote:

> [image: widgets]
> <https://cloud.githubusercontent.com/assets/6437976/10653947/4c9415aa-7819-11e5-81a1-7f3f10d752b0.png>
> Got halfway done with the styling of the widgets today [image: :+1:]
> The second half will be knocked out before Friday, so far they look pretty
> dang good!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/issues/182#issuecomment-150062909>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by cameronoelsen** [comment]
@ellisonbg I was thinking about this exact issue with too many cards colliding within the notebook. I think one cool solution for making everything MD while also acting as one is by taking some cues from Google's new Inbox web application.
<img width="944" alt="screen shot 2015-10-26 at 3 50 54 pm" src="https://cloud.githubusercontent.com/assets/6437976/10744743/66480bda-7bf9-11e5-8e59-6f8bbf39de3f.png">

With this, we could have the cells enlarge for whatever cell you are working on (not as drastic as pictured above but solely the concept)

I'll get some mockups for this in the next few days and we can see what we think!

**Comment by cameronoelsen** [comment]
So before I approach widgets within cells, I mocked up the design I was going towards for the notebook. This is taking the data from the Python test notebook from tempnb. When you click on a cell it focuses in and expands. The grey circles on the left are input cells and when you run, an output cell is generated with an orange dot. I am going to need to elaborate on this and talk to you @ellisonbg about it when you get back to California but I think this is a nice direction with material design.

![notebook example](https://cloud.githubusercontent.com/assets/6437976/10804373/63edd04a-7d84-11e5-85d6-ee3ee1bd67eb.png)

**Comment by jdfreder** [comment]
The whitespace between the logo and the menu on the right feels a bit too dramatic for my tastes.  I like what you've done with the prompts though, and the colors!  Have you seen Tim Clem's design, [here](https://github.com/jupyter/design/issues/10)?

**Comment by jasongrout** [comment]
Closing as outdated at this point - we'll try to do another UI refresh for 6.x
