### ISSUE TITLE
ipywidgets uses traitlets private API `_notify_trait`

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#194]
cf discussion in https://github.com/ipython/traitlets/pull/101. We can either make the new `_notify_change` public as discussed in the PR or make traitlet use the public API and avoid this overloading.

**Comment by minrk** [comment]
+1 to using the public event notification API here, if it works.

**Comment by SylvainCorlay** [comment]
As per discussion in #270, we cannot directly use the notification API, and will have to rely on overloading the (now public API) `notify_change`.
