### ISSUE TITLE
Add npm as prerequisite

### ISSUE THREAD

**Issue by robnagler** [ipython/ipywidgets#195]
If you don't have npm install, you get confusing errors.

```text
Installing collected packages: ipywidgets
  Running setup.py develop for ipywidgets
    Complete output from command /home/vagrant/.pyenv/versions/2.7.10/bin/python2.7 -c "import setuptools, tokenize; __file__='/home/vagrant/src/ipywidgets/setup.py'; exec(com\
pile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
    /home/vagrant/.pyenv/versions/2.7.10/lib/python2.7/site-packages/setuptools/dist.py:282: UserWarning: Normalizing '4.2.0dev' to '4.2.0.dev0'
      normalized_version,
    running develop
    running jsdeps
    npm unavailable
    rebuilding js and css failed
    missing files: ['/home/vagrant/src/ipywidgets/ipywidgets/static/widgets/css/widgets.min.css', '/home/vagrant/src/ipywidgets/ipywidgets/tests/bin']
    error: [Errno 2] No such file or directory
```

**Comment by minrk** [comment]
@jdfreder did the last sdists build wrong? Those css files should be built as part of making the release.

**Comment by jdfreder** [comment]
It didn't complain, and the machine that published it has compiled css.  Also, I don't think I changed anything that would have caused that to no longer to be included.  Stange..  It's the manifest or setup.py that specifies what's included?

**Comment by jdfreder** [comment]
@minrk is it possible the commands I ran aren't correct?  I documented my steps here: https://github.com/ipython/ipywidgets/blob/master/RELEASE.md

( I've automated those same steps in https://github.com/ipython/ipywidgets/pull/193 )

**Comment by minrk** [comment]
It's possible we have something wrong in MANIFEST.in or some such. I'll look into it. I don't think the commands you called are wrong, so it's probably something in the command itself.

**Comment by minrk** [comment]
@jdfreder I looked at the sdist, and it seems to actually be working fine.

@robnagler it looks like you are installing from GitHub. NPM is already a prerequisite when installing from GitHub, but we cannot Is the issue here that the error message on failure due build due to "npm unavailable" isn't clear enough?
