### ISSUE TITLE
Install directly from github

### ISSUE THREAD

**Issue by robnagler** [ipython/ipywidgets#196]
For most users, installing directly from github is probably easiest

```sh
pip install git+git://github.com/ipython/ipywidgets.git
```

I suggest the README be changed to reflect this.

**Comment by minrk** [comment]
@robnagler most users should probably install the stable version, which would be `pip install ipywidgets`. Installing from master should only be for those who know what they are doing and are interested in keeping up with the unstable development version.

**Comment by jdfreder** [comment]
I agree with @minrk .  Also, I think most people prefer a stable branch, master tends to have bugs when we aren't near a release.

**Comment by robnagler** [comment]
I apologize for not being clear. These instructions in [README.md](https://github.com/ipython/ipywidgets/blob/master/README.md) do not work:

```
## Install

0. Install [notebook](https://github.com/jupyter/notebook)

1. Install the package

        pip install -e .
```

If you meant to install from PyPI, then step 1 should be:

```
pip install ipywidgets
```

If you mean to install from git, then I would suggest installing directly:

```
pip install git+git://github.com/ipython/ipywidgets.git
```

**Comment by minrk** [comment]
Ah, those instructions are for working on the repo itself, so they assume that you are working in the repo already. That should be made explicit, which #200 should accomplish.
