### ISSUE TITLE
Notes on widget layout fixes

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#206]
Notes on discussion with Brian and Jon.
- [x] Padding / Margins: the current base widget has no padding and no margin
  proposed solution is: 0 padding everywhere. 2px margin everywhere except for containers.
- [x] Audit which selector is used to apply the `_css` property and top level styling properties. Specifically `Text` cannot be resized at the moment. 
- [x] `Button`: styling missing in `widgets.less`. Should have a `min-width` and a `min-height`?
- [x] More generally should we expose the entire flexbox specification in widgets
  - expose all flexbox **container** properties in containers.
  - expose all flexbox **item** properties in _all_ DOMWidgets.
  - get rid of `FlexBox` widget (`Box` will have all its properties).
- Discussion on renaming: (postponed)
  
  > - XObject (current Widget class, no visual representation, like `jslink` or `bqplot.Scale`).
  > - Visual Widget with no styling model attributes (DOMWidget). Compared to base `XObject`, it only triggers displaying widget area.
  > - Styled Widget (Exposes entire flexbox spec) (current StyledWidget). Base to all other ipywidgets.
- [x]  Brian: have a child `Style`widget applying styles to specified selectors of its parent widget.
- [ ] css helper methods? (Eventful Dict, base on the new traitlet API? `change: {'type': 'element_change'}`). 
- [ ] On `Eventful` containers: rename it `Observable[Dict/List]` -> add it to traitlets?
- [ ] Split base widgets into child widgets for description / main widget etc?

**Comment by blink1073** [comment]
I made an observable list traitlet for my own use: https://github.com/metabolite-atlas/metatlas/blob/9c20a1f34b595d78d8453057fb64f5a6b84dd390/metatlas/metatlas_objects.py#L29-L93

**Comment by blink1073** [comment]
*Crap*, I did not realize you had them in `ipywidgets`.

**Comment by jdfreder** [comment]
@blink1073 awesome!  We have something similar in traitlets already - the EventfulList and EventfulDict, but I think we may put this off till the following major release, because we need to implement the synchronization properly, and wait for @ellisonbg or @Carreau to make observable arrays and objects in JavaScript.

**Comment by SylvainCorlay** [comment]
@blink1073 the new API to traitlets allows for change dictionary to have a `type` attribute specifying the type of change, so that we can observe trait changes but potentially also element changes etc...

**Comment by blink1073** [comment]
It looks like they were in `traitlets` but then moved here and stripped of their `traitlet` status.

**Comment by jdfreder** [comment]
> It looks like they were in traitlets but then moved here and stripped of their traitlet status.

Sad :panda_face:

**Comment by SylvainCorlay** [comment]
Yes, but the new API makes it more natural to integrate them back.

**Comment by blink1073** [comment]
Yep, agreed.

**Comment by jdfreder** [comment]
@SylvainCorlay I edited this to use check boxes for convinience

**Comment by jasongrout** [comment]
@SylvainCorlay says this is not relevant any more since the code has moved way beyond this.
