### ISSUE TITLE
Widgets should always fall within their width

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipywidgets#213]
Right now there are certain widgets that have a width property, but whose view extends beyond that width. Typically this happens when they are given a `description`. Here are ones we know about:

- [ ] Dropdown
- [ ] Sliders
- [ ] Progress

Also, should the drop down be 150 or 300px wide?

**Comment by SylvainCorlay** [comment]
I think that this is solved now, with recent PRs on widget styling. Closing.
