### ISSUE TITLE
No way to get ToggleButtons with just an icon

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipywidgets#220]
Right now you can get a ToggleButtons with text labels or text labels+icon, but you can't get just icons. This is a common usage case we should support.

**Comment by ellisonbg** [comment]
Would probably need to break the API, but not sure.

**Comment by hainm** [comment]
it seems that this issue can be closed.

![togglebutton](https://cloud.githubusercontent.com/assets/4451957/17390614/af548fc6-59dc-11e6-998f-f2d57357e044.png)

**Comment by minrk** [comment]
Thanks!
