### ISSUE TITLE
Scrolling dropdown.

### ISSUE THREAD

**Issue by jdfreder** [ipython/ipywidgets#227]
Suggested by @stefanv in https://github.com/ipython/ipython/issues/8278

Why not switch to a scrollable dropdown when the list reaches a certain length? This is the same pattern followed elsewhere (e.g., output handling).

cc @olgabot

**Comment by ellisonbg** [comment]
+1

On Wed, Nov 4, 2015 at 7:14 PM, Jonathan Frederic <notifications@github.com>
wrote:

> Suggested by @stefanv <https://github.com/stefanv> in ipython/ipython#8278
> <https://github.com/ipython/ipython/issues/8278>
>
> Why not switch to a scrollable dropdown when the list reaches a certain
> length? This is the same pattern followed elsewhere (e.g., output handling).
>
> cc @olgabot <https://github.com/olgabot>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/issues/227>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
