### ISSUE TITLE
Validate that static content version matches backend version on import

### ISSUE THREAD

**Issue by jdfreder** [ipython/ipywidgets#235]
I see a lot of problems where people with envs that differ slightly from the simplest possible have trouble using ipywidgets because the front-end content doesn't align with the back-end content.  I think we should investigate checking/validating the versions of the two on import, and error/warn on mismatch.

**Comment by aggFTW** [comment]
I'm wondering if #233 is related to this? :stuck_out_tongue: 

**How can I check myself?**

What is the front-end and the back-end in this context? In 233 you said:
```
Background: ipywidgets is not only a package used by you in Python, but it's also a package used by the webserver to host static content. It's crtitical that both run the same version of ipywidgets because the static content hosted by the webserver is designed to communicate with the code you run in the kernel.
```
but I didn't get what the webserver is in that sentence.

**Comment by jdfreder** [comment]
Yeah, I opened this after looking at #233 :smile: 

The web server is what you launch when you run `jupyter notebook` or `ipython notebook`.  The kernel, which is the thing that executes the code you run, is actually an entirely different process which gets launched by the web server.  The client is what you see in the web browser, which is the browser's rendering of the static content hosted by the web server.

**Comment by aggFTW** [comment]
Thanks @jdfreder! :) This will be useful for sure!
