### ISSUE TITLE
Creating a new cell by clicking a widget button is somehow buggy

### ISSUE THREAD

**Issue by jakobgager** [ipython/ipywidgets#242]
I've been trying to create a widget button which can be used to create a new cell.
Unfortunately, after clicking the button, the new cell is created only after I execute another cell.
The following minimal example (tested on TryJupyter) recreates to problem (I know that the imports are deprecated):

```python
from IPython.html import widgets
from IPython.display import display

def but1(b):
    get_ipython().set_next_input('NewParameterCell',replace=False)

Button1 = widgets.Button(description='Restart')
Button1.on_click(but1)
display(Button1)
```

A quick screen:
![2015-11-19_090923](https://cloud.githubusercontent.com/assets/1677740/11265676/90de52a2-8e9e-11e5-939d-e31dd18ce287.png)

Is there a workaround to create new cells when clicking a widget button? Moreover, I sometimes meet NameErrors with get_ipython not found in this context.

**Comment by jdfreder** [comment]
Hi @jakobgager ,

Unfortunately that's a part of a long standing issue that's related to how code outside of the context of a cell is executed: https://github.com/ipython/ipython/issues/5006  Related #44 .

The best way to do what you're trying to accomplish is to use Javascript.  The notebook model lives in the front-end, so you have full control of it there.  You can use display to publish the Javascript.

Cheers,
Jon

**Comment by jakobgager** [comment]
Thanks for the hint to ipython/ipython#4983 which is exactly the same question including your javascript based solution. Closing here. 
Unfortunately, I lost track of jupyter development, since it got more and more javascript centric. I never get warm with Javascript :frowning:. Anyway, thanks a lot!

**Comment by jdfreder** [comment]
@jakobgager yeah, I haven't seen you for a while!  Thanks for dropping by.  If you feel like getting friendly with Javascript, would love a PR to fix the root issue (which is actually almost entirely in IPython, not the notebook front-end)! ;)
