### ISSUE TITLE
ipywidgets widget layout problem in safari 

### ISSUE THREAD

**Issue by jdfreder** [ipython/ipywidgets#249]
Originally entered by @mbakker7 in https://github.com/jupyter/notebook/issues/709

---

A slider widget, created with ipywidgets.interact, shows a strange layout in Safari.
Example code:

    def printx(x):
        print x
    from ipywidgets import interact
    interact(printx, x=(-10,10)); 

The widget has the name of the variable (here x) on the right side of the window. Other than that, the widget works fine.

Safari 8.06
ipywidgets 4.1.0
jupyter notebook 4.0.6
python 2.7.10

Same code on same machine (so same ipywidgets, jupyter, python) works fine with Chrome.

**Comment by captainsafia** [comment]
Reproduced. Working on a fix.

**Comment by captainsafia** [comment]
@mbakker7, can you reproduce in Safari 9 on your machine?

**Comment by mbakker7** [comment]
I may have access to a machine with Safari 9 (or higher? not sure what the
number is with El Capitan) on Monday.

Mark

**Comment by jdfreder** [comment]
Thanks @captainsafia !

**Comment by captainsafia** [comment]
@mbakker7 — let me know if you have had a chance to reproduce on Safari 9.

Also, a screenshot would be nice!

**Comment by mbakker7** [comment]
Will send a screenshot on Wednesday. I am away from the computer with
Safari 9 today.

**Comment by mbakker7** [comment]
Problem does not occur anymore in Safari 9.0.1, ipywidgets 4.1.0.

Please close the issue.

Thanks,

Mark

**Comment by jdfreder** [comment]
Thanks!

**Comment by IeiuniumLux** [comment]
I'm now using `Safari 13.1.1` and I cannot see the `widgets.IntSlider` anymore.

<img width="814" alt="Screen Shot 2020-05-28 at 10 33 00 PM" src="https://user-images.githubusercontent.com/3729432/83224997-a319c300-a133-11ea-9d6c-cf10ab718200.png">

**Comment by mbakker7** [comment]
Could you post a minimal script that produces the problem so I can try it in my Safari?

**Comment by IeiuniumLux** [comment]
Hi @mbakker7, jupyter notebook and test csv file attached. Just remove the .txt postfix at the end. Thanks!

[03_01_visualization_end.ipynb.txt](https://github.com/jupyter-widgets/ipywidgets/files/4703934/03_01_visualization_end.ipynb.txt)
[gapminder.csv.txt](https://github.com/jupyter-widgets/ipywidgets/files/4703935/gapminder.csv.txt)

**Comment by mbakker7** [comment]
Can you not reproduce this with a few (5 or so) lines of code? It is just
the IntSlider, right? Can you make a truly minimal example that shows the
problem?

**Comment by IeiuniumLux** [comment]
@mbakker7 The previous notebook was quite small already. Did you try to run it?  I'm a little bit smaller version (just 5 cells) here.  Anyway, either one should be pretty easy to run/test.
[03_01_visualization_end.ipynb.txt](https://github.com/jupyter-widgets/ipywidgets/files/4704961/03_01_visualization_end.ipynb.txt)

**Comment by IeiuniumLux** [comment]
@mbakker7 Yes, the problem is with IntSlider.  It's not showing in Safari like it's shown below.
<img width="1211" alt="Screen Shot 2020-05-29 at 11 21 46 PM" src="https://user-images.githubusercontent.com/3729432/83321343-d62b8780-a203-11ea-90b7-765e12230bce.png">

**Comment by mbakker7** [comment]
Please post a minimal example. Just a few lines of code with an `IntSlider` that produces the problem.

**Comment by IeiuniumLux** [comment]
@mbakker7 Not sure I follow.  Have you seen how small or minimal is the notebook I attached early?

**Comment by mbakker7** [comment]
Can you just copy paste the lines here?
