### ISSUE TITLE
The ipywidget traits should be defined in Javascript too

### ISSUE THREAD

**Issue by jdfreder** [ipython/ipywidgets#251]
Right now the design of our widgets is asymmetric.  To help kernel authors and make the design more symetric, we should define the widget traits in the front-end too.  The would allow us to get rid of the kludgey request_state call in new_widget.

**Comment by SylvainCorlay** [comment]
This is very important to get default values when embedding widgets in kernel-less web pages. However, a new front-end connecting to a live kernel will still need to request state.

I would really like to tackle this one in 5.0.

**Comment by SylvainCorlay** [comment]
I think that we can say this was solved with the default values PR.
