### ISSUE TITLE
Question about how to use existing widgets without necessarily creating custom widgets

### ISSUE THREAD

**Issue by rdhyee** [ipython/ipywidgets#263]
As someone learning how to use widgets at the moment, I wanted to record a conceptual question I'm wrestling with.  As I've worked through the examples, I feel I understand what `interact` and `interactive` are about.  And because you've provided lots of examples for custom widget development, I think that I can see the process I'd undergo to teach myself how to write a custom widget.  

However, I don't quite get how to make use of the large collection of widgets included in `ipywidgets`.  Inspired by @a-campbell's  https://github.com/a-campbell/widgetsapp  I would like to write a simple interactive application in the Notebook which would let me manage a list of items:  view them, delete them, add new ones.  I *think* that I should be able to piece together a bunch of the existing widgets, populate them with data from Python data structures, and register callbacks written in *Python* to take action on the data structures. I suspect that I shouldn't have to write any JavaScript to create a useful little app.  

If I'm correct, having several examples in which some widgets are stitched together combined with some logic written in Python (with no JavaScript) would be super helpful.  (I'm going down the road now of figuring out whether my hypothesis that I can create such an example w/o any JavaScript is correct.)

**Comment by blink1073** [comment]
@rdhyee, yep, here is an example which includes widgets and a matplotlib plot:

```python
%matplotlib notebook
from IPython.html.widgets import HBox, Button
from IPython.display import display
from matplotlib import pyplot as plt

red = Button(description='Make Red')
green = Button(description='Make Green')

fig, ax = plt.subplots()
ax.plot([1,2,3])

def make_red(button):
    ax.lines[0].set_color('red')
    ax.figure.canvas.draw()

def make_green(button):
    ax.lines[0].set_color('green')
    ax.figure.canvas.draw()

red.on_click(make_red)
green.on_click(make_green)
display(HBox([red, green]))
```

**Comment by rdhyee** [comment]
Thanks, @blink1073!  For whatever reason, it was not obvious to me to you could do exactly what you wrote here. :-)

**Comment by blink1073** [comment]
Cheers, I agree, an example like this would certainly help.
Note that the matplotlib figure is not a widget, but exists separately in the "output area".  There are plans to make it a proper widget in the future.

**Comment by rdhyee** [comment]
Once I got going with the [example](https://github.com/ipython/ipywidgets/issues/263#issuecomment-162618717) provided by @blink1073, I then revisited  [ipywidgets/examples/notebooks/Widget Events.ipynb](https://github.com/ipython/ipywidgets/blob/master/examples/notebooks/Widget%20Events.ipynb), which I now realize has a lot of information I needed. That is, I then got to understand the usefulness of `on_trait_change`.

**Comment by blink1073** [comment]
ping @robclewley, this may be of interest to you.

**Comment by jasongrout** [comment]
It sounds like this question has been answered. Thanks everyone!
