### ISSUE TITLE
Slider sum

### ISSUE THREAD

**Issue by jcrichard** [ipython/ipywidgets#269]
Hi,

I have 5 floatsliders and I want the sum of the values be always one. I could you do that, I can't figure out.

Thanks a lot

**Comment by jdfreder** [comment]
Hi @jcrichard 

You can use `on_trait_change` to listen to the value change event of each slider.  Use a lock to ignore the trait change events of the other sliders while in the trait change event of one slider.  Then inside that lock, use math to decide what the values of all of the other sliders should be relative to the changes of the current slider.  i.e. if you increase the current slider's value by 0.1, the other 4 sliders would decrease in value by 0.025.
