### ISSUE TITLE
ipywidgets (4.1.1) doesn't display textbox

### ISSUE THREAD

**Issue by aragnon** [ipython/ipywidgets#274]
The below code is supposed to display a textbox when executed; it doesn't in Chrome and Opera and I have not seen a single browser where it does work. Additionally, there are no error messages.  

This is using Python 2.7.10.  
```
from ipywidgets import widgets
from IPython.display import display
text = widgets.Text()
display(text)

def handle_submit(sender):
    print text.value

text.on_submit(handle_submit)
```

Expected behaviour: see a text box in which I can type something.

**Comment by avishapiro** [comment]
This code works for me in IPython 4.0.1 using Python 2.7.11 and ipywidgets 4.1.0 but I've had a lot of trouble using widgets that "should" work so I sympathize. What version of IPython are you using? One thing that has helped me is to restart ipython and try again without any other code getting in the way.

**Comment by jdfreder** [comment]
@aragnon sounds like an install failure.  If you look in your web dev console you'll probably see "comm" related errors.  I've implement cross context version validation in https://github.com/ipython/ipywidgets/pull/303 , which should make problems like this noisy.  Let me know if you need further help debugging your installation.  When pip installing the widgets, try using `--verbose` to see what exactly is going on.
