### ISSUE TITLE
Issue running JavaScript tests on ipywidgets

### ISSUE THREAD

**Issue by captainsafia** [ipython/ipywidgets#280]
So, I'm trying to run the JavaScript test suit on ipywidgets. Per the README, the following command should do the trick.

```
npm run buildtests; python -m ipywidgets.jstest
```

But alas, it errors out on the `npm run buildtests` portion of the command as there is no `buildtests` script in the current `package.json`. Is the README outdated or am I missing something?

**Comment by jdfreder** [comment]
Sorry, this is my fault.  I recently removed those Javascript tests, in favor of mocha test.  `npm run test` should do the trick now.  The README needs to be updated.
