### ISSUE TITLE
Add badges for RTD docs to README

### ISSUE THREAD

**Issue by willingc** [ipython/ipywidgets#297]
Update README to link to hosted docs.

@Carreau can you add me as an admin on RTD for this https://readthedocs.org/projects/ipywidgets/
Thanks :sunny:

**Comment by SylvainCorlay** [comment]
btw, @willingc when you enable ipywidgets on RTD, you should choose to display the "latest" by default instead of "stable" until 5.0 is released.

**Comment by jdfreder** [comment]
@willingc I just sent him an email in case he is away from GitHub.  I cc'ed you

**Comment by willingc** [comment]
Thanks @jdfreder and @SylvainCorlay. I wanted permission so I can make sure the builds on RTD are updating properly. They seem a bit dated to me.

**Comment by Carreau** [comment]
You all should be admin now. If you are setting up the docs, i would have a look at the new ability to use `readthedocs.yml` file as well as use conda instead of venv.

**Comment by willingc** [comment]
I manually had RTD build the latest version of master so the latest docs are now live. http://ipywidgets.readthedocs.org/en/latest/index.html

I also enabled ReadTheDocs under Services in GitHub Settings so the docs should now rebuild on ReadTheDocs after each new commit.

**Comment by jdfreder** [comment]
Awesome!

**Comment by willingc** [comment]
@captainsafia and others: I've put together a brief doc on how to [enable the ReadTheDocs service in GitHub](https://github.com/willingc/calpoly-cnw/blob/master/doc-workflow/docs-rtd-hook.md)
