### ISSUE TITLE
Interact should use OutputWidget

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#316]
If you use print statements or use stderr in the handlers reacting to widget attribute changes, you may have some surprises.

For example, let's say that you use `interact` without the abbreviations:

``` python
from ipywidgets import *

slider = IntSlider()

@interact
def print_value(x=slider):
    print(x)
```

And in a later cell, you display the slider again:

``` python
slider
```
- Moving the first slider view will print the output in the cell where interact was called.
- Moving the second slider view will print the output in the cell where the second view is.

This is logical since the changes that occurs when moving a given view are bound to the cell where that view is displayed (and the right cell callbacks are called etc)... But this behavior can be confusing for users.

More interestingly if the original change event is not bound to a cell (such as a controller widget event, which is caught by the model and not with a specific view), then no callback is called ever. This is the issue met by @rbeezer when he was experimenting with the controller widget.

In my opinion, `@interact` should use the output widget. Besides, this really calls for a global output area in the notebook (at least for debugging purposes) to display stdout and stderr content that does not come from a specific cell.

**Comment by jasongrout** [comment]
> In my opinion, @interact should use the output widget.

This is the TODO for this issue. I think it does this in master, but the output widget might be broken in the classic notebook, so we should check this.

**Comment by jasongrout** [comment]
This is working now.

![interact](https://cloud.githubusercontent.com/assets/192614/21291449/05a056ee-c4ae-11e6-886a-f8f893e9449a.gif)
