### ISSUE TITLE
Single load point for jupyter-js-widgets in requirejs

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#317]
Currently, custom widget libraries like bqplot import their dependencies from ipywidgets separately by requiring

`nbextensions/widgets/widgets/js/utils`
`nbextensions/widgets/widgets/js/widgets`

etc.
 
It would probably be much easier to ensure a smooth transition to npm packages if a single entry point for `jupyter-js-widgets` corresponding to npm's index.js was accessible under the static directory.

**Comment by jdfreder** [comment]
Agreed

**Comment by SylvainCorlay** [comment]
How would you do this. Duplicate the logic of `index.js` in `static/jupyter-js-widgets.js`?
