### ISSUE TITLE
Use pyscript to allow users to write JS interaction and new widgets in python syntax?

### ISSUE THREAD

**Issue by datnamer** [ipython/ipywidgets#324]
https://github.com/zoofIO/flexx compiles a python like syntax to JS. Bokeh currently lets one write JS callbacks with pyscript. Perhaps it can be of use to writing interactive callbacks and bindings to new widgets  here.

**Comment by jdfreder** [comment]
While I think it makes sense to be able to write callbacks for GUI events, I definitely think it's a bad idea to transpile Python to Javascript.  That said, the widgets already support some callbacks for meaningful events like button click and textbox submit.  If there are more events you'd like to see, open an issue for them so we can discuss.  As a side note, it's important that we scope limit ipywidgets and encourage developers to write custom Javascript when it makes sense.
