### ISSUE TITLE
A better error message would be useful.

### ISSUE THREAD

**Issue by dhirschfeld** [ipython/ipywidgets#339]
My first attempt to use ipywidgets and I run into the below error which for less experienced devs may as well be gibberish:
```python
from IPython.display import display
w = widgets.Dropdown(
    options=temperature.columns,
    value='Brisbane',
    description='Location:',
)
display(w)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<SNIP>
Anaconda3\lib\site-packages\ipywidgets\widgets\widget_selection.py in _make_options(self, x)
     65         # Make sure x is a list or tuple.
     66         if not isinstance(x, (list, tuple)):
---> 67             raise ValueError('x')
     68 
     69         # If x is an ordinary list, use the option values as names.

ValueError: x
```
Translation: *Attempted to set options for 'Dropdown' widget with an object of type `<class 'pandas.core.index.Index'>`. Expected a list, tuple or OrderdDict.*

**Comment by minrk** [comment]
@dhirschfeld you opened your PR against your own repo instead of this one. Want to reopen here?

**Comment by minrk** [comment]
And your comment was right - we probably shouldn't be strictly checking for list/tuple.

**Comment by SylvainCorlay** [comment]
In fact, the make_option mechanism was made before we introduced custom validation/coercion in traitlets, and we should probably use it for this. Besides, the raised exceptions should probably be trait errors.

**Comment by jdfreder** [comment]
Thanks @minrk

**Comment by dhirschfeld** [comment]
Yeah, sorry just noticed that I'd opened the PR against my own fork :/  Reopened as  #341.
