### ISSUE TITLE
Problems with widget/output area not expanding properly

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipywidgets#348]
I saw this yesterday in class. Students were using interact and returning (str) values from the function to be displayed. When you use interact in this way the output/widget area doesn't expand to show the returned value. When the function prints it does work.

**Comment by jasongrout** [comment]
This seems to work now. Do you agree it is fixed in ipywidgets master/notebook 4.2.3?

![expand](https://cloud.githubusercontent.com/assets/192614/20283437/100a4f7c-aa87-11e6-9080-5d63c269fd3e.gif)

**Comment by jasongrout** [comment]
@ellisonbg ^

**Comment by jasongrout** [comment]
Closing as fixed - please reopen if you are still seeing this issue, or if the example above is not the same as the issue you are documenting.
