### ISSUE TITLE
Are button events queued or executed in different threads?

### ISSUE THREAD

**Issue by aggFTW** [ipython/ipywidgets#349]

**Comment by aggFTW** [comment]
From https://github.com/ipython/ipywidgets/blob/4f256821b778f494a6b84033dc062aabf6ecb61a/ipywidgets/widgets/widget.py#L51

It seems like they are executed serially, but wanted to make sure.

**Comment by jdfreder** [comment]
Hey @aggFTW ,
Events fired in the frontend and recieved by the backend will be fired as soon as they are received.

In the other direction, events being triggered by code in the backend, this is not always the case.  At a lower level, the comm level, which the widgets are built on top of, if a message is sent on a thread other than the thread that the main ioloop lives on, the message will be queued and sent by the main thread as soon as possible.  See [here in the comm code](https://github.com/ipython/ipykernel/blob/master/ipykernel/comm/comm.py#L69).

**Comment by aggFTW** [comment]
Thanks @jdfreder !
