### ISSUE TITLE
Text does not pass width parameter to HBox it uses internally.

### ISSUE THREAD

**Issue by aggFTW** [ipython/ipywidgets#351]
`Text(value="<hr/>", description="Session to delete:", width="100px")`
and the output is a text box with a description

From the looks of the resulting `<div>` rendered, it seems like Text is internally using an HBox to stitch the value and description together, but the width value is being passed only to the input `type="text"` element and not the description `div class="widget-hbox widget-text"`

**Comment by jdfreder** [comment]
Hey @aggFTW ,

I know we talked on Gitter but I'd like to repeat what I said (from memory) here for everyone else:

The width parameter of Text and other widgets is used to describe the widget alone, not the widget + label.  If you need to control both the widget and label total width, the easiest thing to do is to set the `.description=''` and make your own label using the `Latex` widget.  Then put both the Latex and Text widgets in an HBox widget, and set the width of that.

Cheers!
Jon
