### ISSUE TITLE
All the links in README.md are dead.

### ISSUE THREAD

**Issue by kostrykin** [ipython/ipywidgets#354]
Particularly, the link to the example notebook gives HTTP error 404.

Where do we find the examples?

**Comment by jdfreder** [comment]
Sorry, I need to update it - here it is for now https://github.com/ipython/ipywidgets/blob/master/examples/Index.ipynb

**Comment by kostrykin** [comment]
Thanks, but sadly the links in the document you posted are dead too.

**Comment by jdfreder** [comment]
Really?  I just tried them and the work here.  Occasionally GitHub's notebook renderer hiccups and outputs " Sorry, something went wrong. Reload? " - but a page refresh fixes that.

**Comment by kostrykin** [comment]
Out of the sudden, they're working now. I didn't do a page reload. Maybe it was a temporary server problem, however, it gave me an 404.

**Comment by jdfreder** [comment]
Maybe it was a caching problem.  I'll leave the issue open to remember to make sure the link in the readme.md still works.
