### ISSUE TITLE
Following custom widgets tutorial (or testing a copy of the file) throws js error

### ISSUE THREAD

**Issue by tomhardman0** [ipython/ipywidgets#365]
I'm following the documentation for [creating a custom widget](https://github.com/ipython/ipywidgets/blob/52d1ff2090801856d4863c8768488a43e7266295/examples/Custom%20Widget%20-%20Hello%20World.ipynb) but it's throwing an error in the browser console saying:

`Cannot GET http://localhost:8888/static/jupyter-js-widgets.js?v=20160211163055`
`Uncaught Error: Script error for "jupyter-js-widgets"`

I understand this means the jupyter-js-widgets cannot be found by the request and hence by require. Interestingly I get the same error when I copy the original `.ipynb` file from the repo and run it locally.

This problem happens when executing the 5th interactive cell. Is there a step I'm missing?

I have tried installing `jupyter-js-widgets` with `npm` and even adding an extra static file path to a custom jupyter config but neither worked - then again these steps aren't included in the documentation so I wasn't sure about them.

Version info:
```
'commit_hash': '86d685f',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/tom/python-virutalenvs/jtest/lib/python3.4/site-packages/IPython',
 'ipython_version': '4.1.1',
 'os_name': 'posix',
 'platform': 'Darwin-15.0.0-x86_64-i386-64bit',
 'sys_executable': '/Users/tom/python-virutalenvs/jtest/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03) \n'
                '[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]'}
```

All help greatly appreciated, thank you!

**Comment by takluyver** [comment]
Discussed this on gitter, Tom was using docs which have been updated following the 'small split', so they don't work on the released version of ipywidges.

@tomhardman0 how did you come to the examples? Is there a link somewhere that should be pointing to the latest release tag instead of master?

**Comment by tomhardman0** [comment]
Nothing specific, several google searches for `jupyter javascript` or `jupyter widgets` led me to the master branch in the end. And [the ipywidgets docs page](http://ipywidgets.readthedocs.org/en/latest/examples.html) suggests looking at the repo for examples, but doesn't provide any links. I didn't think to check if master wouldn't be the release branch unfortunately!

Thanks again for your help.

**Comment by takluyver** [comment]
Fair enough, closing this as there's nothing clear for us to do... except *shipit* ;-)

**Comment by wolever** [comment]
FWIW: I've run into this too, and even installing `ipywidgets` from the current master (tagged `ipywidgets-5.0.0.dev0`).

The JS console is also reporting that "ipywidgets package not installed":

![widget test](https://cloud.githubusercontent.com/assets/59575/13126801/06c75576-d59a-11e5-9947-d51daa2d4e15.png)

This is Jupyter version 4.0.6, with packages installed via:

```
$ pip install -U jupyter
$ pip install https://github.com/ipython/ipywidgets/archive/master.zip
```

**Comment by jdfreder** [comment]
Hey @wolever , the development version of ipywidgets (master) requires the development version of the jupyter notebook (5.0 dev, master) because the path for loading the widget javascript has changed and notebook had to be changed accordingly.
