### ISSUE TITLE
No widget in jupyter notebook

### ISSUE THREAD

**Issue by ImmanuelSamuel** [ipython/ipywidgets#375]
There is no widget in the output. 

![image](https://cloud.githubusercontent.com/assets/7865018/13095461/d5392dd2-d4df-11e5-9e42-e78e1b2707ae.png)

**Comment by jdfreder** [comment]
Hi @ImmanuelSamuel , two questions  

- Are there any errors in your Jupyter server terminal?  
- Can you open the web developer console of your web browser and check if any errors are printed there?

**Comment by ImmanuelSamuel** [comment]
No there are no errors in the terminal. 

Web console says:

ipywidgets package not installed.  Widgets are not available.

**Comment by ImmanuelSamuel** [comment]
I did conda install ipywidgets

**Comment by ImmanuelSamuel** [comment]
OK after browsing through the issues I found the reason. I had to do the npm install permissions stuff
