### ISSUE TITLE
IE11 svg and classList

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#376]
With IE11, svg elements don't support classList (we use it in `addClass` / `removeClass`). Besides, `className` is read-only.

**Comment by jdfreder** [comment]
According to MDN IE 10+ supports it: https://developer.mozilla.org/en-US/docs/Web/API/Element/classList  but not for SVG elements and not the "toggle" function.  Did you test locally and that's not the case?

Looks like jquery uses setAttribute - https://github.com/jquery/jquery/blob/a4d16a26abe3ea36337f7bfc4d1bfe13b893cd17/src/attributes/classes.js#L44 , we can always rely on that.

Also, now that we are an npm project, we could probably find a library other than jquery to do it for us.
