### ISSUE TITLE
problem installing jupyter-js-widgets

### ISSUE THREAD

**Issue by poldrack** [ipython/ipywidgets#377]
I have tried installing the latest version from the repo on mac os x (node v5.6.0, nam  v3.6.0) but I am hitting a problem with the javascript widgets.  The pip command seems to install ok using the standard instructions, but then I get the message "ipywidgets package not installed.  Widgets are not available." in the javascript console when I try to use the package in a jupyter notebook.    when I try to install the javascript separately (using "npm install jupyter-js-widgets") I get an error - I am including the entire npm log below).  I have tried the git cleanup trick from https://github.com/ipython/ipywidgets/issues/340 to no avail, same error persists.

cat /Users/poldrack/code/ipywidgets/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'jupyter-js-widgets' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData jupyter-js-widgets
8 silly fetchDirectoryPackageData jupyter-js-widgets
9 silly install normalizeTree
10 silly loadCurrentTree Finishing
11 silly loadIdealTree Starting
12 silly install loadIdealTree
13 silly cloneCurrentTree Starting
14 silly install cloneCurrentTreeToIdealTree
15 silly cloneCurrentTree Finishing
16 silly loadShrinkwrap Starting
17 silly install loadShrinkwrap
18 silly loadShrinkwrap Finishing
19 silly loadAllDepsIntoIdealTree Starting
20 silly install loadAllDepsIntoIdealTree
21 silly resolveWithNewModule jupyter-js-widgets@0.0.14 checking installable status
22 silly cache add args [ 'jupyter-js-widgets', null ]
23 verbose cache add spec jupyter-js-widgets
24 silly cache add parsed spec Result {
24 silly cache add   raw: 'jupyter-js-widgets',
24 silly cache add   scope: null,
24 silly cache add   name: null,
24 silly cache add   rawSpec: 'jupyter-js-widgets',
24 silly cache add   spec: '/Users/poldrack/code/ipywidgets/jupyter-js-widgets',
24 silly cache add   type: 'directory' }
25 verbose addLocalDirectory /Users/poldrack/.npm/jupyter-js-widgets/0.0.14/package.tgz not in flight; packing
26 verbose correctMkdir /Users/poldrack/.npm correctMkdir not in flight; initializing
27 info lifecycle jupyter-js-widgets@0.0.14~prepublish: jupyter-js-widgets@0.0.14
28 verbose lifecycle jupyter-js-widgets@0.0.14~prepublish: unsafe-perm in lifecycle true
29 verbose lifecycle jupyter-js-widgets@0.0.14~prepublish: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/poldrack/code/ipywidgets/jupyter-js-widgets/node_modules/.bin:/Users/poldrack/anaconda/envs/py3k/bin:/Applications/fmri_progs/fsl/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Applications/fmri_progs/workbench/macosx64_apps/wb_command.app/Contents/MacOS:/Applications/fmri_progs/caret/bin_macosx64:/Applications/fmri_progs/antsbin/bin:/Applications/MATLAB_R2015a.app/bin
30 verbose lifecycle jupyter-js-widgets@0.0.14~prepublish: CWD: /Users/poldrack/code/ipywidgets/jupyter-js-widgets
31 silly lifecycle jupyter-js-widgets@0.0.14~prepublish: Args: [ '-c', 'npm run build' ]
32 silly lifecycle jupyter-js-widgets@0.0.14~prepublish: Returned: code: 1  signal: null
33 info lifecycle jupyter-js-widgets@0.0.14~prepublish: Failed to exec prepublish script
34 error addLocal Could not install /Users/poldrack/code/ipywidgets/jupyter-js-widgets
35 silly rollbackFailedOptional Starting
36 silly rollbackFailedOptional Finishing
37 silly runTopLevelLifecycles Starting
38 silly runTopLevelLifecycles Finishing
39 silly install printInstalled
40 verbose stack Error: jupyter-js-widgets@0.0.14 prepublish: `npm run build`
40 verbose stack Exit status 1
40 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
40 verbose stack     at emitTwo (events.js:100:13)
40 verbose stack     at EventEmitter.emit (events.js:185:7)
40 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
40 verbose stack     at emitTwo (events.js:100:13)
40 verbose stack     at ChildProcess.emit (events.js:185:7)
40 verbose stack     at maybeClose (internal/child_process.js:827:16)
40 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
41 verbose pkgid jupyter-js-widgets@0.0.14
42 verbose cwd /Users/poldrack/code/ipywidgets
43 error Darwin 15.3.0
44 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "jupyter-js-widgets"
45 error node v5.6.0
46 error npm  v3.6.0
47 error code ELIFECYCLE
48 error jupyter-js-widgets@0.0.14 prepublish: `npm run build`
48 error Exit status 1
49 error Failed at the jupyter-js-widgets@0.0.14 prepublish script 'npm run build'.
49 error Make sure you have the latest version of node.js and npm installed.
49 error If you do, this is most likely a problem with the jupyter-js-widgets package,
49 error not with npm itself.
49 error Tell the author that this fails on your system:
49 error     npm run build
49 error You can get information on how to open an issue for this project with:
49 error     npm bugs jupyter-js-widgets
49 error Or if that isn't available, you can get their info via:
49 error     npm owner ls jupyter-js-widgets
49 error There is likely additional logging output above.
50 verbose exit [ 1, true ]

**Comment by poldrack** [comment]
I should add that ipywidgets 4.1.1 works fine on the same machine when installed using conda.

**Comment by jdfreder** [comment]
Hi @poldrack , sorry that you are having this problem.

I have a couple of questions:
1) what version of npm and node are you using?

```
node -v
npm -v
```

2) If node is less than 5.3 or npm is less than 3.3, could you update them?

3) Another possibility is that the node_modules folder is screwed up.  You can rm -rf it and re-run `npm install`.

Looks like the build step is failing:

```
31 silly lifecycle jupyter-js-widgets@0.0.14~prepublish: Args: [ '-c', 'npm run build' ]
32 silly lifecycle jupyter-js-widgets@0.0.14~prepublish: Returned: code: 1 signal: null
33 info lifecycle jupyter-js-widgets@0.0.14~prepublish: Failed to exec prepublish script
```

**Comment by poldrack** [comment]
> On Feb 17, 2016, at 2:03 PM, Jonathan Frederic <notifications@github.com> wrote:
> 
> Hi @poldrack <https://github.com/poldrack> , sorry that you are having this problem.
> 
> I have a couple of questions:
> 1) what version of npm and node are you using?
> 
> node -v
> npm -v
poldrack$ node -v
v5.6.0
poldrack$ npm -v
3.6.0
> 2) If node is less than 5.3 or npm is less than 3.3, could you update them?
> 
> 3) Another possibility is that the node_modules folder is screwed up. You can rm -rf it and re-run npm install.
> 
I deleted the node_modules folder and reinstalled everything (including node and npm), and still have the same problem.  The first error that appears in the log is:

sh: rimraf: command not found

is that a clue?

**Comment by jdfreder** [comment]
Ah yeah, it's trying to do a dev install but it's not installing the devDependencies specified in the package.json.  This may be related to a bug I've found in npm, and have submitted an issue for.  Are you installing from the repo?>

**Comment by poldrack** [comment]
yes.  can I install those dependencies manually?

**Comment by jdfreder** [comment]
Well you shouldn't have to...  

from the repo root:

```
pip install -e .
cd jupyter-js-widgets
npm install
cd ../widgetsnbextension
npm run update:widgets
pip install -e .
```

This will A) build the Javascript B) Use the built Javascript with the nbextension C) Install that built Javascript and Python in a place Python can access it.

Later, when you want to make changes to jupyter-js-widgets, run this piece:

```
cd widgetsnbextension
npm run update:widgets
```

**Comment by poldrack** [comment]
that mostly seems to run, but I get the following errors in the npm update:widgets step, and it still fails with the "Widget Javascript not detected” error - here is the output:


npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! widgetsnbextension@0.0.1 build: `webpack`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the widgetsnbextension@0.0.1 build script 'webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the widgetsnbextension package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs widgetsnbextension
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls widgetsnbextension
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/poldrack/code/ipywidgets/widgetsnbextension/npm-debug.log

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "update:widgets"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! widgetsnbextension@0.0.1 update:widgets: `rimraf node_modules/jupyter-js-widgets; npm install file:../jupyter-js-widgets; npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the widgetsnbextension@0.0.1 update:widgets script 'rimraf node_modules/jupyter-js-widgets; npm install file:../jupyter-js-widgets; npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the widgetsnbextension package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf node_modules/jupyter-js-widgets; npm install file:../jupyter-js-widgets; npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs widgetsnbextension
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls widgetsnbextension
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/poldrack/code/ipywidgets/widgetsnbextension/npm-debug.log

**Comment by jdfreder** [comment]
Oops an additional `npm install ` is missing immediately prior to the npm run update command! ! Sorry

**Comment by poldrack** [comment]
ok - that worked, in the sense that the installation completed without errors.  however, when I try to run my notebook, I still get the error message “ [IPKernelApp] WARNING | Widget Javascript not detected.  It may not be installed properly.” and the widgets fail to appear.

below I am attaching the output from the javascript console - it appears that it still can’t see the ipywidgets package:

Default extension for cell metadata editing loaded.
main.min.js:24168 Raw Cell Format toolbar preset loaded.
main.min.js:24216 Slideshow extension for metadata editing loaded.
main.min.js:28971 actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...
http://localhost:8888/nbextensions/widgets/notebook/js/extension.js?v=20160218062137 Failed to load resource: the server responded with a status of 404 (Not Found)
main.min.js:33736 ipywidgets package not installed.  Widgets are not available.
main.min.js:23370 Session: kernel_created (eecc807c-0ccf-4253-8b2c-51980c59bb87)
main.min.js:22673 Starting WebSockets: ws://localhost:8888/api/kernels/fe72b3da-fc7c-455f-82aa-e6d0cea09bce
main.min.js:12109 Loading extension: livereveal/main
main.min.js:22329 Kernel: kernel_connected (fe72b3da-fc7c-455f-82aa-e6d0cea09bce)
main.min.js:22329 Kernel: kernel_ready (fe72b3da-fc7c-455f-82aa-e6d0cea09bce)
main.min.js:12842 Could not open comm  --  Error: Class jupyter.widget not found in registry (…)(anonymous function) @ main.min.js:12842
main.min.js:23119 Couldn't process kernel message WrappedError(anonymous function) @ main.min.js:23119
main.min.js:12842 Could not open comm  --  Error: Class jupyter.widget not found in registry (…)(anonymous function) @ main.min.js:12842
main.min.js:23119 Couldn't process kernel message WrappedError(anonymous function) @ main.min.js:23119
main.min.js:12842 Could not open comm  --  Error: Class jupyter.widget not found in registry (…)(anonymous function) @ main.min.js:12842
main.min.js:23119 Couldn't process kernel message WrappedError(anonymous function) @ main.min.js:23119
main.min.js:12842 Could not open comm  --  Error: Class jupyter.widget not found in registry (…)(anonymous function) @ main.min.js:12842
main.min.js:23119 Couldn't process kernel message WrappedError(anonymous function) @ main.min.js:23119
main.min.js:12842 Could not open comm  --  Error: Class jupyter.widget not found in registry (…)(anonymous function) @ main.min.js:12842
main.min.js:23119 Couldn't process kernel message WrappedError(anonymous function) @ main.min.js:23119
main.min.js:12842 Could not open comm  --  Error: Class jupyter.widget not found in registry (…)(anonymous function) @ main.min.js:12842
main.min.js:23119 Couldn't process kernel message WrappedError(anonymous function) @ main.min.js:23119
main.min.js:12842 Could not open comm  --  Error: Class jupyter.widget not found in registry (…)(anonymous function) @ main.min.js:12842
main.min.js:23119 Couldn't process kernel message WrappedError(anonymous function) @ main.min.js:23119
main.min.js:12842 Could not open comm  --  Error: Class jupyter.widget not found in registry (…)(anonymous function) @ main.min.js:12842
main.min.js:23119 Couldn't process kernel message WrappedError(anonymous function) @ main.min.js:23119
main.min.js:12842 Could not open comm  --  Error: Class jupyter.widget not found in registry (…)(anonymous function) @ main.min.js:12842
main.min.js:23119 Couldn't process kernel message WrappedError(anonymous function) @ main.min.js:23119
main.min.js:12842 Could not open comm  --  Error: Class jupyter.widget not found in registry (…)(anonymous function) @ main.min.js:12842
main.min.js:23119 Couldn't process kernel message WrappedError(anonymous function) @ main.min.js:23119
main.min.js:23119 Couldn't process kernel message WrappedError(anonymous function) @ main.min.js:23119
main.min.js:23119 Couldn't process kernel message WrappedError(anonymous function) @ main.min.js:23119

**Comment by rwblair** [comment]
I am seeing a similar issue as Poldrack's last comment. The installation appears to have worked, with extension.js being generated but on startup, even of example notebooks I am seeing a 404:

404 GET /nbextensions/widgets/notebook/js/extension.js (::1) 60.38ms referer=http://localhost:8888/notebooks/Widget%20Low%20Level.ipynb

The javascript file is appearing with the installed ipywidgets module:
/usr/local/lib/python2.7/site-packages/ipywidgets/static/notebook/js/extension.js

Is there any setting in ipywidget that would effect where extension.js is being looked for or being loaded from? Noticed a similar path at the top of ipywidgets/widgetsnbextension/src/extension.js but playing around with it did not seem to affect the 404 of errors.

**Comment by jdfreder** [comment]
Because you are running ipywidgets master, you also need to run notebook master which has been updated to load the ipywidgets Javascript from it's new location, ref: https://github.com/jupyter/notebook/pull/1022.

**Comment by jdfreder** [comment]
Let me know if I can close this issue if the above works for you...

**Comment by poldrack** [comment]
thanks - yes, that worked, you can close the issue.

> On Feb 22, 2016, at 12:37 PM, Jonathan Frederic <notifications@github.com> wrote:
> 
> Let me know if I can close this issue if the above works for you...
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/ipython/ipywidgets/issues/377#issuecomment-187372733>.
> 

—
Russell A. Poldrack
Professor of Psychology
Bldg. 420, Jordan Hall
Stanford University
Stanford, CA 94305

poldrack@stanford.edu
http://www.poldracklab.org/
