### ISSUE TITLE
Image() stretches PNG Display by default

### ISSUE THREAD

**Issue by benbini** [ipython/ipywidgets#379]
Jupyter environment:
```
{'commit_hash': '86d685f',
 'commit_source': 'installation',
 'default_encoding': 'utf-8',
 'ipython_path': '/usr/local/lib/python3.5/site-packages/IPython',
 'ipython_version': '4.1.1',
 'os_name': 'posix',
 'platform': 'Linux-3.2.0-4-amd64-x86_64-with-debian-7.9',
 'sys_executable': '/usr/local/bin/python3.5',
 'sys_platform': 'linux',
 'sys_version': '3.5.0 (default, Sep 19 2015, 14:56:18) \n[GCC 4.7.2]'}
```
Inline PNG images generated by `ipywidgets.Image()` as follows:
```
return Image(value=MyTree.create_png())   # MyTree is a pydot.Dot() object
```
Are stretched by default across the width of the browser window.  

![stretched](https://cloud.githubusercontent.com/assets/11338993/13164308/3358ab42-d682-11e5-95b4-12cb15017bb0.png)

There seems to be no way to specify "width=100%" to avoid this stretching; all width/height values are in absolute numbers of pixels.  

In order to obtain desirable visual effects:

![scaled](https://cloud.githubusercontent.com/assets/11338993/13164310/3571adf2-d682-11e5-9c4e-0a4d9a380d36.png)

It seems necessary to manually parse through the PNG data to find the appropriate dimensions:
```
P = parse_bytes()
# read the DWORD W/H values out of the raw PNG data
pngWidth,pngHeight = P.Parse(pngData[0x10:0x14],BigEndian=True),P.Parse(pngData[0x14:0x18],BigEndian=True)
return Image(value=pngData,width=pngWidth,height=pngHeight)
```
It would seem better for `Image()` to return by default the image scaled to its intrinsic dimensions, as opposed to stretched-out disasters, without having to add additional userland  code to parse the PNG data.

**Comment by minrk** [comment]
I can [reproduce this](http://nbviewer.jupyter.org/gist/minrk/f68bd7681666de28286e), but I don't see the CSS that would make the widgets Image stretch-to-fill when the regular display.Image shows up correctly. cc @jdfreder.

**Comment by jdfreder** [comment]
The problem is that the parent div, the widget subarea, is a flexible box model div.  Removing the flex property of it fixes the rending issue.

**Comment by jdfreder** [comment]
It seems there isn't CSS styling that will force the `img` tag to ignore the "flex" property of it's parent.  Instead the solution is to wrap the `img` tag in a `div` tag.  This is done like so:

```python
display(Box([Image(value=png)]))
```

Or in the context of @minrk 's notebook:

```python
display(ipywidgets.Box([ipywidgets.Image(value=png)]))
```

I'm unconvinced that it makes sense for the Image widget to be a div with an embedded image tag because that complicates other use cases and convolutes what an Image widget is.

**Comment by benbini** [comment]
alright. I'll follow the `display...` approach you suggest, thanks.  The manually-read-PNG-data approach was generating huge images when used against real data, so it didn't work too well either.
