### ISSUE TITLE
Large descriptions and readouts can have negative side effects on widget rendering.

### ISSUE THREAD

**Issue by jdfreder** [ipython/ipywidgets#380]
One option is to deprecate description and truncate readouts.

The other option is to adjust the rendering of description and readouts so everything plays nicely.

**Comment by jdfreder** [comment]
@ellisonbg looking at the code and after talking to @SylvainCorlay .  I think doing this right will take a lot of effort, more than what we want to do immediately prior to a release.  

Also instead of deprecating `description`, which a lot of users rely on, we should probably look at this as a refactor of of how the widget class structure is designed.  The views created for widgets should internally inherit from hbox create description and internal widget views that are children.  I don't think this needs to be reflected in Python.

The last item in the list we still need to do prior to release.  I'll move that to it's own issue.

**Comment by minrk** [comment]
I really enjoy the history of the title of this issue

**Comment by ellisonbg** [comment]
But isn't there a nasty bug with master right now - that if you have a long description, the slider shrinks to silly small sizes?

**Comment by jdfreder** [comment]
Yeah, with the outter div widgets you can do that with long descriptions.  One possible solution is to use something like this:

```css
    word-wrap: break-word;
    max-width: 100px;
```

We may want to thing more about what the max width should be.  We could do the same for the readout I think...

**Comment by jdfreder** [comment]
Here's what that looks like with a description max width of 100px and a readout max width of 50px:

![widgetsize](https://cloud.githubusercontent.com/assets/3292874/13272333/224f57fc-da50-11e5-9ac0-42889bbdf61e.jpeg)

**Comment by jdfreder** [comment]
Source code for the above:

```python
FloatSlider(description="testtttttttttttttttttttttttttttttttttttt", min=0., max=4., step=1./3.)
```
