### ISSUE TITLE
Update to new API in jupyter-js-services 0.5

### ISSUE THREAD

**Issue by jhpedemonte** [ipython/ipywidgets#381]
Need to update **services-shim.js** to the new API in *jupyter-js-services* v0.5.

In particular, `kernel.commOpened` has been removed. Instead, need to use `kernel.registerCommTarget()`.

I took a quick stab at updating, but it doesn't seem to be a simple update.

**Comment by jdfreder** [comment]
Is this closed by #382 ?

**Comment by jhpedemonte** [comment]
Yes.
