### ISSUE TITLE
Casting to str() required by widgets.Select()

### ISSUE THREAD

**Issue by arisolt** [ipython/ipywidgets#384]
The **options** argument of **widgets.Select()** only accepts a list of strings. If a list of integers is used, it returns: 

> TraitError: The 'selected_label' trait of a Select instance must be a unicode string, but a value of 0 <type 'int'> was specified.

**Comment by Carreau** [comment]
I think it is fair to not do too much magic for Select. Logically the right container to use for `Select` is a dictionary with keys being strings, and corresponding value to use, so that you can pass functions, or any other object. It's not that much code much of the time `{str(v):v for v in container}` and prevent many mistakes.

**Comment by jdfreder** [comment]
@arisolt do you have a use case where the solution provided by @Carreau does not work?  Or a reason to argue for the change?

**Comment by arisolt** [comment]
I was asked to add this ticket by one of the dev's in the Gitter room, actually

**Comment by jdfreder** [comment]
> I was asked to add this ticket by one of the dev's in the Gitter room, actually

Yes that was me, I wanted to be able to discuss it here

**Comment by arisolt** [comment]
I've been given some thought to @Carreau 's suggestion, and I think it makes sense. 

I think we are all on the same page. Basically my concern is that there is no straight-forward way in the current version to select from a custom list of integers (only from an automatically generated list with fixed increment). This is necessary for functions that can only take something like [1, 7, 92]. 

If `SelectionSlider` will be included in the next version, there probably isn't a reason to also alter the logic of `Select`.
