### ISSUE TITLE
Readout rounding errors can cause widget width issues.

### ISSUE THREAD

**Issue by jdfreder** [ipython/ipywidgets#385]
Round off error in readout should be truncated to X digits (to prevent shrinking).

Originally from #380

**Comment by jdfreder** [comment]
This seems to be a non-issue with master, cc @ellisonbg 

![rounding](https://cloud.githubusercontent.com/assets/3292874/13231939/93cbc8ba-d961-11e5-83cf-7f45ace004da.gif)

**Comment by ellisonbg** [comment]
Still a bit confused about this. If the outer div has a fixed width, how is it possible the that readout can occupy different widths and not have the slider change in width?

**Comment by jdfreder** [comment]
The slide will change in width, but the default truncation length of 5 digits seems sane.  I don't see how picking a different truncation length would help - i.e. if we pick 2 digits the user could still see the same resizing problem as the screenshot above by using the same interval * 1000.

Other possible behaviors:
- fixed width readout: Weird because the visual representation of the readout will be trucated.  IOW numbers like 9,999,999 may read to the user as 9,999.
- shrink the readout font size when the contents overflow

**Comment by jdfreder** [comment]
I've now consumed this issue in #380.
