### ISSUE TITLE
ipywidgets 5.0

### ISSUE THREAD

**Issue by jdfreder** [ipython/ipywidgets#390]
@minrk @Carreau ,

@SylvainCorlay and I are interested in releasing ipywidgets 5.0 sometime soon (days/weeks timescale).  However ipywidgets depends on https://github.com/jupyter/notebook/pull/1022 and the notebook is 4.2 release is held up by https://github.com/jupyter/notebook/pull/879 .  We can either bump https://github.com/jupyter/notebook/pull/879 to 4.3 or push forward with https://github.com/jupyter/notebook/pull/879 for 4.2.  I've been in contact with @damianavila about moving forward with https://github.com/jupyter/notebook/pull/879, and he has some work in a branch towards the TODO items summarized at the bottom of the PR.  

@damianavila what branch is your work in?  Is it pushed & up to date?  Would you like to hand that off to me so I can push forward with it today or tomorrow?

**Comment by ellisonbg** [comment]
It is really, really important to finish the nbextension stuff for 4.2. We
have essentially promised Continuum and @damianavila that. I know you
really want to get ipywidgets 5.0 out, but there are a bunch of other
things blocking on the nbextensions work as well. @damianavila can
@jdfreder take over on he nbextension stuff?

On Tue, Feb 23, 2016 at 10:51 AM, Jonathan Frederic <
notifications@github.com> wrote:

> @minrk <https://github.com/minrk> @Carreau <https://github.com/Carreau> ,
>
> @SylvainCorlay <https://github.com/SylvainCorlay> and I are interested in
> releasing ipywidgets 5.0 sometime soon (days/weeks timescale). However
> ipywidgets depends on jupyter/notebook#1022
> <https://github.com/jupyter/notebook/pull/1022> and the notebook is 4.2
> release is held up by jupyter/notebook#879
> <https://github.com/jupyter/notebook/pull/879> . We can either bump
> jupyter/notebook#879 <https://github.com/jupyter/notebook/pull/879> to
> 4.3 or push forward with jupyter/notebook#879
> <https://github.com/jupyter/notebook/pull/879> for 4.2. I've been in
> contact with @damianavila <https://github.com/damianavila> about moving
> forward with jupyter/notebook#879
> <https://github.com/jupyter/notebook/pull/879>, and he has some work in a
> branch towards the TODO items summarized at the bottom of the PR.
>
> @damianavila <https://github.com/damianavila> what branch is your work
> in? Is it pushed & up to date? Would you like to hand that off to me so I
> can push forward with it today or tomorrow?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/issues/390>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
Oh also, @jdfreder, what is the status of all the 5.0 todo items that we
discussed last week?

On Tue, Feb 23, 2016 at 4:42 PM, Brian Granger <ellisonbg@gmail.com> wrote:

> It is really, really important to finish the nbextension stuff for 4.2. We
> have essentially promised Continuum and @damianavila that. I know you
> really want to get ipywidgets 5.0 out, but there are a bunch of other
> things blocking on the nbextensions work as well. @damianavila can
> @jdfreder take over on he nbextension stuff?
>
> On Tue, Feb 23, 2016 at 10:51 AM, Jonathan Frederic <
> notifications@github.com> wrote:
>
>> @minrk <https://github.com/minrk> @Carreau <https://github.com/Carreau> ,
>>
>> @SylvainCorlay <https://github.com/SylvainCorlay> and I are interested
>> in releasing ipywidgets 5.0 sometime soon (days/weeks timescale). However
>> ipywidgets depends on jupyter/notebook#1022
>> <https://github.com/jupyter/notebook/pull/1022> and the notebook is 4.2
>> release is held up by jupyter/notebook#879
>> <https://github.com/jupyter/notebook/pull/879> . We can either bump
>> jupyter/notebook#879 <https://github.com/jupyter/notebook/pull/879> to
>> 4.3 or push forward with jupyter/notebook#879
>> <https://github.com/jupyter/notebook/pull/879> for 4.2. I've been in
>> contact with @damianavila <https://github.com/damianavila> about moving
>> forward with jupyter/notebook#879
>> <https://github.com/jupyter/notebook/pull/879>, and he has some work in
>> a branch towards the TODO items summarized at the bottom of the PR.
>>
>> @damianavila <https://github.com/damianavila> what branch is your work
>> in? Is it pushed & up to date? Would you like to hand that off to me so I
>> can push forward with it today or tomorrow?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ipython/ipywidgets/issues/390>.
>>
>
>
>
> --
> Brian E. Granger
> Associate Professor of Physics and Data Science
> Cal Poly State University, San Luis Obispo
> @ellisonbg on Twitter and GitHub
> bgranger@calpoly.edu and ellisonbg@gmail.com
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
> what is the status of all the 5.0 todo items that we
> discussed last week?

See #380 and #385

**Comment by ellisonbg** [comment]
k thanks, following there...

**Comment by SylvainCorlay** [comment]
What prevents a 4.2 and a 4.3?

**Comment by ellisonbg** [comment]
Nothing, I am sure there will be a 4.3 But the urgency of getting the
nbextension stuff released is high enough that it would be very unfair to
make people wait for an entire alpha/beta/testing release cycle to get 4.2
out and then 4.3 out. What is the urgency of getting 5.0 of ipywidgest out?
If there are fundamental problems with colliding release schedules, please
bring this up with the council though.

@fperez @minrk

On Tue, Feb 23, 2016 at 4:58 PM, Sylvain Corlay <notifications@github.com>
wrote:

> What prevents a 4.2 and a 4.3?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/issues/390#issuecomment-187993873>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by fperez** [comment]
Given how much work has already been put into the nbextensions material, and that we already asked @ellisonbg and other interested parties to wait post-4.1 for it (there was initially a bit of desire to sneak it into 4.1), I'd also suggest that it be given priority now for 4.2.  I know that lots of people are waiting/blocking on it.

I wish I had the cycles to help right now finish that work, but I'm about to disappear for two back-to-back conferences til next week.

So I feel guilty asking for work I can't help with. But right now, I think pushing  jupyter/notebook#879 so it's out as fast as possible seems like the best compromise to me...

**Comment by ellisonbg** [comment]
Just a thought - ipywidget 5.0 is a big enough release that it should have a pretty generous alpha/beta/testing/doc release cycle itself (~a few weeks). What about entering into that cycle in parallel with 4.2 of the notebook and then releasing at roughly the same time? That way, ipywidgets doesn't have to wait for 4.2 of the notebook to be fully released before it starts its own release process...

**Comment by jdfreder** [comment]
We could definitely push a alpha to PYPI... I'm unfamiliar with the behavior of pip regarding the following:  I'm an unsuspecting user trying to install the notebook and ipywidgets.  I pip install notebook then I pip install ipywidgets.  If ipywidgets 4.1.1 and 5.0.0-alpha both exist on PYPI, will pip install 4.1.1?  If so, then yes we could release an alpha now.

**Comment by SylvainCorlay** [comment]
> Just a thought - ipywidget 5.0 is a big enough release that it should have a pretty generous alpha/beta/testing/doc release cycle itself (~a few weeks). What about entering into that cycle in parallel with 4.2 of the notebook and then releasing at roughly the same time? That way, ipywidgets doesn't have to wait for 4.2 of the notebook to be fully released before it starts its own release process...

This sounds like a good idea.

**Comment by blink1073** [comment]
@jdfreder, unless they use the `--pre` flag, they will get the stable version.

**Comment by minrk** [comment]
I think focusing on the installation stuff for 4.2 first and *using it* for ipywidgets 5.0 makes the most sense to me. We can do an alpha of ipywidgets (is it three packages to release on two systems?) in the meantime.
