### ISSUE TITLE
Storing widgets in notebook output

### ISSUE THREAD

**Issue by aiguofer** [ipython/ipywidgets#404]
I'm not sure if this has been discussed before, but I couldn't find it. I read somewhere that widgets are persisted in browser storage, but that doesn't help this case. Maybe it's related to #16?

Anyway, I've noticed that when I create a notebook with widgets, if I share the notebook with someone they can see the output. This is great, especially when using `jupyter_dashboard`, but the problem is that if I want to incorporate widgets into a notebook, they would have to execute the whole notebook themselves. This makes it cumbersome when I want to share a dashboard with someone. Is there a way to make widgets persist in the output so other people have access to them?

**Comment by jdfreder** [comment]
Persist live widgets, no.  Persist static renderings of those widgets, yes.  In master, which will be released soon as ipywidgets 5.0, the widgets add a "widgets" menu which allows you to save the notebook w/ static renderings of the widgets.

**Comment by aiguofer** [comment]
Ahh I see, but the static rendering wouldn't be linked to the callback in that case then?
