### ISSUE TITLE
How to use the widgets from other language kernels?

### ISSUE THREAD

**Issue by minad** [ipython/ipywidgets#41]
Is this also part of jupyter? It should be very well possible to share the js part and only keep a small model and logic part on the kernel side.

**Comment by jdfreder** [comment]
It is.  At one point we were trying to decide whether or not to put the repository under the Jupyter org.  We decided to leave it here because of its Python content.  Other kernels have implemented the widget spec, IHaskel and IJulia to name two.  It's not well documented yet, but totally doable.

**Comment by minrk** [comment]
@minad the kernel-side and frontend-side will be split like the rest of ipython:jupyter when the interfaces between them (loading, widget messages, etc.) stabilize. Since those interfaces are *highly* unstable at this point, the Python-side and js-side are really a single active research project for now, from a practical standpoint. Other kernels can definitely use the JS provided with this package, but we are pretty far from any API stability promises.

**Comment by minad** [comment]
Ok, good. It would be great if the js/notebook side could be stabilized, documented and shared between the kernels.

But no hurry. It is already very good what you have already achieved with jupyter in terms of multi lang support and I really appreciate your work. I stalled further development of iruby up to that point where I felt that jupyter is ready enough and I think I guess we will just do the same concerning the widgets. It would still be great if you let me know if the widget thing starts to converge...

**Comment by minrk** [comment]
Yup, that's definitely the plan. Just not there yet.

**Comment by minad** [comment]
great :clap:

**Comment by lbustelo** [comment]
Where is the discussion of how IPy Widgets move forward in the language agnostic world of Jupyter? I would like to understand if there are plans or experimentation taking place.

**Comment by jdfreder** [comment]
@lbustelo there's not much planning to be done, it's just a matter of moving the files around.  However, we'd like to wait for the API to stabilize before splitting the repo.  Only time will tell when the API has stabilized.

**Comment by jasongrout** [comment]
For reference, we have now split the backend (ipywidgets) and frontend (jupyter-js-widgets). They still live in the same repo, but are completely separate packages. I think it's right to close this as fixed at this point.
