### ISSUE TITLE
web3 jupyter js widget example seems to fail.

### ISSUE THREAD

**Issue by michaelaye** [ipython/ipywidgets#410]
`web` and `web2` examples work fine, with `web3` I just see what is shown in attached screenshot.
<img width="1181" alt="screenshot 2016-03-08 16 33 56" src="https://cloud.githubusercontent.com/assets/69774/13620283/c000acd4-e54b-11e5-924e-11da444ac930.png">

**Comment by jdfreder** [comment]
This is definitely a bug.  The jupyter-js-services API may have changed under our feet.  I'll lock to a strict version in package.json, that should fix things.

**Comment by jdfreder** [comment]
In #414 I fix the version of jupyter-js-services, hopefully that does the trick....

**Comment by jdfreder** [comment]
I've confirmed #414 closes this.

**Comment by minrk** [comment]
Closed by #414
