### ISSUE TITLE
local nosetests failing after dev install

### ISSUE THREAD

**Issue by rmorshea** [ipython/ipywidgets#411]
I've followed the instructions in the readme file for a dev install, but the test suite fails to run complaining:

```
ImportError: No module named 'IPython'
```

inside: `ipython/ipywidgets/ipywidgets/__init__.py`

I've uninstalled `ipython/ipython` and reinstalled, but the issue still persists. Any idea what's gone wrong?

**Comment by jdfreder** [comment]
Hey Ryan, I think the version of python that ipython is getting installed to is different.   Also something may be stale in your python distribution. Try replacing `pip` with `python -m pip` , which will make sure the right python is being used.   You may need to manually remove the python packages files from python's packages folder on your machine

**Comment by jasongrout** [comment]
This seems to work on master. Please reopen if you are still having issues with this.
