### ISSUE TITLE
FloatText widgets overlap each other in HBox

### ISSUE THREAD

**Issue by moorepants** [ipython/ipywidgets#412]
See:
![selection_053](https://cloud.githubusercontent.com/assets/276007/13625390/38d87982-e56c-11e5-9cda-5aebfb3ceef8.png)

Is this expected behavior? If so is there an easy way to tweak it so that the descriptions don't overlap the input boxes?

**Comment by SylvainCorlay** [comment]
This is fixed in 5.x.
