### ISSUE TITLE
Trying to create a custom widget using example from this repo gives errors.

### ISSUE THREAD

**Issue by zsameem** [ipython/ipywidgets#416]
I am following the [Hello world example](https://github.com/ipython/ipywidgets/blob/4.0.2/examples/Custom%20Widget%20-%20Hello%20World.ipynb) to create a custom widget. The example does not run properly. In the console of the browser there is a 404 for a file called "jupyter-js-widgets.js". 
![screenshot from 2016-03-11 18 11 19](https://cloud.githubusercontent.com/assets/7116164/13702450/c10f376a-e7b4-11e5-8343-c90f3c56b203.png)
I am running jupiter in a virtual environment. I am using the following versions of packages
__ipywidgets              == 4.1.1__
jupyter                    == 1.0.0
jupyter-client          == 4.2.1
jupyter-console      == 4.1.1
jupyter-core           == 4.1.0

A similar issue was also reported [here](https://github.com/ipython/ipywidgets/issues/365). It said that the problem occurs by using non compatible versions of __ipywidgets__ and __jupiter notebook__. I think I am using compatible versions but still getting the same error.

**Comment by antmanler** [comment]
+1, cannot creating custom widgets

**Comment by jdfreder** [comment]
I talked to @zsameem in the mailing list, the problem was that he had ipywidgets 4.1 installed and was looking at the docs in master (5.0).  The appropriate docs are here: https://github.com/ipython/ipywidgets/tree/4.1.1/examples
