### ISSUE TITLE
Color trait type hexadecimal input

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#439]
The current `Color` trait type validates html colors strings.

The color trait type that was used in pythreejs took integers like 0x000000 too.

Should we extend the Color trait type to convert the corresponding integers to RGB strings?

**Comment by SylvainCorlay** [comment]
cc @jasongrout

**Comment by jasongrout** [comment]
Is that a yes or a no?

**Comment by jasongrout** [comment]
> Should we extend the Color trait type to convert the corresponding integers to RGB strings?

Is that a yes or a no?

**Comment by SylvainCorlay** [comment]
That is a no, given the high level of interest :)
