### ISSUE TITLE
6.x ToggleButtons behavior needs review.

### ISSUE THREAD

**Issue by afshin** [ipython/ipywidgets#452]
The `ToggleButtons` behavior needs some UX review. In the newly reimplemented 6.x version of `ToggleButtons`, when the set of toggles is instantiated, they all have the `button_style` they were given at instantiation. Immediately upon one of the toggles being activated, all buttons are reset to the default button style and the set of toggles works as expected. This behavior is loosely based on the earlier `5.x` behavior, but it seems without precedent in other widgets, so it may need some review.

cc: @ellisonbg @jasongrout @jdfreder @SylvainCorlay 

cf: https://github.com/ipython/ipywidgets/issues/223

**Comment by afshin** [comment]
FYI, there is a static instance of `ToggleButtons` in cell [7] of this page:

http://afshin.github.io/jupyter-js-bbwidget/

**Comment by SylvainCorlay** [comment]
Fixed in #645
