### ISSUE TITLE
Navigating with prev and next on the Widget List page 404s

### ISSUE THREAD

**Issue by willingc** [ipython/ipywidgets#456]
@jdfreder On the Widget List page generated from the notebook, the next, prev, and index links 404.

<img width="1215" alt="screen shot 2016-04-04 at 5 38 07 pm" src="https://cloud.githubusercontent.com/assets/2680980/14268175/dcc9866e-fa8c-11e5-93be-fce3921cac78.png">

Now that I'm thinking about it, part of this issue may be something that Peter and I saw as a Sphinx issue on kernel gateway. Let me double check that. Leaving issue as a reminder.

**Comment by willingc** [comment]
Meh. Wrong Sphinx issue, the one that I was remembering was [this Edit on GitHub issue with Markdown](https://github.com/jupyter/kernel_gateway/pull/127)

Looks like there is something in the theme that needs to be tweaked.

**Comment by jdfreder** [comment]
If we have the original file ext we can change the edit on github link accordingly.  I'm not sure that information is available to us, I'll have to look.

**Comment by willingc** [comment]
@jdfreder The GitHub edit is not a real issue since it is fixed in a later Sphinx.

What is the issue is the Next, Back breadcrumbs(?) that are causing a 404.

**Comment by gnestor** [comment]
We will be migrating away from this theme and resolving this (fingers crossed) in the process. Follow https://github.com/ipython/ipywidgets/issues/799 for updates...

**Comment by willingc** [comment]
@gnestor I think this can be closed.
