### ISSUE TITLE
Polyfill for Object.assign

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipywidgets#463]
We're starting to use Object.assign, which is not supported in IE 11. We should add a polyfill (IIRC, the widgets work in IE 11, so we shouldn't break it for something as simple as this).

A polyfill is at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill

**Comment by SylvainCorlay** [comment]
`_.extend` should do the trick. We are still using underscore.

**Comment by jasongrout** [comment]
Good point.

**Comment by jasongrout** [comment]
TODO: check for existence of Object.assign, and close if there are none.

**Comment by jasongrout** [comment]
Nope, no references to Object.assign
