### ISSUE TITLE
6.x dropdown widget doesn't scroll with page

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipywidgets#466]
Notice that scrolling the page when the dropdown is open shows the dropdown does not scroll with the page. Presumably this is from absolutely positioning the dropdown, rather than inserting it into the dom and relatively positioning it.

![dropdown-positioning](https://cloud.githubusercontent.com/assets/192614/14364520/49e75d7e-fcd7-11e5-8c28-87b89c6f3f12.gif)

CC @afshin

**Comment by SylvainCorlay** [comment]
Fixed in #524
