### ISSUE TITLE
SelectionSlider doesn't update as slide moves on 6.x branch

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipywidgets#467]
For some reason, the problem noted in #413 still is happening for me on the 6.x branch (4936b86a87804053eb3d719ff67b527e7f5beb4b): the SelectionSlider is not updating the value as the slider is dragged:

![selectionslider](https://cloud.githubusercontent.com/assets/192614/14366165/6c255bae-fcdf-11e5-8897-39058b850d8b.gif)

The code (https://github.com/ipython/ipywidgets/blob/4936b86a87804053eb3d719ff67b527e7f5beb4b/jupyter-js-widgets/src/widget_selection.js#L911) seems like it hooks up the `'slide'` event to the `handleSliderChange` function, but the `handleSliderChange` function seems like it only gets invoked when the mouse button is released, not as the slide happens. It seems like the exact same code hooks up the IntSlider events up to a corresponding handler, and things work for the IntSlider.

**Comment by gnestor** [comment]
@jasongrout I tested on master and SelectionSlider only updates on mouseup when `continuous_update=True` and updates on drag when `continuous_update=False`, which is the opposite of what is expected.

![screenshot](http://g.recordit.co/whn6MFPlgt.gif)

**Comment by jasongrout** [comment]
Now on master, it always updates, even when `continuous_update=False`

**Comment by jasongrout** [comment]
Actually, never mind. It works great on master - the readout updates as you drag the slider always, but the value isn't synced until you let off the slider if you have `continuous_update=False`

![selectionslider](https://cloud.githubusercontent.com/assets/192614/20217793/5c13d414-a7d6-11e6-995d-22223ecb8aa6.gif)
