### ISSUE TITLE
get_state and set_state are not symmetrical

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#47]
Since 09d58f28e31bd37a18f64dfe7e24d0c0116a7b1a, `Widget.get_state` returns a tuple.
`(state, buffer_keys, buffers)` while `Widget.set_state` only takes the first `sync_data` dictonary.

@jasongrout

**Comment by jdfreder** [comment]
+1 for making this symmetrical, like the names suggest.

**Comment by SylvainCorlay** [comment]
Fixed in #48
