### ISSUE TITLE
Dependency on window.require

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#471]
`jupyter-js-widgets` depends on require.

 - [ ] make requirejs a true npm dependency of jupyter-js-widgets
 - [ ] have the webpacked `embed.js` put it on the page.
 - [ ] exclude it in the nbextension webpack (as an external thing) since it is already on the page with notebook.

**Comment by blink1073** [comment]
I would say leave it external and document the fact that it is needed as a script tag or global.

**Comment by blink1073** [comment]
cf https://github.com/jupyter/jupyter-js-utils/issues/29 https://github.com/webpack/webpack/issues/1986

**Comment by SylvainCorlay** [comment]
We probably want it to be part of the `embed.js` though...

**Comment by jdfreder** [comment]
@SylvainCorlay no I don't think so, I think it should be the document's responsibility to load require.js.

**Comment by SylvainCorlay** [comment]
We explicitly call `window.require` in `jupyter-js-widgets` so it is a dependency of the module.

We may have a webpack rule that excludes it in the case of the notebook, but for the embed widgets thing, we need to add it on the page.
