### ISSUE TITLE
Label widget not rendering math

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipywidgets#486]
For me, on the current notebook 4.x branch, running the label widget example in the Widget List example notebook yields: "[Math processing error]", and right-clicking and showing the mathjax error shows "Error: this.CHTMLcreateNode is not a function"

**Comment by SylvainCorlay** [comment]
@jasongrout I cannot reproduce. Should I close this?

**Comment by jasongrout** [comment]
I'm pretty sure we fixed this a while ago. I can look at the PRs to get the reference, but I think it's fine to close now.

**Comment by minrk** [comment]
I saw this last week, I'll double-check versions of everything. Could be broken in 5.0, fixed in 5.1.

**Comment by jasongrout** [comment]
I think this was fixed in https://github.com/ipython/ipywidgets/pull/560.

**Comment by minrk** [comment]
Perfect, thanks @jasongrout!
