### ISSUE TITLE
npmcdn + semver

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#489]
npmcdn supports semver. 

You can request  
 - `https://npmcdn.com/requirejs@~2.1.0` 

and you get 

- `https://npmcdn.com/requirejs@2.1.22`

Same with the other ways to define semver ranges. Should we use that `~` operator in our embedable code snippet so that we get the latest backward compatible code?

The user would have a manager compatible with his state plus bug fixes.

**Comment by SylvainCorlay** [comment]
Another question is how to define a common pattern for looking on npmcdn for custom widget models.

for example, for bqplot it would be `https://npmcdn.com/bqplot/dist/index.js`... If we agree on a standard one like this for npmcdn custom models, we can go pretty far to embed custom widgets.

**Comment by SylvainCorlay** [comment]
cc @ellisonbg

**Comment by SylvainCorlay** [comment]
cc @blink1073

**Comment by blink1073** [comment]
Sounds reasonable to me, :+1:

**Comment by bollwyvl** [comment]
Sounds very cool!

I'd like to advocate for making sure that someone can change the CDN stem at rendering time, either by specifying it directly into the widget creation process, or as a switch on something aware in nbconvert, though that would take more work. A gnarly old `data-ipywidgets-static-root` attribute on the body or something might even be appropriate.

### Use case
if i have generated a notebook in-house that uses embedded widgets, but don't want t always be hitting the CDN, I'd want a way to signal to use a different prefixed location, and probably do a one-time static build there. Or run my own npmcdn. Or whatever.

This would probably then recommend just storing the URI fragment, perhaps taking a page from JSON-LD, so naively:

```js
{
     'bqplot' : 'npm:bqplot#/dist/embed.js',
     'jupyter-threejs' : 'npm:jupyter-threejs#/dist/embed.js'
} 
```

Eventually, one could imagine having a local, caching version of this shipped with lab...

**Comment by minrk** [comment]
Is the standard you are talking about the path within npm, e.g. `https://npmcdn.com/{name}/dist/jupyter-widgets.js`?

I think this seems like a great idea, I'm just not quite sure what we need to decide / do to get it going.

**Comment by SylvainCorlay** [comment]
> Is the standard you are talking about the path within npm, e.g. https://npmcdn.com/{name}/dist/jupyter-widgets.js?
> I think this seems like a great idea, I'm just not quite sure what we need to decide / do to get it going. 

That is it for now, yes. The version for the custom thing should be stored in the model state too at some point so that we can get the versioned cdn.

**Comment by SylvainCorlay** [comment]
> Sounds very cool!

> I'd like to advocate for making sure that someone can change the CDN stem at rendering time, either by specifying it directly into the widget creation process, or as a switch on something aware in nbconvert, though that would take more work. A gnarly old data-ipywidgets-static-root attribute on the body or something might even be appropriate.

The only thing that would make custom widgets point to npmcdn is the version of `jupyter-js-widgets` webpacked and made available on npmcdn, so it is consistent.

It would be easy to make another version pointing elsewhere.

**Comment by SylvainCorlay** [comment]
So the fallback mapping `'foobar' -> 'https://npmcdn.com/foobar/dist/embed.js'` seems to be the last thing to do to get a first version of embeddable custom widgets. Although it seems that it will require to have an indirection for `window.require` in `loadClass`.
