### ISSUE TITLE
widgets.Text don't show on deployed dashboard

### ISSUE THREAD

**Issue by shroomba** [ipython/ipywidgets#500]
I wanted to create a dashboard in Jupyter and the only input I needed was text widget:
inputT = widgets.Text("date")
display(inputT)

When I deployed the dashboard, the widget wasn't there. After digging through the source of the html page, my colleague and I found the issue.
Text widget has "input" class, the same class that all python cells have, which hides all cells, so they don't appear on the dashboard.
We found a way around it, but it would still be nice not having to do this everytime :)
Here is the work around:
After displaying the widget, we remove "input" class from all "widget-text".
display(Javascript("$('.widget-text').removeClass('input')"))

**Comment by jdfreder** [comment]
Thanks, this is definitely a bug, fixing now...

**Comment by jdfreder** [comment]
I'm looking into it still, but I think this may be because that's the bootstrap class name for styled text inputs.  In which case, the bug actually is in the dashboard library you are using.  Instead of hiding `.input` it should hide `.cell .input`.

**Comment by jdfreder** [comment]
Nope, turns out it was not needed, #503 should fix
