### ISSUE TITLE
Widgets won't display occasionally in notebook

### ISSUE THREAD

**Issue by Ethanleet** [ipython/ipywidgets#519]
I'm new to iPython Notebook, so I could hardly figure out the problem on my own.

I was using some widgets before and they worked fine, until suddenly they are gone from my notebook. I tried to reduce my code to only displaying a single IntSlider but it still doesn't work. Here's my code.
![screen shot 2016-04-17 at 3 39 02 am](https://cloud.githubusercontent.com/assets/10285603/14586473/fb3e2f4e-044d-11e6-8034-3f630781d7d5.png)
I went into this problem several times. However, if I use the same code in a new notebook, it works again.

**Comment by SylvainCorlay** [comment]
@Ethanleet thanks for reporting. I would need some more information to help you:
 - what version of ipywidgets you are using. (`import ipywidgets; ipywidgets.__version__`)
 - what web browser are you using, and which version.
 - do you see any error in the console of your web browser (on Crtl + Shift + J to see the console on chrome)

**Comment by Ethanleet** [comment]
@SylvainCorlay My ipywidgets version is 4.1.1. Running on Safari 9.1. The error has gone after I restarted my notebook. I'll update with my console output when I'm able to reproduce the problem.

**Comment by Ethanleet** [comment]
@SylvainCorlay I reproduced the issue. Here's the console log.
![screen shot 2016-04-17 at 1 17 05 pm](https://cloud.githubusercontent.com/assets/10285603/14589758/b432d0f4-049e-11e6-8ead-0999e09371e9.png)

![screen shot 2016-04-17 at 1 13 23 pm](https://cloud.githubusercontent.com/assets/10285603/14589739/4dfdb1dc-049e-11e6-961c-2357d830cd19.png)
There are still bunch of same errors occurring after this, but I've included all logs and warnings. Thanks!

**Comment by SylvainCorlay** [comment]
Thanks @ethanleet. I should also have asked for the version of the notebook
you are running. Did this appear after you updated the notebook package?

**Comment by Ethanleet** [comment]
@SylvainCorlay I'm running 4.1.2. No I didn't update the notebook package, but I did update ipywidgets yesterday, after I saw a similar issue posted a few days ago.

**Comment by crwilcox** [comment]
@SylvainCorlay I am having the same issue.

Browser: Chrome, IE, Edge

Python 3.4 (Anaconda3 version 2.3.0 Linux-x86_64)
IPyWidgets: 4.1.1
jupyter_core: 4.0.2
jupyter_client: 4.2.2

The code cell executes but there is no displayed output.

I am using an old version of Anaconda, but Jupyter is up to date. Perhaps this is related also? https://github.com/ipython/ipywidgets/issues/569

**Comment by SylvainCorlay** [comment]
This should be fixed since notebook 4.2.1.
