### ISSUE TITLE
Design problems with slider in 5.0

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipywidgets#526]
* Slider is too narrow if there is any description
* Formatting problems with the readout

<img width="763" alt="screen shot 2016-04-20 at 11 49 33 pm" src="https://cloud.githubusercontent.com/assets/27600/14700321/9318204c-0753-11e6-9dbf-ddae7b2c0214.png">

**Comment by ellisonbg** [comment]
* When a slider is moved, all of the code in subsequent cells jitters up and down.
* The range slider handles jitter horizontally when you move them at all.

@fperez

**Comment by SylvainCorlay** [comment]
Fixed in #548.
