### ISSUE TITLE
Drop down has inconsistent width

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipywidgets#527]
The width of the drop down items should match the width of the actual dropdown widget itself.

<img width="431" alt="screen shot 2016-04-20 at 11 49 46 pm" src="https://cloud.githubusercontent.com/assets/27600/14700333/a8509138-0753-11e6-913d-7d28bfbacb5e.png">

**Comment by afshin** [comment]
FYI, the 6.x dropdown does not have this issue, but it is an entirely different widget, so it isn't back-portable.

**Comment by jasongrout** [comment]
This is fixed now in master.
