### ISSUE TITLE
interact_manual: way to make <enter> press the button

### ISSUE THREAD

**Issue by JanSchulz** [ipython/ipywidgets#53]
I've a lookup widget, which is implemented as a function with a single string argument:

```
def table_by_name(name=""):
    if name == "":
        display(HTML("<strong>Nothing to do</strong>"))
    else:
        # do some pandas merging and dicing, which results in `df`...
        display(HTML(df._repr_html_()))
interact_manual(table_by_name)
```

It would be nice if there would be some way to specify that pressing enter in the input box will trigger the button.

**Comment by akimd** [comment]
+1

**Comment by jdfreder** [comment]
It's not 100% clear to me what the right behavior is here.  My initial thoughts are that any input box, when used with interact manual, should submit on return.
