### ISSUE TITLE
jupyter.widget.version open call should only take place when the kernel is Python

### ISSUE THREAD

**Issue by lbustelo** [ipython/ipywidgets#531]
The version check does not seem to cause any issues, but it does print an error message on the js console. Maybe this check should look at the kernel.info and be performed only for Python kernels.

Something along the lines of this https://github.com/jupyter-incubator/declarativewidgets/blob/7659d9def805b4f7066abeedb3225c09ac153522/elements/urth-viz-ipywidget/urth-viz-ipywidget.html#L104

**Comment by SylvainCorlay** [comment]
I think that it is ok to have an error in the js console. We don't prevent other kernels to implement the check!

**Comment by lbustelo** [comment]
@SylvainCorlay true... maybe reduce it to a warning?

**Comment by SylvainCorlay** [comment]
Good point! 👍 for a warning instead of an error.
