### ISSUE TITLE
Potential timing problem when using `new_widget` in jupyter-js-widgets and widgetsnbextension

### ISSUE THREAD

**Issue by lbustelo** [ipython/ipywidgets#534]
This problem is not isolated to the 5.0.0 release, it is possible is older versions of the code. This issues is exposed in declarativewidgets when running on a Scala or R kernel. Basically any kernel that by default does not support the comm target_name.

Background:

For the R and Scala support of declarativewidgets, we build a library that basically adds a handler to the ipywidgets comm target_name. To add the library and the handler the user must basically have a couple of code cells that need to be executed at the top of the notebook. 

In declarativewidgets, we currently start trying to connect with the kernel from the moment the kernel is ready. We have code in our browser side elements to retry connection with the kernel for a certain number of execute_request calls until they succeed in creating a WidgetModel that is connected to its kernel side instance.

Problem:

We use the following code to create our WidgetModel and open a comm connection with the kernel side of the widget.

``` javascript
widget_manager.new_widget(
                    {
                        model_module: 'jupyter-decl-widgets/DeclWidgetModel',
                        model_name: 'DeclWidgetModel',
                        widget_class: this.kernelClass
                    }
                ).then(function(model) {
                        ...
                        model.on('change', this.__modelChangeCallback);
                        model.once('comm:close', this.__commCloseCallback);
                        ...
                    }.bind(this),
                    function(error){
                        console.error(error);
                    }
                );
```

There is a timing issue that a comm close might have already taken place before the promise with the `model` is resolved. Our `__commCloseCallback` never gets called, so our browser element/widget thinks everything is fine (but it's not!)

Solution:

On our side, we put a [safeguard in the Promise callback](https://github.com/jupyter-incubator/declarativewidgets/pull/322/files) to check the `model`'s comm and see if it is still registered in the CommManager. If it is not, we error out.

``` javascript
if(!model.comm.kernel.comm_manager.comms[model.comm.comm_id]){
   this._handleCommDisconnect();
   return;
}
```

I think that this might be better handled as part of manager-base.js. Maybe it should check the state of the comm [here](https://github.com/ipython/ipywidgets/blob/master/jupyter-js-widgets/src/manager-base.js#L170) before it continues on to create a model and reject the promise.

**Comment by SylvainCorlay** [comment]
I think that this issue also occurs with the custom widgets in combination with the web3 example.

**Comment by SylvainCorlay** [comment]
I can confirm that this is fixed as of master.
