### ISSUE TITLE
Dropdown widget view does not update with new options.

### ISSUE THREAD

**Issue by drafter250** [ipython/ipywidgets#536]
I am not sure if this is a bug or not as I am just getting into ipywidgets. After initial creation of a dropdown widget if you  assign a new set of options the view does not update.
so if I do:
```python
import ipywidgets as ipw
opts = ['one','two','three']
dpdown = ipw.Dropdown(description='selector', options=opts)
display(dpdown)
opts.append('four')
dpdown.options = opts
display(dpdown)
```
I Thought that I would see view update with the 'four' option added but it doesn't. I check the options attribute and it does show the 'four' added to the list.

"Update":
I am on version 4.1.1,
Linux
IE 11 over server.

so I ran the same example code on my local windows version of Anaconda that has ipywidgets 4.1.0 and setting new options does indeed update the _options_dict, _options_values, _options_labels attributes in the Dropdown widget thus the view updates as well. However in 4.1.1 they do not.

I don't see any changes in widget_selection.py between 4.1.1 and 4.1.0

Ultimatley I am trying to keep the options available in the Dropdown synced with a dictionary.

**Comment by justinmc** [comment]
This works for me in 5.2.2.  My exact commands:

    from IPython.display import display
    import ipywidgets as ipw
    opts = ['one','two','three']
    dpdown = ipw.Dropdown(description='selector', options=opts)
    display(dpdown)

This shows the dropdown with 3 options.  Then in the next cell:

    opts.append('four')
    dpdown.options = opts

The original dropdown now updates to show 4 options.

Should be ok to close this issue?

By the way, if you're looking to sync the options in the dropdown with a dictionary, look at the [traitlets](https://github.com/ipython/traitlets) library, mainly `traitlets.link`.

**Comment by SylvainCorlay** [comment]
What @justinmc said ^

Just adding that you can get ipywidgets 5.x by typing 

```
conda install -c conda-forge ipywidgets
```

You can also check ipywidgets.jslink for a link on the javascript side.

**Comment by gnestor** [comment]
@drafter250 Is this issue resolved after upgrading to ipywidgets 5.x?

**Comment by drafter250** [comment]
Yes sorry i believe it is.

**Comment by BenjaPH** [comment]
I have the same problem with a recent update of anaconda,
anaconda 5.0.0
jupyter notebook 5.0.0
ipywidgets 7.0.0

The code is,

```
# widget Dropdown
import ipywidgets as widgets
from IPython.display import display

OptDict={'XXX':0,'YYY':1}
wDd2=widgets.Dropdown(options=OptDict,value=0,disabled=False)
print(wDd2, id(wDd2),"\n")

with wDd2.hold_trait_notifications():
    OptDict['ZZZ']=9
    wDd2.options=OptDict
    wDd2.value=1
print(wDd2.options, id(wDd2.options))
print(wDd2._options_labels, wDd2._options_values)

display(wDd2)

```
and the output is,
```
Dropdown(options={'XXX': 0, 'YYY': 1}, value=0) 2205788730032 

{'ZZZ': 9, 'XXX': 0, 'YYY': 1} 2205789360520
('XXX', 'YYY') (0, 1)
```

It seems that the Dropdown widgets atributes (_options_labels, _options_values) are not updated with the assigment of wDd2.options=OptDict.
Are there any other instructions that force the updating of this attributes? or it is possible to synchronize automatically with any changes of the variable 'OptDict' assigned at the beginning?
