### ISSUE TITLE
Keep backwards-compatible module name

### ISSUE THREAD

**Issue by ricklupton** [ipython/ipywidgets#543]
To make my custom widget package work with Notebook 4.2 and the updated ipywidgets, I have to change `widgets/js/widget` to `jupyter-js-widgets` ([diff](https://github.com/ricklupton/ipysankeywidget/commit/a5f0322387a78d8fcbd440cf9a5ff7e98174296d?diff=unified#diff-a0fbe5d402bbca32327bfd8dfb1f445e)).

Having done this my widget no longer works with older versions of jupyter. Would it be possible to add `widgets/js/widget` as a depreciated alias for `jupyter-js-widgets` to ease the transition?

**Comment by SylvainCorlay** [comment]
Sorry for the late reply.
`jupyter-js-widgets` is the name of the npm package. Since we are moving towards npm for everything, I think that it makes more sense to not try to alias the earlier package name of 4.x.
