### ISSUE TITLE
jupyter-js-widgets will not build with node v6.0.0

### ISSUE THREAD

**Issue by afshin** [ipython/ipywidgets#547]
There is an issue with the Less compiler: https://github.com/less/less.js/issues/2881 that causes it to fail silently on node v6.0.0, thus breaking `npm install` in `jupyter-js-widgets`. Before it is resolved by the Less developers, we should at least be aware that it may cause issues for users who have upgraded to the latest version of `node`.

cc: @jdfreder @SylvainCorlay @jasongrout

**Comment by sccolbert** [comment]
cc: @ellisonbg @fperez

**Comment by SylvainCorlay** [comment]
Thanks for the heads up.

**Comment by fperez** [comment]
Ouch, I do have node 6.0.0, since that's what homebrew is shipping ATM. Is there any workaround we can use?

**Comment by fperez** [comment]
In fact, I'm getting a "wrong JS version" error:

![image](https://cloud.githubusercontent.com/assets/57394/14978753/eff36ad2-10d2-11e6-91bb-30859f851d10.png)

while running from master, and I'm now wondering if this is my problem...

**Comment by minrk** [comment]
@fperez you can install specific node versions [with nvm](https://github.com/creationix/nvm):

```bash
# install
brew install nvm
# in bashrc:
export NVM_DIR="$HOME/.nvm"
. "$(brew --prefix nvm)/nvm.sh"

# install node 5 (once)
nvm install 5
# use node 5 (in shell, bashrc, whenever):
nvm use 5
