### ISSUE TITLE
ImportError: cannot import name _get_nbext_dir

### ISSUE THREAD

**Issue by denfromufa** [ipython/ipywidgets#558]
```
[ NotebookApp] server_extensions is deprecated, use nbserver_exten
sions
c:\python\python27_32b\lib\site-packages\widgetsnbextension\__init__.py:30: User
Warning: To use the jupyter-js-widgets nbextension, you'll need to update
    the Jupyter notebook to version 4.2 or later.
  the Jupyter notebook to version 4.2 or later.""")
[W 16:54:29.007 NotebookApp] Error loading server extension nbextensions
    Traceback (most recent call last):
      File "c:\python\python27_32b\lib\site-packages\notebook\notebookapp.py", l
ine 1042, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "c:\python\python27_32b\lib\importlib\__init__.py", line 37, in impor
t_module
        __import__(name)
      File "C:\Users\denis.akhiyarov\AppData\Roaming\jupyter\extensions\nbextens
ions.py", line 8, in <module>
        from notebook.nbextensions import _get_nbext_dir as get_nbext_dir
    ImportError: cannot import name _get_nbext_dir
```

```
>pip install -U notebook
Requirement already up-to-date: notebook in c:\python\python27_32b\lib\site-pack
ages
Requirement already up-to-date: traitlets in c:\python\python27_32b\lib\site-pac
kages (from notebook)
Requirement already up-to-date: tornado>=4 in c:\python\python27_32b\lib\site-pa
ckages (from notebook)
Requirement already up-to-date: jupyter-client in c:\python\python27_32b\lib\sit
e-packages (from notebook)
Requirement already up-to-date: nbformat in c:\python\python27_32b\lib\site-pack
ages (from notebook)
Requirement already up-to-date: jupyter-core in c:\python\python27_32b\lib\site-
packages (from notebook)
Requirement already up-to-date: nbconvert in c:\python\python27_32b\lib\site-pac
kages (from notebook)
Requirement already up-to-date: ipykernel in c:\python\python27_32b\lib\site-pac
kages (from notebook)
Requirement already up-to-date: ipython-genutils in c:\python\python27_32b\lib\s
ite-packages (from notebook)
Requirement already up-to-date: jinja2 in c:\python\python27_32b\lib\site-packag
es (from notebook)
Requirement already up-to-date: pygments in c:\python\python27_32b\lib\site-pack
ages (from nbconvert->notebook)
Requirement already up-to-date: mistune!=0.6 in c:\python\python27_32b\lib\site-
packages (from nbconvert->notebook)
Requirement already up-to-date: entrypoints in c:\python\python27_32b\lib\site-p
ackages (from nbconvert->notebook)
Requirement already up-to-date: MarkupSafe in c:\python\python27_32b\lib\site-pa
ckages (from jinja2->notebook)
Requirement already up-to-date: configparser in c:\python\python27_32b\lib\site-
packages (from entrypoints->nbconvert->notebook)
```

**Comment by denfromufa** [comment]
related:

https://github.com/ipython-contrib/IPython-notebook-extensions/issues/591

**Comment by jdfreder** [comment]
You're right in trying to update your notebook, 

```
User
Warning: To use the jupyter-js-widgets nbextension, you'll need to update
    the Jupyter notebook to version 4.2 or later.
```

The error you're seeing is actually in the notebook code.  Specifically the nbextensions.py file, which is not a part of the widgets.

I have a hunch the version of the notebook that is being launched is not the one pip has "upgraded".

**Comment by denfromufa** [comment]
@jdfreder looks like you are pointing fingers at each other with @jcb91  :)

https://github.com/ipython-contrib/IPython-notebook-extensions/issues/591#issuecomment-216716721

**Comment by jcb91** [comment]
Haha :stuck_out_tongue_closed_eyes: :point_right: @jdfreder 

So, as explained in https://github.com/ipython-contrib/IPython-notebook-extensions/issues/591#issuecomment-214259578, there are two separate warnings about two separate things here. As detailed there, the second warning 

> `[W 16:54:29.007 NotebookApp] Error loading server extension nbextensions`

comes not from the `nbextensions.py` that @jdfreder refers to above, but from a completely different file confusingly also called `nbextensions.py`, which _is_ the domain of the [ipython-contrib repository](https://github.com/ipython-contrib/IPython-notebook-extensions/), and is dealt with in https://github.com/ipython-contrib/IPython-notebook-extensions/issues/591, so I'll ignore that here.

The first warning I think does belong here though, since I don't think that it's the `nbextensions.py` file that's causing it. As I mentioned in https://github.com/ipython-contrib/IPython-notebook-extensions/issues/591#issuecomment-214259578

>  `User Warning: To use the jupyter-js-widgets nbextension, you'll need to update the Jupyter notebook to version 4.2 or later.`

appears in this repo, in the `find_static_assets` function at [`widgetsnbextension/widgetsnbextension/__init__.py#L29-L30`](https://github.com/ipython/ipywidgets/blob/be7cd6290abd743e748e86b2642723046961b9e3/widgetsnbextension/widgetsnbextension/__init__.py#L29-L30), and notebook 4.2.0 still calls `find_static_assets` at [`notebook/notebookapp.py#L242`](https://github.com/jupyter/notebook/blob/4.2.0/notebook/notebookapp.py#L242)

phew, that was a lot of text...

**Comment by gnestor** [comment]
@denfromufa Is this issue resolved after upgrading notebook?

**Comment by denfromufa** [comment]
I found alternative solution, but let me check on this one again.

**Comment by denfromufa** [comment]
@gnestor just checked, not having any issues!

alabaster (0.7.7)
anaconda-build (1.15.0)
anaconda-client (1.4.0)
anaconda-navigator (1.1.0)
argcomplete (1.0.0)
astropy (1.2.1)
autopxd (1.1.1)
Babel (2.2.0)
backports-abc (0.4)
backports.shutil-get-terminal-size (1.0.0)
backports.ssl-match-hostname (3.4.0.2)
beautifulsoup4 (4.4.1)
bitarray (0.8.1)
blaze (0.9.0)
bokeh (0.11.1)
boto (2.39.0)
cdecimal (2.3)
certifi (2016.9.26)
cffi (1.5.2)
chest (0.2.3)
click (6.6)
cloudpickle (0.1.1)
clrmagic (0.0.1a2)
clyent (1.2.1)
colorama (0.3.7)
comtypes (1.1.2)
conda (4.2.9)
conda-build (1.21.0)
conda-manager (0.3.1)
configobj (5.0.6)
configparser (3.5.0)
cryptography (1.3)
cycler (0.10.0)
Cython (0.24)
cytoolz (0.7.5)
dask (0.8.1)
datashape (0.5.0)
decorator (4.0.10)
dill (0.2.4)
docopt (0.6.2)
docutils (0.12)
dulwich (0.13.0)
entrypoints (0.2.2)
enum34 (1.1.6)
et-xmlfile (1.0.1)
fastcache (1.0.2)
fileupload (0.1.3.dev1)
Flask (0.10.1)
Flask-Cors (2.1.2)
funcsigs (0.4)
functools32 (3.2.3.post2)
futures (3.0.3)
gevent (1.1.0)
greenlet (0.4.9)
grin (1.2.1)
h5py (2.6.0)
haxor (0.3.1)
haxor-news (0.4.1)
HeapDict (1.0.0)
idna (2.0)
ipaddress (1.0.14)
ipykernel (4.5.0)
ipython (5.1.0)
ipython-genutils (0.1.0)
ipywidgets (5.2.2)
itsdangerous (0.24)
jdcal (1.2)
jedi (0.9.0)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (4.1.1)
jupyter-contrib-core (0.3.0)
jupyter-contrib-nbextensions (0.2.0)
jupyter-core (4.2.0)
jupyter-kernel-gateway (0.5.1)
jupyter-nbextensions-configurator (0.2.2)
Keras (1.0.7)
llvmlite (0.12.1)
llvmpy (0.12.1)
locket (0.2.0)
lxml (3.6.0)
MarkupSafe (0.23)
matplotlib (1.5.1)
menuinst (1.3.2)
meta (development)
mistune (0.7.3)
mpmath (0.19)
multipledispatch (0.4.8)
nbconvert (4.2.0)
nbformat (4.1.0)
networkx (1.11)
nltk (3.2)
nose (1.3.7)
notebook (4.2.3)
numba (0.27.0+0.g6ca78ce.dirty)
numexpr (2.6.1)
numpy (1.11.1)
odo (0.4.2)
openpyxl (2.3.2)
pandas (0.18.1)
partd (0.3.2)
path.py (0.0.0)
pathlib2 (2.1.0)
patsy (0.4.1)
pep8 (1.7.0)
pickleshare (0.7.4)
Pillow (3.1.1)
pip (8.1.1)
ply (3.8)
prompt-toolkit (1.0.7)
psutil (4.1.0)
ptipython (1.0.0)
ptpython (0.34)
py (1.4.31)
py-earth (0.1.0)
pyasn1 (0.1.9)
PyAutoGUI (0.9.33)
pycosat (0.6.1)
pycparser (2.14)
pycrypto (2.6.1)
pyflakes (1.1.0)
Pygments (2.1.3)
pyHook (1.5.1)
pyhooked (0.8.0)
PyInstaller (3.1.1)
pymongo (3.3.0)
PyMsgBox (1.0.3)
pymssql (2.1.2)
pyodbc (3.0.10)
pyOpenSSL (0.15.1)
pyparsing (2.0.3)
pyreadline (2.1)
pyrfa (7.6.2)
PyScreeze (0.1.8)
PySide (1.1.2)
pytest (2.8.5)
Python-contrib-nbextensions (alpha)
python-dateutil (2.4.1)
pythonnet (2.2.0.dev1)
PyTweening (1.0.3)
pytz (2016.2)
pyvim (0.0.18)
pywin32 (220)
PyYAML (3.12)
pyzmq (15.4.0)
QtAwesome (0.3.2)
qtconsole (4.2.0)
QtPy (1.0)
requests (2.4.3)
rope (0.9.4)
ruamel-yaml (-VERSION)
scandir (1.2)
scikit-image (0.12.3)
scikit-learn (0.17.1)
scipy (0.18.0)
seaborn (0.7.0)
setuptools (28.2.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
snowballstemmer (1.2.1)
sockjs-tornado (1.0.1)
sphinx (1.3.5)
sphinx-gallery (0.1.2)
sphinx-rtd-theme (0.1.9)
spyder (2.3.8)
SQLAlchemy (1.0.12)
statsmodels (0.6.1)
sympy (1.0)
tables (3.2.2)
Theano (0.9.0.dev2)
toolz (0.7.4)
tornado (4.4.2)
traitlets (4.3.1)
tzlocal (1.2.2)
uncertainties (3.0.1)
unicodecsv (0.14.1)
vanity (2.2.2)
wcwidth (0.1.7)
Werkzeug (0.11.4)
wheel (0.29.0)
widgetsnbextension (1.2.6)
win-unicode-console (0.5)
xdress (0.5.dev0)
xlrd (0.9.4)
XlsxWriter (0.8.4)
xlwings (0.7.2)
xlwt (1.0.0)
yolk (0.4.3)
