### ISSUE TITLE
Random JavaScript test failures

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#56]
As discussed with @jdfreder, I sometimes see that one of the two js test suites that is failing. A simple restart generally solves it. 
I have not observed it when running it locally, but it is probably not related to the Travis env.

**Comment by jdfreder** [comment]
Are you seeing anything more than the critical "Phantom has crashed" error?  I see that one sometimes, and I'm quite puzzled about its origin.

**Comment by SylvainCorlay** [comment]
`FAIL "function () { return _this._page_loaded(); }" did not evaluate to something truthy in 10000ms`

**Comment by jdfreder** [comment]
Hm it seems the notebook server isn't starting in that case.

**Comment by SylvainCorlay** [comment]
- ok, just a note. This crash was due to the Travis caching issues that were solved recently.

I also observed the *Phantom has crashed* issue from time to time.

**Comment by SylvainCorlay** [comment]
Another one.
```
FAIL ".CodeMirror-code" still did not exist in 10000ms
#    type: uncaughtError
#    file: /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/ipywidgets/tests/bin/tests/widget_button.js
#    error: ".CodeMirror-code" still did not exist in 10000ms
#    stack: not provided
```

**Comment by jdfreder** [comment]
I think we can close this, now that we have the new karma tests.  Now, believe it or not, the Python tests seem to have more random failures!  The npm install inside the pip install seems to be touchy on Travis...
