### ISSUE TITLE
Dropdown behavior in ipywidgets 6.x

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipywidgets#562]
@afshin wrote a custom dropdown widget so we can have nice styling. I looked into how various dropdown widgets work in different platforms for corner cases. In the following cases, the 'list box' is the list box that pops up when clicking on the control that displays the options to select. 

At this stage, I don't have any suggestions for improved dropdown behavior, but just wanted to record observations of various behavior.

On Chrome on OS X 10.10, a `<select>` widget has the following behavior (see https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/ControlswithMenus.html)

![dropdown](https://cloud.githubusercontent.com/assets/192614/15023003/61b91124-11fc-11e6-9067-049841d2529c.gif)

1. the list box is essentially a popup menu which is modal and covers the dropdown control so that the selected item is over the control. The height is the minimum of the screen height (i.e., larger than the browser window) and the natural height of the list box, and the ends have arrows indicating whether there is more content above or below the displayed content.
2. The widget takes over scrolling when the list box is displayed, and scrolling changes the selection while keeping the list box open *if* the list box is bigger than the screen. Scrolling *doesn't* affect the page. Scrolling also doesn't do anything if the list box is open and is shorter than the screen height.
3. For normal cases, the width of the list box seems to be the minimum of the dropdown control width and the width needed to fit the content of the list box, up to a maximum of about 172 characters. After a list entry is about 6309 characters, though, the entry seems to be ignored in the width calculation (e.g., it fits the second longest entry). 
4. By default, the list box left edge lines up with the dropdown box left edge. However, the list box is adjusted left or right so that the entire list box displays on the screen, even if it means that the list box left edge does not align with the dropdown control left edge.

For Chrome on Windows 7, I see:

1. The list box is a dropdown below the control with a fixed height of 20 items.
2. You can scroll inside the dropdown list. Moving your mouse outside the list box and scrolling the page causes the list box to disappear with no change in selection.
3. The width is the minimum of the dropdown control width and the content width.
4. The list box left edge is always the drop down box left edge, even if the content width goes off the edge of the physical screen - the list box also just goes off the edge of the screen and you don't see the scrollbars at the left edge)
4. Putting thousands of characters in an `<option>` *really* slows down the control so that selects lags the mouse movement *really* bad and the list box also takes maybe a second to display.
`

**Comment by jasongrout** [comment]
I do think there is precedence here for making the list box width minimum be the control width, but not necessarily have the max width be the dropdown size. However, both in OS X and Windows, the list box did not wrap content, while we do, so perhaps having the list box be exactly the dropdown width is okay for us.

**Comment by afshin** [comment]
Thanks for doing the research on the user experience of dropdown menus, this is valuable stuff.

I don't think we necessarily need to follow the behavior of the native `select`, exactly. For example, our keyboard control behavior is slightly different:

```
index = index < items.length - 1 ? index + 1 : 0;
```

If you keep hitting the down arrow, our dropdown will loop back to the top, but the native one will stay at the bottom.

Similarly, we can decide what to do on scroll events (right now we just collapse) in a way that a `select` tag will not allow.

I think there could be a case made in both directions re: drop list width, so I'm curious what others think.

**Comment by blink1073** [comment]
I would argue that the browser implementations of dropdowns leave a lot to be desired and should not be used as a model.

**Comment by jasongrout** [comment]
@afshin - I think wrapping keydown event selection is confusing, and would rather have it stop at the bottom. Also, collapsing on scroll outside the select is exactly what I saw on Windows, but I also agree that it's nice that we can decide what to do. That's why I looked into what is done elsewhere.

@blink1073 - the `<select>` controls are OS-level controls (configured by the browser), if I understand correctly, not browser-specific implementations. I agree they leave a lot to be desired (especially Windows!), but I would also say that using them as a model (1) helps us understand user expectations, and (2) provides good input into what presumably has been battle-tested over a number of years.

**Comment by afshin** [comment]
@jasongrout fair enough re: cycling through options. I like that behavior, personally, but I'm not wedded to it.

**Comment by jasongrout** [comment]
The reason I like it to stop is that I use keyboard repeat to get to the bottom of a list quickly via keyboard. Cycling breaks that, since it's very easy to go over the end. It's similar to why we don't make our computer screens a torus (i.e., wrap around like pacman) - now, you can throw your mouse to the edge and then adjust a bit. Once the edge is gone, though, you have to aim a lot more carefully.

**Comment by afshin** [comment]
@jasongrout That's reasonable. Should I remove that behavior or should we keep it for the time being?

**Comment by jasongrout** [comment]
Can you remove the keydown cycling behavior? I think that also makes things more predictable for users.

**Comment by afshin** [comment]
@jasongrout Sure, sounds good.

**Comment by jasongrout** [comment]
Thanks!

**Comment by sccolbert** [comment]
As a data point: menus cycle on key press on Windows, but not on OSX. I've copied the windows behavior for the Menu widget.

**Comment by jasongrout** [comment]
Another data point: I just checked the `<select>` tag in Chrome, and on both OS X and Windows, it doesn't cycle on key press, but the selection stops at the extreme element.

**Comment by afshin** [comment]
One feature I think we should strongly consider is item matching + selection based on the user typing the first character of the item. The native implementation of this is not always consistent, I have encountered variations. For example, my current version of OS X (El Capitan) running Chrome 50 does this:

1. The initial `keydown` that has a character value matches the closest alphabetical match.
2. Subsequent `keydown`s that happen quickly enough to be typing a phrase *add* to the value of the string being sought alphabetically.
3. After a sufficient pause, the search item clears and another `keydown` will start from a blank search state.

I'm not sure what the exact times in milliseconds are for those shifts in behavior.

**Comment by jasongrout** [comment]
Good point. I've always been slightly frustrated with the semantics for this (I was never quite sure what would happen). Your algorithm makes sense. I see this is as less important than a console at this point, but perhaps we create an issue and if you have time, do it?
