### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by marqh** [ipython/ipywidgets#565]
Hi ipywidgets

I'm having an issue with Output, I wonder if you could help?

code:

```
import ipywidgets as widgets
from IPython.display import display
out = widgets.Output()
container = widgets.Box(children=[out])
container.layout.border = '3px red dotted'
display(container)
print('prints to output area')
with out:
    print('prints to output widget')
print(widgets.__version__)
```

results in 

```
<red bordered no height box>

prints to output area
prints to output widget
5.1.3
```

So, the output widget is not being printed to

this example is in the source doc string:
https://github.com/ipython/ipywidgets/blob/master/ipywidgets/widgets/widget_output.py#L25

many thanks
mark

**Comment by marqh** [comment]
any clues on this issue would be really appreciated.

for example, is it repeatable, do you get the same behaviour as I have observed?

thank you

**Comment by aggFTW** [comment]
I see the same thing, executing this:

```
import ipywidgets as widgets
from IPython.display import display
out = widgets.Output()
display(out)

print('prints to output area widget version: {}'.format(widgets.__version__))

with out:
    print('prints to output widget')
    display('prints to output widget')
```

I get both strings in output area, while the output of the `display` call simply disappears:
![capture](https://cloud.githubusercontent.com/assets/654204/15735240/dd13f4d2-284b-11e6-8fda-4e0457906add.PNG)

My notebook version:
```
The version of the notebook server is 4.2.0 and is running on:
Python 2.7.11 |Anaconda 2.3.0 (64-bit)| (default, Feb 16 2016, 09:58:36) [MSC v.1500 64 bit (AMD64)]
```

Executing:
```
import ipywidgets as w
print(w.__version__)
import notebook as nb
print(nb.__version__)
import widgetsnbextension as wne
print(wne.__version__)
```

I get:
```
5.1.5
4.2.0
1.2.3
```

No errors in the console...

Any ideas?

**Comment by aggFTW** [comment]
cc @ellisonbg @jasongrout @SylvainCorlay

**Comment by ankostis** [comment]
I'm also having the some problems for `notebook-4.2.1` in *Windows*, Output-widget does not intercepting any message, while the output of the `display ()` disappearing:
![image](https://cloud.githubusercontent.com/assets/501585/16539600/4ebce3aa-4048-11e6-859b-f048dadd16b3.png)

```
> pip list|grep -E "ipy|notebook|widge|jupyter"
ipykernel (4.3.1)
ipython (4.2.0)
ipywidgets (5.1.5)
jupyter (1.0.0)
jupyter-client (4.3.0)
jupyter-console (4.1.1)
jupyter-core (4.1.0)
notebook (4.2.1)
widgetsnbextension (1.2.3)
```

I get the same behavior with a `ipython-5.x`:
```
>pip list|grep -E "ipy|notebook|widge|jupyt"
ipykernel (4.3.1)
ipython (5.0.0b3)
ipython-sql (0.3.7.1)
ipywidgets (5.1.5)
jupyter (1.0.0)
jupyter-client (4.3.0)
jupyter-console (5.0.0b1)
jupyter-core (4.1.0)
notebook (4.2.1)
widgetsnbextension (1.2.3)
```

Any help?

**Comment by aggFTW** [comment]
Ping? :)

**Comment by minrk** [comment]
@jasongrout @SylvainCorlay any idea why display_data messages would not be captured by the output widget?

**Comment by mihaiparaschiv** [comment]
I had the same issue with the following versions:
```
import ipywidgets as w
print(w.__version__)
import notebook as nb
print(nb.__version__)
import widgetsnbextension as wne
print(wne.__version__)
```

```
5.2.2
4.2.1
1.2.6
```

The following code seems to work:

```
import ipywidgets as widgets
import sys
from traitlets import Unicode, List
from IPython.display import clear_output
from jupyter_client.session import Message
from IPython import get_ipython


class Output(widgets.Output):
    
    def __enter__(self):
        """Called upon entering output widget context manager."""
        self._flush()
        kernel = get_ipython().kernel
        session = kernel.session
        send = session.send
        self._original_send = send
        self._session = session

        def send_hook(stream, msg_or_type, content=None, parent=None, ident=None,
             buffers=None, track=False, header=None, metadata=None):

            # Handle both prebuild messages and unbuilt messages.
            if isinstance(msg_or_type, (Message, dict)):
                msg_type = msg_or_type['msg_type']
                msg = dict(msg_or_type)
            else:
                msg_type = msg_or_type
                msg = session.msg(msg_type, content=content, parent=parent,
                    header=header, metadata=metadata)
            
            # If this is a message type that we want to forward, forward it.
            if (stream is kernel.iopub_socket or stream.background_socket is kernel.iopub_socket) \
                and msg_type in ['clear_output', 'stream', 'display_data']:
                self.send(msg)
            else:
                send(stream, msg, ident=ident, buffers=buffers, track=track)

        session.send = send_hook
```

The problem looks to be the type of stream object.

The current condition (in 5.2.2) is:
```
if stream is kernel.iopub_socket and msg_type in ['clear_output', 'stream', 'display_data']:
```

I changed it to:
```
if (stream is kernel.iopub_socket or stream.background_socket is kernel.iopub_socket) \
    and msg_type in ['clear_output', 'stream', 'display_data']:
```

The current master version uses a different updating mechanism. Thus, I do not know if this would be an issue for future releases.

**Comment by jdemeyer** [comment]
I also don't get `Output` to work (using latest master of `ipywidgets`). Running the code from the original poster:

![output](https://cloud.githubusercontent.com/assets/3625785/18639030/a45d686a-7e92-11e6-836c-5a6b4fc4a4fc.png)

**Comment by RobinL** [comment]
Just to note that I'm having the same issue on:
ipywidgets                5.2.2                    py27_0 
jupyter v4.2.0
on Mac

And you also get the same if you use :
https://tmpnb.org/

I'm running the example code from the docstring:

    import ipywidgets as widgets
    from IPython.display import display  
    out = widgets.Output()
    display(out)

    print('prints to output area')

    with out:
         print('prints to output widget')

**Comment by rgbkrk** [comment]
Is there a way to invoke / show a single output as a mimebundle rather than using a context manager? I ask because I want to be able to use multiple threads rather than the management around the ipython parent IDs.

**Comment by jasongrout** [comment]
> Is there a way to invoke / show a single output as a mimebundle rather than using a context manager? I ask because I want to be able to use multiple threads rather than the management around the ipython parent IDs.

Great question. With ipywidgets 7.0, you can just append mimebundles (well, really display messages) directly to the output widget: 

```python
out = ipywidgets.Output()
out
```

```python
with out:
    print('hi')
out.outputs = out.outputs + ({'name': 'stdout', 'output_type': 'stream', 'text': 'hi\n'},)
```

**Comment by jasongrout** [comment]
@rgbkrk, I didn't see your question above until now. Here's a belated reply (directly above this).
