### ISSUE TITLE
Dropdown selection and key behavior

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipywidgets#567]
I'm experimenting more with the dropdown in master. Here are a couple of points:

1. When an option is selected, then the dropdown is opened, the current value should be selected. This also makes sure that keyboard up/down events start from the currently selected item instead of the top/bottom.
4. Any time the selected value in the list box is set (either on open or on keyup/keydown), the new selected value should be visible in the list box. We see this problem on keyup/keydown (when using the keyboard to select an option, when the selected option goes out of the visible area, the list box doesn't scroll to make the selected option visible.)

CC @afshin - can you look at these? Thanks!

**Comment by afshin** [comment]
Sure thing.
