### ISSUE TITLE
Latest release (5.1.3) doesn't work with Jupyter 4.2.0 (latest release)

### ISSUE THREAD

**Issue by ViralBShah** [ipython/ipywidgets#573]
When I open a notebook, I get this warning in the console:

```
loaded widgets
manager.js:115 Could not cross validate the widget frontend and backend versions. Error: Timeout while trying to cross validate the widget frontend and backend versions.(…)
```

Subsequently, creating a widget fails

```
utils.js:785 Could not open comm  --  Error: Class ipython.widget not found in registry
```

I installed the packages with Conda (IJulia automatically installs jupyter 4.2.0, then I did `Conda.add("ipywidgets")`)

How do I go about fixing this?

**Comment by shashi** [comment]
Looks like this callback which would suppress the warning is never called.. https://github.com/ipython/ipywidgets/blob/4142fc074dc63032be7b0fd84dfe5570e70dd546/jupyter-js-widgets/src/manager-base.js#L195-L202

When is it supposed to be? It looks like IJulia hasn't yet implemented `comm_info_request` and related message types, is this causing the problem? (it looks to me though as though the kernel throws the error after the warning is thrown in the browser)

**Comment by SylvainCorlay** [comment]
In any case, the warning regarding the frontend / backend version validation should not be an issue.

Are you using a Julia backend for the Jupyter interactive widgets?

**Comment by shashi** [comment]
Yeah, [Interact.jl](https://github.com/JuliaLang/Interact.jl)

**Comment by shashi** [comment]
I found this: https://github.com/ipython/ipywidgets/wiki/ipywidgets-5.0-Release-Document

Will try to fix up things

**Comment by SylvainCorlay** [comment]
Closing. We addressed these issues in the two hangouts with @shashi and @ViralBShah .
