### ISSUE TITLE
Can events be forward to the parent widget?

### ISSUE THREAD

**Issue by izaid** [ipython/ipywidgets#580]
I've been working a lot with ipywidgets in the last few weeks and I'm very impressed by how well everything is working. I've just got a question about how to properly communicate between two sibling widgets when events occur.

Suppose I have some parent widget with two children. I'd like to do something with child 1 if some value in child 2 changes. What is the "proper" to notify child 1 in this case?

For instance, in frameworks like Qt, I can forward events up to the parent. Can I do something similar here?

Relatedly, I'm finding that the `.parent` attribute is often `None` for my widgets. Is this supposed to be the case? Perhaps `.parent` doesn't mean what I think it does?

**Comment by SylvainCorlay** [comment]
The same widget *model* could be a child of many widgets models (e.g. displayed in multiple layouts). In other words, parent-child relationship is multiple in widget models.

However it is not the case for views: a widget view has a notion of parent widget view (in `this.options.parent`). Hence a widget view can trigger something in the model of its parent view...

**Comment by izaid** [comment]
Okay, I think this clears things up a bit. I still not totally sure as to how to send events between one widget and another (or if that is something one should even do), but thanks.
