### ISSUE TITLE
Aligning widgets

### ISSUE THREAD

**Issue by jbednar** [ipython/ipywidgets#589]
According to https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Styling.html

> Most widgets have a description attribute, which allows a label for the widget to be defined. The label of the widget has a fixed minimum width. The text of the label is always right aligned and the widget is left aligned:
> If a label is longer than the minimum width, the widget is shifted to the right:

How can I change the minimum width?  My widgets have descriptions with various lengths, and I can't get any of them to line up!

**Comment by jbednar** [comment]
Here's an example of the output we currently get when stacking a bunch of ipywidgets in a VBox:

![image](https://cloud.githubusercontent.com/assets/1695496/15363933/cf931fae-1d1a-11e6-99a7-273059a25ee4.png)

or a Box:

![image](https://cloud.githubusercontent.com/assets/1695496/15364004/07ec1090-1d1b-11e6-8d76-39e96733fb6e.png)

From the documentation, I can't figure out what options there are for aligning either the descriptions, the left edge of the widget, or the right edge of the widget, and for the results to look at all sensible we'd want to align all three of those values.  From the code, I can see lots of different settings, but nothing that I can see how to change...

**Comment by SylvainCorlay** [comment]
@jbednar which version of ipywidgets are you using?

**Comment by SylvainCorlay** [comment]
The situation should be better with ipywidgets 5.x, which you can install with

`conda install -c conda-forge ipywidgets`

**Comment by jbednar** [comment]
ipywidgets 4.1.1, the latest available on the main anaconda channel.  I'll try the conda-forge version.

**Comment by SylvainCorlay** [comment]
You should get `5.1.4`.

**Comment by jbednar** [comment]
Thanks for the suggestion!  After 

```
conda install -c conda-forge ipywidgets
jupyter nbextension enable --py --sys-prefix widgetsnbextension
```
and restarting the notebook server, I get ipywidgets 5.1.4 and the following output (after disabling selection boxes, which seemed to have changed syntax or requirements):

![image](https://cloud.githubusercontent.com/assets/1695496/15364449/ea9f3fa6-1d1c-11e6-8b99-b29f9980adf2.png)

I guess that's an improvement. :-)  But I still have the same problem: How can I increase the description width, which is woefully short?  Breaking it across lines like that isn't something I'd want to happen except for extremely long names.  How can I make the various widgets (sliders, different types of text boxes, etc.) be the same width?  How can I make a boolean's label show up on the same side of the widget as for all the other widgets, so that it lines up the same?  Is there a magic web page or even code file somewhere that explains all this? :-)

**Comment by SylvainCorlay** [comment]
At the moment, you cannot change the description width from a Python API. 

However, you can add a css class to the widget and inject css through the %%css magic.

**Comment by jbednar** [comment]
Thanks! Is there a web page or notebook with an example of how to do that?

**Comment by SylvainCorlay** [comment]
This is not something we really support because it is exposing the DOM structure of the widget, which we don't want to make part of the API.

Regarding layouts, I recommend you take a look at the FlexBox Layout example notebook.

**Comment by jbednar** [comment]
I had previously run across the FlexBox eample and tried to run it, but thought that it required a development version because it wouldn't work with my 4.x installation.  I'll try again with 5.x!

I don't want to mess with CSS either, but I would think that widget widths are something that many users will need to control, from Python.

**Comment by jbednar** [comment]
BTW, I'll ask for ipywidgets to be updated on the main conda channel, which should happen quickly because I'm at Continuum using it for a Continuum-sponsored project. :-)  Thanks for releasing such a fabulous package for everyone to use!

**Comment by SylvainCorlay** [comment]
👍 thanks @jbednar

**Comment by jbednar** [comment]
Unless there's any chance a release is imminent that would add control over the description width, in which case I'd hold off on updating the main conda channel until the release is ready?

**Comment by SylvainCorlay** [comment]
I don't think there is any reason to hold off. We are making releases all the time since 5.x, and it should not be an issue for anaconda folks to bump version numbers.

**Comment by jbednar** [comment]
Ok, request submitted.

**Comment by jbednar** [comment]
Just to update, after fixing a problem with the traitlets version, dropdowns work again, so I can show what all the widgets look like now:

![image](https://cloud.githubusercontent.com/assets/1695496/15377605/2cd9cbc6-1d5d-11e6-90f3-9553d59d0859.png)

As you can see, the dropdowns have yet another width and a different left edge, making the property sheet display like this be even more jumbled.

**Comment by jbednar** [comment]
I also tried all the options in `Flexbox Layout.ipynb`, but all I managed to achieve was drawing a box around the entire set of widgets or to try to cram them on one line; I couldn't see any way to affect how the description field is formatted or how to change the widths of any of the widgets.

**Comment by jbednar** [comment]
Correction: I can make the widths *worse*, I just can't improve them. :-)  If I pass`width=20%` to all of the widgets, the FloatText widget gets cropped off at a narrow width, and if I pass  `width=10px` so does the SelectMultiple widget.  But I can't make any of them stretch to match the larger size of the other widgets, nor can I reduce the size of the larger ones to match, only reduce the size of already small ones.  Surely I'm missing something obvious about how to control all this?

**Comment by SylvainCorlay** [comment]
@jbednar I meant that instead of using the description you can use `Label` widgets and lay them out with the FlexBox widgets.

**Comment by jbednar** [comment]
Ah, I'll try that, thanks!

**Comment by jbednar** [comment]
Well, that does improve things somewhat.  I couldn't get the Label widget to enforce a minimum width to make anything line up, but I was able to use an HTML widget with a fixed width:

![image](https://cloud.githubusercontent.com/assets/1695496/15437160/d3f6ab0e-1ec5-11e6-8a17-8c3040eac419.png)

So this takes care of lining up the descriptions, and it also puts the checkbox on the same side of its label as all the other widgets do.  However, SelectMultiple is still formatted incorrectly -- why is it offset slightly to the right?  It just always is, and I can't see how to affect that in any way.  Plus it might be nice to make the FloatText widget match the others in length, but I can't see how to stretch it out.

**Comment by SylvainCorlay** [comment]
I just fixed the offset to the right, it will be in the next minor release.

I am preparing a better example notebook on widget styling and layout to
settle all of this.

FYI there ia a readout_format attribute for the slider. You may be
interested in this.

**Comment by jbednar** [comment]
Thanks for the fix!  I think this will be usable for our purposes now, though it's definitely tricky to figure out how to format anything.  Hopefully the notebook will help enlighten us. :-)  I wasn't able to use readout_format to eliminate the strange gap after the slider, but maybe there's a way...
