### ISSUE TITLE
Minor bootstrap-less css issues

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#604]
- The blue border on the new Button widget behaves oddly. (You have to take the pointer out of the button to see it).
- The default gray color for the new widgets (dropdown, button etc) looks different from before. Should we reproduce the old style used for ipywidgets 5.x?

**Comment by SylvainCorlay** [comment]
cc @afshin

**Comment by jasongrout** [comment]
@ellisonbg - this seems to stem from code you added, specifically https://github.com/ipython/ipywidgets/commit/1ab64318b0fa9aba3bd7c4d0710417a9278f22b7#diff-e3a114e453e310b722bb71f53a0f4ad4R203. To reproduce the first problem above, construct a button, click it, then hover the mouse on and off the button.

![button](https://cloud.githubusercontent.com/assets/192614/15838549/ad53db80-2c0c-11e6-873c-b25485f43f89.gif)
