### ISSUE TITLE
it seems "restart Kernel and clear all output doesn't" remove ipywidgets

### ISSUE THREAD

**Issue by stonebig** [ipython/ipywidgets#607]
ipywidgets 5.1.4 / firefox / windows
![ipywidgets_resiliance](https://cloud.githubusercontent.com/assets/4312421/15483762/b9d9265c-2136-11e6-8127-cf1ab308df3d.PNG)

**Comment by SylvainCorlay** [comment]
Indeed it does not. I agree that it should probably erase the widgets.

**Comment by SylvainCorlay** [comment]
wow I responded to that 15 seconds after it was opened.

**Comment by SylvainCorlay** [comment]
Closing as duplicated to #637
