### ISSUE TITLE
empty string should be a valid dropdown selection

### ISSUE THREAD

**Issue by AaronWatters** [ipython/ipywidgets#612]
When I create a drop down with the empty string as an option I get an error when I attempt to select that option.  I think I've also seen the error at the time the dropdown is created also:

```
import ipywidgets
dd = ipywidgets.Dropdown(description="",
            options=["", "solid", "dotted", "dashed"], value="solid")
dd
```

![screen shot 2016-05-25 at 4 09 45 pm](https://cloud.githubusercontent.com/assets/13857252/15554707/7ed25f70-2293-11e6-8bc1-305ca876896d.png)

**Comment by jasongrout** [comment]
Thanks for reporting this. It seems to work well now in master:

![empty](https://cloud.githubusercontent.com/assets/192614/20217867/ce4ad01e-a7d6-11e6-826c-84eb9d2234e4.gif)
