### ISSUE TITLE
how to switch from ipywidgets 4.x to 5.x?

### ISSUE THREAD

**Issue by hainm** [ipython/ipywidgets#618]
Hi,

Can you please update the instruction (or show me the link) how to switch from ipywidgets 4.x to 5.x
We have this [nglview](https://github.com/arose/nglview) work nicely with 4.x version but my widget is not displayed with 5.x version.

I don't think `jupyter nbextension enable --py widgetsnbextension` is enough to make the widget works at all. I kept getting errors from console log (Chrome)

<img width="587" alt="screen shot 2016-05-30 at 11 46 29 pm" src="https://cloud.githubusercontent.com/assets/4451957/15662668/149174fc-26c1-11e6-8cb5-8aee2bf0f92e.png">

The errors are so silent in Python side and this makes our debugging is super difficult, especially I myself is not good at JS at all.

PS: I already this [https://github.com/ipython/ipywidgets/wiki/ipywidgets-5.0-Release-Document]

thanks

**Comment by SylvainCorlay** [comment]
Hi @hainm thanks for posting. nglview looks awesome. Congrats on the work there!

ipywidgets 5.x is indeed backward incompatible with 4.x. However, things should be much more stable from now on. 

Once you complete the migration, we should be able to include your visualization in static webpages such as the online are building for the jupyter.org website https://github.com/jupyter/jupyter.github.io/pull/93

There is a bit of work to do the migration but it is not so hard. A good place to start is probably to use the [widget-cookiecutter](https://github.com/jupyter/widget-cookiecutter/tree/master/%7B%7Bcookiecutter.github_project_name%7D%7D) project to generate a new nglview widget, to create a base project with the right project structure and boilerplate, and migrate your source to it... It also generates all the logic to build and webpack the javascript.

You can study the generated directory structure. We follow exactly the same template in ipyleaflet, pythreejs and bqplot...

Some background on what is going on

- the js directory holds the JavaScript code, in the form of an npm package.
- The webpack configuration generates 3 bundles
   - `../{python_module_Name}/extension.js` the notebook extension loaded on load of the page
   - `../{python_module_Name}/index.js` the amd module holding the model and views (most of the code)
   - `dist/embed.js` the amd module that is published on npmcdn and used for widget persistence.
- On the python side, the view module must become the name of your npm package
- You should also have custom models for all the widgets (with the same view modules). The custom js models hold the default javascript values. This  will reduce the footprint of the serialized blobs used for persistence.

**Comment by SylvainCorlay** [comment]
PS: I was looking at the nglview codebase earlier this week end. You should not need the es6-promise which is already included into both the notebook and the inline bundler.

**Comment by hainm** [comment]
thanks @SylvainCorlay for all of your info. It seems too much work to do, but we will do that with the flow of Jupyter project. I will keep you updated. Thanks and cheers.

@arose: ping you.

**Comment by SylvainCorlay** [comment]
I have recently migrated pythreejs and ipyleaflet to the new format. I could give you a hand but I am traveling a lot in the next couple of weeks...

**Comment by hainm** [comment]
thanks, I think we will try by ourself first before bothering you. It's good to learn anyway.

**Comment by arose** [comment]
@SylvainCorlay cool, that helps us a lot, I will try starting anew from the widget-cookiecutter

@hainm with the [reorganizing](https://github.com/arose/ngl/commits/reorg) of the ngl code I can son build a single amd module to be used in nglview

I am curious how the persistence works, having that is quite exciting.

**Comment by SylvainCorlay** [comment]
To build an amd module, we use webpack in the other libraries.

As soon as you get it to work, we will be able to include it in the new showcase gallery here:

http://jupyter.org/widgets.html

**Comment by SylvainCorlay** [comment]
@hainm any news on this?

**Comment by hainm** [comment]
@SylvainCorlay hi, there is no progress on this. It's totally up to @arose time slot.

**Comment by arose** [comment]
I'll start with it once we have 0.5 and 0.5.1 released and come back here if something is unclear, thanks for asking!

**Comment by hainm** [comment]
just add to @arose reply: v0.5 and 0.5.1 are intended to work with ipywidget < 5.0

**Comment by hainm** [comment]
@SylvainCorlay  we finally have a working version of `nglview` with `ipywidgets 5.1.5` (and notebook 4.2.1)

You can check this out: https://github.com/hainm/test_nglview_ipywidget5/blob/master/README.md

However, I still can not make the embeded code work yet

- first, I publish `nglview-js` here: https://npmcdn.com/nglview-js@0.5.2

- create an html file with embeded code copied from jupyter notebook
http://hainm.github.io/nglview_demo.html

(source: view-source:http://hainm.github.io/nglview_demo.html)

Nothing shows up. Looking at console log, error says: `http://hainm.github.io/nglview-js.js Failed to load resource: the server responded with a status of 404`. Any idea how I can get the `nglview-js.js` file?

thanks.

**Comment by hainm** [comment]
![layout](https://cloud.githubusercontent.com/assets/4451957/16903057/059a695e-4c41-11e6-94e2-3389b63c2904.png)

**Comment by SylvainCorlay** [comment]
woot! I will check out this branch later today.

**Comment by hainm** [comment]
**updated**: in case you would check out, please use the `ipywidgets5` branch in official repo.

https://github.com/arose/nglview/tree/ipywidgets5

**Comment by hainm** [comment]
I am closing this since we officially support ipywdgets >= 5. thanks.
