### ISSUE TITLE
ipywidgets saves new entries to `metadata.widgets.state` on execute and notebook displays a widget for each entry on reload

### ISSUE THREAD

**Issue by lrq3000** [ipython/ipywidgets#624]
I am using ipywidgets 4.0 with Jupyter 1.0 (IPython 4.0) in Anaconda 64-bits v4.0 (Python 2.7).

When multiple widgets are displayed, if the user starts the cell again, the widgets seem to be completely cleared and replaced by the new instances. However, if the user saves the notebook, then reopens it (eg, by refreshing the page), the old widgets that should have been cleared reappear (except the first one for each cell execution). This is because ipywidgets cleans up the first widget from the log, but not the subsequent ones.

Code to reproduce the issue:

```
import ipywidgets
from ipywidgets import IntProgress
from IPython.display import display
from time import sleep
p = IntProgress(min=0, max=100, description="First bar is deleted")
p2 = IntProgress(min=0, max=100, description="Second bar always stays")
display(p)
display(p2)
p.bar_style = 'info'
for i in xrange(100):
    p.value = p.value + 1
    p2.value = p2.value + 1
    sleep(0.01)
```

Here is a demonstration of the issue (note that it doesn't matter if the cell execution completes or if it is stopped by user, in both cases the widgets will reappear):

![ipywidgets-not-clearing-issue](https://cloud.githubusercontent.com/assets/1118942/15741912/26af62d2-28bc-11e6-8ddb-eee6f08e0a55.gif)

**Comment by gnestor** [comment]
I'm not sure I understand the problem... I am able to reproduce the 4 progress bars after a refresh vs. the expected 2.

**Comment by lrq3000** [comment]
@gnestor All "second bar"s before "first bar"  should not reappear after the refresh, as they should have been deleted/cleared when user restarted the cell.

**Comment by lrq3000** [comment]
Steps to reproduce the issue using the code above:
1. Execute cell with the above code. 
2. Restart the cell. 
3. Repeat 1 and 2 several times. At this point there is nothing abnormal. 
4. Refresh the page. Now you should see deleted "second bar"s reappearing, thus mangling the output of the last run with widgets of previous runs.

**Comment by lrq3000** [comment]
And sorry i should have posted the steps before, i don't know why I didn't.

**Comment by gnestor** [comment]
I'm still unsure what you mean by "restart the cell." Do you mean "clear the cell's output" or "restart the kernel"?

**Comment by gnestor** [comment]
Here's what I see (on master) when I run the example code and refresh the page:

![screenshot](http://g.recordit.co/dN7ctCGDny.gif)

**Comment by lrq3000** [comment]
Sorry for the loose terminology, "restart the cell" means "re-execute the cell", so just execute it again several times (you don't need to clear the output). This is not really necessary to display the issue, executing it once as you did already produces the bug, but executing it several times will multiply the bug (there will be as many "buggy" widgets as the number of time you executed the cell).

In your gif, I can see that "Second bar" is displayed first (at the top of "First bar"), which is the opposite of my example ("First bar" is displayed first and "Second bar" second). The same bug happens: the first displayed widget is cleared, but all subsequent widgets are not, so in your case "Second bar" is deleted but not "First bar".

My example code should display "First bar" first, so I don't know why it's the other way around when you executed it, but anyway the same bug happens.

What is expected: when refreshing the page, only the widgets of the last run should appear, so we should only see one "First bar" and one "Second bar", because the other ones should have been deleted by IPython when re-executing the cell.

**Comment by gnestor** [comment]
@SylvainCorlay Do you have any idea where this bug may be lurking? The notebook is reloaded and output for the cell in question contains a bunch of _ghost_ widgets that weren't displayed before reloading. On first thought, it sounds like there must be something odd going on with the cell's output in the notebook file:

```json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget": "a5257d42728f4ed6b2e65d38e377fc50"
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget": "f34a188694174b6faad558f45c0b1294"
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
  }
 ],
```

The output looks fine. However, the `metadata.widgets.state` contains 6 entries which equals the number of _ghost_ widgets:

```json
 "metadata": {
  "widgets": {
   "state": {
    "398fafc77b83477da449c1288a21a8ca": {
     "views": [
      {
       "cell_index": 0
      }
     ]
    },
    "4a834609f38f4d70840a9364a1e19bfd": {
     "views": [
      {
       "cell_index": 0
      }
     ]
    },
    "a5257d42728f4ed6b2e65d38e377fc50": {
     "views": [
      {
       "cell_index": 0
      }
     ]
    },
    "cf26b696d3ed4ea6ad86af7ca563146b": {
     "views": [
      {
       "cell_index": 0
      }
     ]
    },
    "f34a188694174b6faad558f45c0b1294": {
     "views": [
      {
       "cell_index": 0
      }
     ]
    },
    "f7c43e1ced4641afb0aa576307444c24": {
     "views": [
      {
       "cell_index": 0
      }
     ]
    }
   },
   "version": "2.0.0-dev"
  }
 },
}
```

It appears that ipywidgets is saving new entries to `metadata.widgets.state` every time the cell is executed and when the notebook is reloaded, it displays a widget for each of those entries even though if you look at the cell's source, it should only display 2 widgets (not 6).

**Comment by lrq3000** [comment]
Thank's Grant, this explains why the deleted widgets still reappear, they
do are stored.

**Comment by gnestor** [comment]
@SylvainCorlay I did some more investigating and it appears that widget state (as in WidgetManager state) keys are not being preserved across executions, so if a cell is executed multiple times, a new widget with a new key is created each time. I can't find where these keys are created so I'm not able debug further...

**Comment by lrq3000** [comment]
Thank you guys for investigating this issue :)

**Comment by jasongrout** [comment]
Related to #638.

**Comment by SylvainCorlay** [comment]
OK, this is fixed in master! We have a much better model for widgets persistence now.

**Comment by gnestor** [comment]
Thank you, Sylvain! 🙏

**Comment by lrq3000** [comment]
Thanks a lot!!!! That's really great! :D
