### ISSUE TITLE
Correct way to delete a widget ?

### ISSUE THREAD

**Issue by patrickhoebeke** [ipython/ipywidgets#631]
Hello,

I am using ipywidgets quite a lot and It must admit it is really wonderful. Thanks a lot for the job !
I've search in all documentation but I haven't found a way to **completely delete a widget**.
A "state" entry always remains in the *.ipynb file. This means that each time the notebook is run, the state of deleted widgets is kept. For a notebook using a lot of widgets and used frequently, this slows down rapidly the notebook and at the end, it blocks it completely (jscript not responding) ....
The only work-around I found up to know is to work with copies of my original notebook and restart from a fresh copy when it starts to be problematic.

So IMHO, it comes either from a bug or improper deletion of the widgets.
Any help is more than welcome !

---

Example:
Let's imagine that I create a new notebook with:

![ipywidgets_state_issue1](https://cloud.githubusercontent.com/assets/1043822/16072694/8b44101e-32e2-11e6-9d51-0bdb19d388ff.jpg)

At the end of the ipynb file, I have the following entry (which is logical): 

>   "widgets": {
>    "state": {
>     "c9cc6bc3374145dd9e7dccdb14c0ee60": {
>      "views": []
>     },
>     "fa541020ee5e4245bfe45b4b1099e8a9": {
>      "views": [
>       {
>        "cell_index": 0
>       }
>      ]
>     }
>    },
>    "version": "1.1.1"
>   }

Now, if I do the following, I still have the widget state in my *.ipynb file:
![ipywidgets_state_issue2](https://cloud.githubusercontent.com/assets/1043822/16074116/4efe4168-32e9-11e6-8f6c-f39645d360e7.jpg)

> "widgets": {
>    "state": {
>     "c9cc6bc3374145dd9e7dccdb14c0ee60": {
>      "views": []
>     }
>    },
>    "version": "1.1.1"
>   }

This "state" entry is still present even if I restart the notebook or use the magic %reset :-(
How could I delete that "state" entry from the notebook?
Any idea ?
Is this a bug ?

Thanks a lot for your help !

**Comment by SylvainCorlay** [comment]
@patrickhoebeke thanks for reporting. This is indeed a bug.

**Comment by patrickhoebeke** [comment]
mmh. I would have preferred an incorrect use from my side ;-)
Any quick work-around meanwhile ?

**Comment by lrq3000** [comment]
I reported the same bug I think in #624. The deleted widgets can also reappear when you restart the kernel. If there is a work-around, I take it too!

**Comment by jasongrout** [comment]
Related to #638.

**Comment by SylvainCorlay** [comment]
OK, this is fixed in master, and will be released in ipywidgets 6.0.

Now, widget state is saved in the notebook metadata when using the `save with widget state` command in the widgets submenu.

This state is only overridden upon save when this command is used again to avoid churn in the source files.
