### ISSUE TITLE
Problem with RadioButtons

### ISSUE THREAD

**Issue by ryanpepper** [ipython/ipywidgets#634]
On the latest commit of the development version (#9350667), Radio Buttons doesn't seem to be working; the value doesn't seem to update:
![jupyter-radiobuttons](https://cloud.githubusercontent.com/assets/8539474/16122605/a65f8574-33df-11e6-9eee-4fe5c46ad118.gif)

Wheras for the Dropdown widget, it does:
![jupyter-dropdown](https://cloud.githubusercontent.com/assets/8539474/16122610/a81c19a4-33df-11e6-89cf-0096cdefe305.gif)

Environment: OS X 10.11, Chrome, using this Conda environment:
[environment.txt](https://github.com/ipython/ipywidgets/files/318758/environment.txt)

**Comment by ryanpepper** [comment]
Eventually fixed this - I think it may have been version clash occurring with files stored in the 
~/Library/Jupyter directory

**Comment by SylvainCorlay** [comment]
Awesome. Thanks I could not reproduce.
