### ISSUE TITLE
reconsider saving widget state to notebook metadata by default

### ISSUE THREAD

**Issue by minrk** [ipython/ipywidgets#638]
It seems quite rare that restoring widget state makes sense as often as opening a notebook does. In general, it only makes sense if the kernel has not been restarted (i.e. across page refresh, but nothing else). As such, I find it quite frustrating to work with widgets now that they save a bunch of data to my notebook documents that don't make sense for anyone but me (or even me a day later). It's doubly troubling that the state apparently cannot be cleared (#637).

I believe saving widget state to notebook metadata makes sense sometimes, but that seems to be the exception rather than the rule, so I don't think the current default behavior of saving widget state in notebook metadata is desirable.

**Comment by SylvainCorlay** [comment]
We are actually not saving the widget state to the notebook metadata. Merely the list of models that are displayed. Model state is retrieved from the backend.

Besides, when saving the notebook, only live widgets are saved, so that it is effectively cleared when saving with a blank kernel.

**Comment by minrk** [comment]
So to clear widget data from the file, you have to restart the kernel?

**Comment by minrk** [comment]
Since widgets are now published as display-data messages with a widget mime-type, does that mean that widget view info in the metadata is now redundant?

**Comment by jasongrout** [comment]
Right now the widget display happens *both* through a comm message and through a display_data message. The current notebook ignores the display_data message, while JupyterLab ignores the comm message.

**Comment by jasongrout** [comment]
(when we deprecate the current notebook, we'll remove the display comm message)

**Comment by minrk** [comment]
The information is still saved in the output. As far as I can tell, the widget_state saved in notebook.metadata is 100% redundant with data stored in the output as the widget mime-type, even with notebook 4.x.

**Comment by SylvainCorlay** [comment]
gotcha

**Comment by minrk** [comment]
It may well be that the info currently saved with save_state will grow beyond what's in output, in which case we can safely ignore the redundancy. I just happened to notice in while investigating what was in my notebooks. Do you think it's likely for the two to diverge? Or are they likely to stay in sync? Or are they not actually in sync now, and it's just a coincidence in the notebooks I looked at?

**Comment by SylvainCorlay** [comment]
It is very unlikely that we add more info to the notebook metadata. Removing it completely will require us writing code to rebuild this information from the cell metadata which is doable.

**Comment by SylvainCorlay** [comment]
@minrk do you have some time for a quick chat?

**Comment by minrk** [comment]
@SylvainCorlay Yes, give me a sec.
