### ISSUE TITLE
broken links for tutorials

### ISSUE THREAD

**Issue by hainm** [ipython/ipywidgets#649]
hi, just FYI:

http://ipywidgets.readthedocs.io/en/latest/examples/Index.html

An example: http://ipywidgets.readthedocs.io/en/latest/examples/Nonblocking%20Console.ipynb

**Comment by ryanpepper** [comment]
This is broken on the stable docs too

**Comment by willingc** [comment]
Hi @hainm @ryanpepper, Thanks for the link report. We've been working on some updates to the documentation as part of the recent 5.2 release. The following links will direct you to the current latest and stable docs. As an FYI, some examples such as Nonblocking console have been removed from the documentation. 

Latest docs: http://ipywidgets.readthedocs.io/en/latest/index.html
Stable docs: http://ipywidgets.readthedocs.io/en/stable/

If you have any questions, please let us know. I'm going to close this issue as answered.
