### ISSUE TITLE
interact with tuple of strings throws an error

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipywidgets#654]
``` python
from ipywidgets import interact
def f(x):
    return x
interact(f, x=('apples','oranges'));
```

throws an error: "ValueError: ('apples', 'oranges') cannot be transformed to a Widget". However, the "Using interact" example says it should: "Dropdown menus are constructed by passing a tuple of strings. In this case, the strings are both used as the names in the dropdown menu UI and passed to the underlying Python function."

**Comment by SylvainCorlay** [comment]
OK, the documentation is wrong as of 6.0 we are adopting the sage
convention.

list - > selection
tuple -> slider (min, max, [step])

**Comment by jasongrout** [comment]
Note to self: check the documentation, and close if the docs are updated.
