### ISSUE TITLE
widget pop up?

### ISSUE THREAD

**Issue by hainm** [ipython/ipywidgets#659]
Hi,

is there any quick trick to pop up the widget and make it floatable in notebook? something like

![](https://cloud.githubusercontent.com/assets/4451957/16601880/ca90e7c8-42dd-11e6-9cfd-32966a24e288.png)

If not, is it a good idea to introduce to `ipywidget`? I just want to ask before doing anything by myself. thanks.

cc @arose

**Comment by hainm** [comment]
PS: I am aware of [jupyter dashboard](https://github.com/jupyter-incubator/dashboards) but it does not provide what I really want.

**Comment by jakirkham** [comment]
That's pretty neat @hainm. Does the code for these examples live somewhere?

**Comment by hainm** [comment]
Hi @jakirkham 

You need to install development version of [nglview](https://github.com/arose/nglview)

```bash
git clone https://github.com/arose/nglview
cd nglview
python -m pip install .
```

then issue
```bash
nglview demo # this will open a Jupyter notebook with demo command
```

then choose `Extra` button then play with drag/drop stuff. 

PS: `nglview` does not work with `ipywidget >= 5.0` yet and it works well with `ipywidgets==4.1.1`

**Comment by SylvainCorlay** [comment]
I don't think that we will allow that in ipywidgets. Although in jupyter lab, output areas should become draggable https://github.com/jupyter/jupyterlab/pull/424

![demo-424-3](https://cloud.githubusercontent.com/assets/2279598/16931180/46be41de-4d05-11e6-96df-79eb3bf1a2c5.gif)

However, jupyterlab does not support custom widgets yet. We are working on it.

**Comment by hainm** [comment]
thanks @SylvainCorlay.

**Comment by hainm** [comment]
ping @arose
