### ISSUE TITLE
IntRangeSlider does not trigger at first value change if continuous_update=False

### ISSUE THREAD

**Issue by rfinck** [ipython/ipywidgets#660]
In the example below, the value change does not trigger until at least the second time the slider is changed. Either an actual value change or just a single mouse click on the slider is sufficient to then make the next value change trigger *if* it is different from the initial value, but sliding back and forth between the initial value and another will not trigger a change until the slider is moved to a third value.

This issue is present for FloatRangeSlider too, but it is not present when continuous_update=True.

```python
from IPython import display
from ipywidgets import widgets

def has_changed(change):
    print change['new']

widget = widgets.IntRangeSlider(
    value=(0, 10),
    min=0,
    max=10,
    continuous_update=False,
)
widget.observe(has_changed, names='value')
    
display.display(widget)
```

Python 2.7
ipywidgets 4.1.1 
ipython 4.1.2

**Comment by rfinck** [comment]
I updated to 5.2.2 which has solved this issue.

**Comment by SylvainCorlay** [comment]
👍

**Comment by RJC0514** [comment]
Hmm I'm still experiencing this issue on ipywidgets 6.0.0 with Python 3.6 running the same code as above.

**Comment by jasongrout** [comment]
@RJC0514 - let's take the conversation to https://github.com/jupyter-widgets/ipywidgets/issues/1229
