### ISSUE TITLE
overflow_x not working?

### ISSUE THREAD

**Issue by lexax666** [ipython/ipywidgets#661]
I have to following code:
![overflow](https://cloud.githubusercontent.com/assets/20363034/16703029/120b8f0c-451f-11e6-9c8b-fac70141e929.png)

I was expecting jupyter to provide a horizontal scroll menu for the text boxes, since the text boxes overflowed the container box. Any idea how I could get the scroll to work? 
P.S I also tried to adjust the size the container box, but no luck.

**Comment by SylvainCorlay** [comment]
@lexax666 top-level styling attributes are deprecated (and we never had an `overflow_x` there anyway).
What you should do instead is

z.layout.overflow_x = 'scroll'.

Check out the example notebook here:

https://github.com/ipython/ipywidgets/blob/master/docs/source/examples/Widget%20Styling.ipynb

The last example makes use of `overflow_x`. It gives more information about how to lay out widgets.
