### ISSUE TITLE
Readthedocs installation page out of date?

### ISSUE THREAD

**Issue by mfirmin** [ipython/ipywidgets#675]
The readthedocs installation page (http://ipywidgets.readthedocs.io/en/latest/user_install.html) instructs you to use `conda install ipywidgets` rather than `conda install -c conda-forge ipywidgets`

Custom widgets (in particular the Hello World example) don't seem to work in the version installed by `conda install ipywidgets`.

![image](https://cloud.githubusercontent.com/assets/6256205/16932885/c4512872-4d06-11e6-89d9-b80fabd9ee29.png)

**Comment by SylvainCorlay** [comment]
cc @willingc
