### ISSUE TITLE
Move of top-level ctor from constructor to initializes

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#677]
forces the custom widget authors to call `super.initialize`....

@jasongrout This breaks every single custom widget library.

**Comment by jasongrout** [comment]
@ssunkara1 just thought through this again, and realized things were documented. Problem's are:

1. In typescript, the constructor *must* call `super()` and *must* call it before doing anything with `this`.
2. In our current logic, we wanted to set things up before calling the super's constructor. That had to change.
3. Moving things to initialize is more supported by backbone (that's where initialization "should" happen)
4. There is a bug in that we use one of our custom attributes in the `.set()` function, which @ssunkara1 is putting in a PR for.
5. If people were overriding the initialize, they should be calling the `super.initialize` anyway.
