### ISSUE TITLE
HBox/VBox layout breaks the notebook

### ISSUE THREAD

**Issue by hainm** [ipython/ipywidgets#679]
Hi

it's fine with `ipywidgets 4.1.1` but broken with `5.1` and dev version

Old
![old](https://cloud.githubusercontent.com/assets/4451957/16962948/00c370ec-4dc2-11e6-894e-8571942e9564.png)

New version
![new](https://cloud.githubusercontent.com/assets/4451957/16962956/07bf6464-4dc2-11e6-94dd-c0a73a4531e3.png)

**Comment by hainm** [comment]
info: I am using firefox 45.0.2 on Linux.

If anyone wants to try [nglview](https://github.com/arose/nglview) with `ipywidgetes >= 5.1`, you need to checkout `ipywidgets5` branch

**Comment by SylvainCorlay** [comment]
For the dropdown that is too high, you can set 

dpdown.layout.max_height = ' 32px'

which should fix this. I am checking why this is not the case in 5.x.

**Comment by SylvainCorlay** [comment]
Regarding nglview, I will check out the branch by the end of the week so that we can see what is the issue with persistence.

**Comment by SylvainCorlay** [comment]
I confirm the behavior on ipywidgets 5.x. This issue is already fixed in master.

**Comment by hainm** [comment]
hi, in the second image I sent, it shows `ipywidgets 6.0.0.dev`. I just try to pull again and the VBox still break the notebook layout.

**Comment by SylvainCorlay** [comment]
probably because it still uses the built javascript of 5.x.

**Comment by SylvainCorlay** [comment]
(I mean that the dropdown height is normal in 5.x)

**Comment by hainm** [comment]
to save your time, I make a simple script here

```python
# ipywidgets 6.0.0.dev
from ipywidgets import Button, VBox, HBox, Dropdown

HBox([HBox([Button(), Button(), Button(), Button()]),
      HBox([Button(), Dropdown()])
])
```

![new](https://cloud.githubusercontent.com/assets/4451957/16993283/abe8e408-4e70-11e6-8820-2a58e95711bf.png)

Note: the layout is fine with `4.1.1`

**Comment by SylvainCorlay** [comment]
What is the problem in this screenshot? The overflow on the right?

**Comment by hainm** [comment]
yes.

**Comment by SylvainCorlay** [comment]
Ah, that is expected, you are stacking items of fixed width horizontally.

If you want to have a different layout, you can change the `layout` attribute of the button (`width = 'auto'`, `flex =  '1 1 auto'` ).

**Comment by SylvainCorlay** [comment]
Check out the notebook here about the `layout` attribute
https://github.com/ipython/ipywidgets/blob/master/docs/source/examples/Widget%20Styling.ipynb

top-level styling attributes for widgets are deprecated. Layout can be shared among widgets.

**Comment by hainm** [comment]
thanks. I will try. 

small question: why not making the `width='auto'` as default. Regular users just want very minimal effort to 
have a nice layout.

**Comment by SylvainCorlay** [comment]
Because we like those widgets to have a natural size...

**Comment by hainm** [comment]
thanks. fair enough.

**Comment by SylvainCorlay** [comment]
Yeah, the notebook above is a good start for layout and styling. I will probably iterate on this shortly.

**Comment by hainm** [comment]
I think I can close this issue. After following [the example notebook about styling](https://github.com/ipython/ipywidgets/blob/master/docs/source/examples/Widget%20Styling.ipynb), I can make better layout.

![layout](https://cloud.githubusercontent.com/assets/4451957/17307259/21650d5c-5802-11e6-8c57-eb1b6448565e.png)

PS: example notebooks are always helpful.

thanks.
