### ISSUE TITLE
DOC website: Widget Javascript not detected

### ISSUE THREAD

**Issue by hainm** [ipython/ipywidgets#681]
FYI:
a series of error messages in website

e.g.
http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Styling.html#The-layout-attribute

![error](https://cloud.githubusercontent.com/assets/4451957/16992670/3f97bd9e-4e6e-11e6-96c4-51f58c72a6d1.png)

**Comment by hainm** [comment]
may be relate to https://github.com/ipython/ipywidgets/issues/662#issue-164723635

**Comment by willingc** [comment]
@hainm Good catch. Thanks for passing along. We'll look into this as well as #662.

**Comment by jasongrout** [comment]
The error doesn't appear anymore, it seems.
