### ISSUE TITLE
Create a simple example of using `.observe`

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipywidgets#688]
Surprisingly, we don't have any simple examples of building a small UI with widgets interacting with each other using `.observe`.

**Comment by jasongrout** [comment]
Like this:
```python
from ipywidgets import IntSlider
from IPython.display import display
x = IntSlider(description='x')
y = IntSlider(description='y')

def update_y(args):
    y.value = args['new']
    print(args['new'])

x.observe(update_y, 'value')

display(x)
display(y)
```

**Comment by hainm** [comment]
may be change `args` to `change` for consistency and adding `change['old']` too? 

```python
def update_y(change):
    y.value = change['new']
    print(change['old'], change['new'])
```

**Comment by SylvainCorlay** [comment]
Note: use `change.old` and `change.value` instead of `get_item`.

**Comment by hainm** [comment]
is this new in 6.0.x?

**Comment by SylvainCorlay** [comment]
Fairly new in traitlets

**Comment by denfromufa** [comment]
IMO, this example is not enough, here is related issue:

https://github.com/jupyter-widgets/ipywidgets/issues/1731

**Comment by jasongrout** [comment]
Let's come up with another example over there and submit it to the docs. It's always great to have more!
