### ISSUE TITLE
Dropdown: weird error message

### ISSUE THREAD

**Issue by hainm** [ipython/ipywidgets#693]
- the error message is very weird for me.

```python
d = ipywidgets.Dropdown(value=1, options=range(3))
d
```

```bash
...
TraitError: The 'options' trait of a Dropdown instance must be any value or any value, but a value of range(0, 3) <class 'range'> was specified.
```

**Comment by SylvainCorlay** [comment]
range is a generator in python3, not a list.

I am afk at the moment but it should work if you convert it to list.

**Comment by hainm** [comment]
hi, the message says

`The 'options' trait of a Dropdown instance must be any value or any value`

**Comment by SylvainCorlay** [comment]
OK, this is a traitlets issue. The trait type of the `options` attribute of the selection widgets is `Union([List(), Dict()])`.

And
```
print(Dict().info_text)
print(List().info_text)
print(Int().info_text)
```
returns 

```
any value
any value
an int
```

`info_text` is not specified for all trait types.

We should probably work on better error messages in the traitlets library.

**Comment by SylvainCorlay** [comment]
OK, this is a traitlets issue. The trait type of the `options` attribute of the selection widgets is `Union([List(), Dict()])`.

And
```
print(Dict().info_text)
print(List().info_text)
print(Int().info_text)
```
returns 

```
any value
any value
an int
```

`info_text` is not specified for all trait types.

We should probably work on better error messages in the traitlets library.

**Comment by SylvainCorlay** [comment]
OK, this is a traitlets issue. The trait type of the `options` attribute of the selection widgets is `Union([List(), Dict()])`.

And
```
print(Dict().info_text)
print(List().info_text)
print(Int().info_text)
```
returns 

```
any value
any value
an int
```

`info_text` is not specified for all trait types.

We should probably work on better error messages in the traitlets library.

**Comment by SylvainCorlay** [comment]
OK, this is a traitlets issue. The trait type of the `options` attribute of the selection widgets is `Union([List(), Dict()])`.

And
```
print(Dict().info_text)
print(List().info_text)
print(Int().info_text)
```
returns 

```
any value
any value
an int
```

`info_text` is not specified for all trait types.

We should probably work on better error messages in the traitlets library.

**Comment by SylvainCorlay** [comment]
Closing since jake vpd opened https://github.com/ipython/traitlets/issues/260
