### ISSUE TITLE
SpinnerView example:   semantics of this.$variableName?

### ISSUE THREAD

**Issue by paul-shannon** [ipython/ipywidgets#695]
Working my way through the very helpful  [HelloWorld.ipynb](https://github.com/ipython/ipywidgets/blob/master/docs/source/examples/Custom%20Widget%20-%20Hello%20World.ipynb), I find that I do not quite understand  the meaning of "$" in these statements within SpinnerView.render:

    this.$input = $('<input />');
    this.$el.append(this.$input);
    this.$spinner = this.$input.spinner({...

I recognize the jQuery function call shorthand:

    $('<input />')

 Does the other uses of $, of which three are shown just above,  all in this style

     this.$variableName

indicate that the object slot is a jQuery object?  The comments in the notebook are very complete and helpful, but this point eludes me.

Thanks!

**Comment by pbugnion** [comment]
It's fairly common practice to name variables (or object fields) that hold a jQuery element with names starting with a `$`. There is no programmatic meaning to the `$` itself in the variable name. It's just convention.

For instance, in a `DOMWidgetView`, you have access to both `this.el`, which represents the actual DOM element the widget view is attached to, and `this.$el`, a jQuery element equivalent to `$(this.el)`. Thus, both this:

```javascript
this.$el.text('Hi Paul');
```

and this

```javascript
this.el.textContent = 'Hi Paul';
```

would have the same behaviour.

**Comment by paul-shannon** [comment]
Thank you!
