### ISSUE TITLE
can not restart notebook if getting "Could not cross validate the widget frontend and backend versions"

### ISSUE THREAD

**Issue by hainm** [ipython/ipywidgets#697]
hi,

I got `*` status besides the notebook cell when getting above error (and I knew why I got that).
However, I could not restart and rerun the notebook by clicking `Kernel -> Restart` or anything else.
I must close the notebook by File -> Close and Halt.

![star](https://cloud.githubusercontent.com/assets/4451957/17350334/e39962fa-58f3-11e6-846e-4c6c86ae3d62.png)

version:

``` bash
ipywidgets: 5.2.2
notebook: 4.2.1
```

**Comment by hainm** [comment]
dummy code
=========

# cell 1
```python
%%javascript

define(['jupyter-js-widgets'], function(widget){
	var TabModel = SelectionContainerModel.extend({
	    defaults: _.extend({}, SelectionContainerModel.prototype.defaults, {
	        _model_name: "TabModel",
	        _view_name: "TabView"
	    }),
	});
})
```

# cell 2
```python
import ipywidgets, traitlets
from traitlets import Unicode

class Tab2(ipywidgets.Tab):
    _view_name = Unicode('TabView2').tag(sync=True)
    _model_name = Unicode('TabModel').tag(sync=True)
```

# cell 3
```python
tab = Tab2()
tab
```

**Comment by gnestor** [comment]
@hainm This sounds like an issue that should be posted on the notebook repo.

**Comment by jasongrout** [comment]
@hainm - I'm not reproducing this. Are you still observing it? If so, what version of the notebook were you using, and what version of widgets (both python and javascript side)?

**Comment by jasongrout** [comment]
Closing since there was no response. Please reopen if this is still an issue.

**Comment by hainm** [comment]
I am sorry, not sure why I missed this notification. Yes, I will reopen this if encountering the issue again. thanks.
