### ISSUE TITLE
adjusting space between icon and text in Button?

### ISSUE THREAD

**Issue by hainm** [ipython/ipywidgets#699]
Hi,

I am using v5.2.2. Is there any way to change the space between icon and text in button?

Seems too tight to me.

![icon](https://cloud.githubusercontent.com/assets/4451957/17390642/f9f769ae-59dc-11e6-874d-e6ca425bb01c.png)

**Comment by hainm** [comment]
trick: adding space

```python
ipywidgets.Button(description=' Refresh', icon='fa-trash')
```

**Comment by SylvainCorlay** [comment]
> Is there any way to change the space between icon and text in button?

Not at the moment. Indeed it is a bit close.

**Comment by jasongrout** [comment]
There is now a 4px padding between the icon and the text: 
<img width="486" alt="screen shot 2016-11-14 at 4 03 03 pm" src="https://cloud.githubusercontent.com/assets/192614/20282698/dd280caa-aa83-11e6-8d9c-c9d5e8442f47.png">
