### ISSUE TITLE
Widget Styling Example Not Loading

### ISSUE THREAD

**Issue by madridnick** [ipython/ipywidgets#702]
@SylvainCorlay, the styling notebook doesn't seem to load for me

ipywidgets/docs/source/examples/Widget Styling.ipynb

https://github.com/ipython/ipywidgets/blob/47611c9ec312d17a6703ddbcc35f59913f242f05/docs/source/examples/Widget%20Styling.ipynb

**Comment by SylvainCorlay** [comment]
@madridnick it seems to be an issue with Github's notebook viewer, which is not developed by the Jupyter team. It renders correctly on nbviewer.

http://nbviewer.jupyter.org/github/ipython/ipywidgets/blob/master/docs/source/examples/Widget%20Styling.ipynb

**Comment by jasongrout** [comment]
I submitted a request to github.
