### ISSUE TITLE
Get rid of blue highlight after button is clicked.

### ISSUE THREAD

**Issue by alexanderwhatley** [ipython/ipywidgets#704]
This is a pretty minor issue, but the button is highlighted in blue after being clicked, and I cannot find any information on how to get rid of it. Is there a way to do it. Attached is a screenshot of an example, and example code:

```
from IPython.display import display
from ipywidgets.widgets import Button
def click(b):
    print("Hi")
b = Button(description = "Click me")
b.on_click(click)
display(b)
```

![image](https://cloud.githubusercontent.com/assets/14192598/17488795/d6bce308-5d4f-11e6-8997-cffea000df33.png)

**Comment by SylvainCorlay** [comment]
Thanks for the report! This is already fixed in master.

**Comment by jasongrout** [comment]
Confirmed.
