### ISSUE TITLE
How to construct new models on the client?

### ISSUE THREAD

**Issue by abelnation** [ipython/ipywidgets#706]
It is not clear how I can go about constructing a model on the client and push it to the server.  Can a quick example be posted demonstrating that?  Or, at worst, can you explain how to leverage the widgetmanager to create new models?

**Comment by SylvainCorlay** [comment]
The widget manager's `new_widget` does what you are looking for. An example of widget that uses `new_widget` is the `Controller` widget, which detects the properties of the connected game controller and pushes as many button an axes models as needed to the backend.

**Comment by abelnation** [comment]
perfect.  thanks!
