### ISSUE TITLE
nothing happens when send(msg) is triggered from frontend

### ISSUE THREAD

**Issue by damlatien** [ipython/ipywidgets#708]
I am trying to make the following example work : 
```python
from ipywidgets import Button
from IPython.display import display

def on_button_clicked(b):
    print("Button clicked.")
button = Button()
button.on_click(on_button_clicked)
display(button)
```

then the following : 
```python
button.send({'event':'click'})
```
doesn't trigger the event as I would (maybe naively) expect. 

Could someone explain please ?

**Comment by SylvainCorlay** [comment]
Hum I don't reproduce. Can you please specify the versions of notebook and ipywidgets that you are using?

**Comment by jdfreder** [comment]
Is the later supposed to be Javascript?  It's hard to tell because you've written it like Python.  If it's python, I have no idea what you're trying to do.  The code would send a custom message to a frontend which would be ignored.

**Comment by damlatien** [comment]
Yes it is python, what I would like to achieve is to send a custom message from the python frontend. Sorry that I was'nt clear

**Comment by jdfreder** [comment]
You have achieved that - but the front-end ignores the custom message you've sent because there's not Javascript to handle that message.  If you're trying to invoke a button click in the front-end, you'll need to write Javascript to do so.

**Comment by damlatien** [comment]
ok, thanks !
