### ISSUE TITLE
Excessive spacing between Text objects in HBox.

### ISSUE THREAD

**Issue by alexanderwhatley** [ipython/ipywidgets#709]
I have the following code in a cell in the Jupyter Notebook:

```
from ipywidgets.widgets import HBox, Text
from IPython.display import display

text1 = Text(description = "text1", width = 100)
text2 = Text(description = "text2", width = 100)
text3 = Text(description = "text3", width = 100)
text4 = Text(description = "text4", width = 100)
text5 = Text(description = "text5", width = 100)
display(HBox((text1, text2, text3, text4, text5)))
```

It produces the following output:
![image](https://cloud.githubusercontent.com/assets/14192598/17608751/7871aa9a-5fe3-11e6-981a-b9b6d0784536.png)

Are the displayed Text objects supposed to be this far apart? How do I change the spacing so that they stay within the cell?

**Comment by SylvainCorlay** [comment]
What version of ipywidgets are you using?

**Comment by jdfreder** [comment]
If I were you, I'd remove the descriptions from the text boxes and inject HTML widgets between the text boxes instead

**Comment by alexanderwhatley** [comment]
@SylvainCorlay 
>>> ipywidgets.__version__
'4.1.1'

**Comment by alexanderwhatley** [comment]
@jdfreder I don't think that's going to help. I removed the descriptions from the text boxes, and the same thing still happened:

![image](https://cloud.githubusercontent.com/assets/14192598/17612036/b90f1ff6-6001-11e6-8ab4-0ffaca0c9585.png)

**Comment by jdfreder** [comment]
Strange, sounds like a bug.  As a workaround, you should be able to collapse them with CSS.  I don't remember if the notebook has a %%css magic, but I don't think it does.  Instead you can use an html magic and a style tag to embed your custom css.

**Comment by alexanderwhatley** [comment]
Ok, I fixed the problem by adding in the following line of code after the last line:

`HTML('<style> .widget-text { width: auto; } </style>')`

This definitely seems like a bug though; the default display should not look like this.

**Comment by alexanderwhatley** [comment]
Ok hmm, more weird behavior. When I add in that line, everything looks good:

![image](https://cloud.githubusercontent.com/assets/14192598/17614088/3356025a-6018-11e6-83b6-fa1c239f6f9b.png)

However, when I add in a print statement below it, it gets messed up again:

![image](https://cloud.githubusercontent.com/assets/14192598/17614102/501d1068-6018-11e6-96ff-d953b70377b8.png)

**Comment by SylvainCorlay** [comment]
@alexanderwhatley 4.1.1 is pretty old now. The current stable version is 5.2.2. You can install it from the conda-forge channel.

**Comment by alexanderwhatley** [comment]
Alright, so I upgraded to 5.2.2. So the spacing issues appears to be fixed, but there appear to be sizing issues now. As you can see, the width of the text boxes has gotten larger, and I cannot seem to change it (changed from 100 ).

![image](https://cloud.githubusercontent.com/assets/14192598/17636458/feba4658-6091-11e6-97fc-a0d6b25b10e7.png)
![image](https://cloud.githubusercontent.com/assets/14192598/17636483/32e334da-6092-11e6-907c-494ae549bdf7.png)

**Comment by SylvainCorlay** [comment]
As of ipywidgets 5.x, top-level styling attributes are not exposed anymore.

Check out the notebook here about the layout attribute
https://github.com/ipython/ipywidgets/blob/master/docs/source/examples/Widget%20Styling.ipynb

top-level styling attributes for widgets are deprecated. Layout can be shared among widgets.

**Comment by SylvainCorlay** [comment]
Example of sharing the same layout attribute on multiple widgets:

```python
l = Layout(width='100px')
HBox(children=Text(layout=l) for i in range(10)])
```

**Comment by alexanderwhatley** [comment]
Thanks. I don't think there's much more to discuss, so I'll close this thread.
