### ISSUE TITLE
Creating a new "model_ready" event in widget.js

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#71]
I encountered the following problem with widgets that create sub-widgets from the JavaScript side in their JavaScript model constructor: 

For example the gamepad widget creates subwidgets for the buttons and axes in its constructor. Once the `connected` trait attribute is set to True, the user may wire things to the gamepad buttons...

However, in the case of a page reload, I would like these widgets **not** to be replaced by new ones, when the constructor of the JavaScript side is executed. The part of the constructor containing the creation of the children should only occur after the state request resolves.

One way to solve this issue would be to create a `model-ready` event for that, of have a certain promise that gets resolved right away in the case of a new model, and after the state request resolves in case of page reload.

Suggestions welcome.

@jdfreder @jasongrout

**Comment by SylvainCorlay** [comment]
I think this is related to the idea of sending the first state at the same time as when we create the widget.

**Comment by jdfreder** [comment]
Either solution sounds fine to me.  Like you mention, moving the initial state push to the comm open event may remedy this.

**Comment by SylvainCorlay** [comment]
Do you want me to look at this today. (since the widget persistence changes got in)

**Comment by jdfreder** [comment]
Yeah, if we want to get this in for 4.0, I'd do it ASAP.  I don't think we'll hold 4.0 if this isn't ready though.

**Comment by jasongrout** [comment]
This is related to #112, and probably deserves more than a few minutes discussion and time to test it in practice.  So we're pushing this back to 4.1.

**Comment by SylvainCorlay** [comment]
The fixes to this and #112 needed to happen after #62. It is just too bad it took so much time to get it in.

**Comment by jdfreder** [comment]
@SylvainCorlay , I forget, was this fixed by all the work you did with create_widget and new_widget?

**Comment by SylvainCorlay** [comment]
@jdfreder I think this will still be needed even after the `beastmode` PR, because of the usecase described in the issue description.
