### ISSUE TITLE
Support observe as a decorator

### ISSUE THREAD

**Issue by aplavin** [ipython/ipywidgets#716]
When one needs to `observe` a widget trait, it can't be done without separately defining the handler function and then subscribing:

```python
def handler(*_):
    # ... code ...

w.observe(handler, 'value')
```

Wouldn't it be better if you could just write like this:

```python
@w.observe('value')
def _(*_):
    # ... code ...
```

This way there is also no need to make a name for the handle function.

However, it's often useful to call the handler once after setting everything up, e.g. if you make some plots in the handler it makes sense to display them without forcing user to move a slider or something. So, I also suggest adding an argument to `observe`, like `run=True` (looking for a better name :) ) or a separate method `observe_and_run` which would also execute the handler (in addition to subscribing).

So, instead of:

```python
def handler(*_):
    # ... code ...

w.observe(handler, 'value')
handler()
```

we would be able to write:

```python
@w.observe('value', run=True)
def _(*_):
    # ... code ...
```

**Comment by jdfreder** [comment]
hmmm I thought traitlets already supported this, @SylvainCorlay -?

**Comment by SylvainCorlay** [comment]
Traitlets allows this for methods, not free functions. This is a https://github.com/ipython/traitlets issue.

**Comment by SylvainCorlay** [comment]
```python
from traitlets import HastTraits, Unicode, observe

class Foo(HasTraits):
    bar = Unicode()

    @observe('bar')
    def _bar_change(self, change):
        self.baz = change['new']
```
