### ISSUE TITLE
get_state arguments not consistent

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipywidgets#720]
https://github.com/ipython/ipywidgets/blob/43b49e210bbceddb668dd695351c503edcf6a640/jupyter-js-widgets/src/widget.ts#L312 calls `get_state` with an options object, but `get_state` just takes a boolean value

(hooray for (manual) static typing :)

**Comment by SylvainCorlay** [comment]
@jasongrout this was fixed in #739
