### ISSUE TITLE
Backbone native view example

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#73]
@jdfreder do you think we should provide an example using a `backbone.NativeView` with the widgets? This would require shipping [NativeView](https://github.com/akre54/Backbone.NativeView) but it would be interesting for people willing to make custom widgets without jquery.

**Comment by jdfreder** [comment]
I don't think it makes sense to add a dependency to the project solely for an example.  On the other hand, weening ourselves from jQuery where possible is a good thing IMO.  You've already thinned the jQuery usage in the widgets, what do you think about shipping a NativeView and using the WidgetViewMixin with it for our base widgets?

Maybe that's not a good idea though... I'm not sure about the effort required to do this, how compatible NativeView is with BackboneView, how many docs would need to change, and how many of our users are inheriting from the base widgets, relying on jQuery-ism builtin.

**Comment by SylvainCorlay** [comment]
We would need to export other base view classes, in addition to `WidgetView` and `DOMWidgetView`...
Backbone 1.2 was apparently meant to allow for other view types with the [view hooks](https://github.com/jashkenas/backbone/wiki/Using-Backbone-without-jQuery).

Although I feel like there should have rather been a hierarchy of view types, eventually inheriting from NativeView, but I don't know if they could have done something like this while remaining backward compatible.

**Comment by SylvainCorlay** [comment]
I think that this was "fixed" in #627 .
