### ISSUE TITLE
Add a Troubleshooting subsection to dev install docs

### ISSUE THREAD

**Issue by willingc** [ipython/ipywidgets#732]
Based on discussion on gitter and #662, let's expand the notes subsection into a Troubleshooting subsection to https://github.com/ipython/ipywidgets/blob/master/docs/source/dev_install.md 

While it might not solve the underlying issue, it will at least provide greater possiblity for users to find a solution when install is 😢 

cc @fperez @SylvainCorlay

**Comment by fperez** [comment]
+1, excellent idea. Thanks!!

**Comment by SylvainCorlay** [comment]
👍
