### ISSUE TITLE
Phosphor-tabs based tabs broken

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#733]
As reported by @fperez 

![image](https://cloud.githubusercontent.com/assets/57394/17911389/1c1f403c-6942-11e6-9fd6-eb3793fcfbb1.png)

**Comment by SylvainCorlay** [comment]
cc @jasongrout @afshin

**Comment by fperez** [comment]
Thanks @SylvainCorlay, for reference this is what it used to look like:

![image](https://cloud.githubusercontent.com/assets/57394/17871881/6df0a32c-6872-11e6-8887-1ee1a20b1776.png)

as reported in #662 where we started looking at this.

**Comment by SylvainCorlay** [comment]
@fperez it is most likely due related to a change in phosphor mono-repo. This should be fixed soon.

**Comment by fperez** [comment]
Sure, I'm not worried :) Just glad you can reproduce it so we can track it down.  Thanks!

**Comment by gnestor** [comment]
This was fixed by https://github.com/ipython/ipywidgets/pull/848
