### ISSUE TITLE
How did the new widget registration API change between 4.1.1 and 5.1.5?

### ISSUE THREAD

**Issue by rs2** [ipython/ipywidgets#736]
A custom widget that is registered by subclassing `widgets.DOMWidget` used to work with 4.1.1, but no longer does when upgrading to `ipywidgets 5.1.5`.

**Comment by hainm** [comment]
@rs2 you can check old thread here: https://github.com/ipython/ipywidgets/issues/618

**Comment by SylvainCorlay** [comment]
@rs2 there was a lot of changes between 4.x and 5.x. If you have custom widget projects, I suggest you check out the widget cookiecutter project which is a template for such projects and takes care of a lot of the boilerplate.
