### ISSUE TITLE
Resetting an attribute to default doesn't sync

### ISSUE THREAD

**Issue by justinmc** [ipython/ipywidgets#738]
Setting an attribute in a model back to its original default is not synced to the server as it should be.

```js

    // This will be successfully synced to Python
    model.set('myparam', 'notthedefault');
    model.save();

    ...

    // If model's default is empty string, this will not be
    // synced, so Python will still see myparam as "notthedefault"
    model.set('myparam': '');
    model.save();
```

I believe this is caused by [this line](https://github.com/ipython/ipywidgets/blob/eb4dcd9956d88ae842bff7822a9c32fc038906dd/jupyter-js-widgets/src/widget.ts#L312) in WidgetModel's `sync` method, which is passing what seems to be an unrelated `options` object into [get_state](https://github.com/ipython/ipywidgets/blob/eb4dcd9956d88ae842bff7822a9c32fc038906dd/jupyter-js-widgets/src/widget.ts#L207), which expects a boolean.

I will attempt a pull request really quick, but I'm not totally sure what the original intent was in passing the options object here.

**Comment by SylvainCorlay** [comment]
Closed with #739
