### ISSUE TITLE
CaselessStrEnum for layout attributes?

### ISSUE THREAD

**Issue by hainm** [ipython/ipywidgets#740]
Hi,

I have hard time about silent error.

For example, I try

``` python
from ipywidgets import Text

t = Text()
t

# set visibility
t.layout.visibility = True # and 'true'
```

nothing happens, no error message.
turns out that `t.layout.visibility = 'hidden' # or visible`

It's great help if error message is clearer. Since [Layout](https://github.com/ipython/ipywidgets/blob/master/ipywidgets/widgets/widget_layout.py) only support a subset of CSS, what's about using CaselessStrEnum rather the Unicode?

**Comment by SylvainCorlay** [comment]
totally
