### ISSUE TITLE
Falsey values in selection

### ISSUE THREAD

**Issue by aplavin** [ipython/ipywidgets#743]
It looks like `ipywidgets` doesn't support falsey values (e.g. empty string) as options. The simplest reproducible example:

```python
ToggleButtons(options=[''])
```
raises `TraitError: Invalid selection`.

Not sure if that's intentional, but something like `['', 'opt 1', 'opt 2']` as `options` totally makes sense, as for me.

**Comment by hainm** [comment]
I agree with @aplavin. That (`''`) used to work with v4 version.

**Comment by SylvainCorlay** [comment]
Thanks for the report.
