### ISSUE TITLE
Should we remove completely the deprecated widget names (suffixed with Widget?)

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#75]
@jdfreder

**Comment by jdfreder** [comment]
I brought this up earlier and the response was no for 4.0 - https://github.com/ipython/ipywidgets/issues/18  .  For 5.0 I think we definitely should!

**Comment by ellisonbg** [comment]
I am +1 on removing them.

On Wed, Jul 1, 2015 at 9:29 PM, Jonathan Frederic <notifications@github.com>
wrote:

> I brought this up earlier and the response was no for 4.0 - #18
> <https://github.com/ipython/ipywidgets/issues/18> . For 5.0 I think we
> definitely should!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/issues/75#issuecomment-117901821>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
For 4.0?

**Comment by jasongrout** [comment]
We removed the deprecated names in https://github.com/ipython/ipywidgets/pull/90
