### ISSUE TITLE
SelectMultiple : width locked to 300px ?

### ISSUE THREAD

**Issue by patrickhoebeke** [ipython/ipywidgets#750]
Hello,

It seems that the width of the SelectMultiple widget is locked to '300px'.
Indeed, when I try to set the width to '500px' using the Layout option, the main container "HBox" is updated to '500px' but the listbox widget itself is kept to '300px'.
I think it is a bug. Could you confirm ?
Is there a way to get an auto-width ?

have a nice day !

```python
from ipywidgets import widgets
options=['abcdefghijklmnopqrstuvwxyz ** '*2]
widgets.SelectMultiple(options=options,layout=Layout(width='500px',border='solid'))
```

![2016-09-01 14_02_33-xubuntu_14 04_ilab en fonction - oracle vm virtualbox _ 1](https://cloud.githubusercontent.com/assets/1043822/18166681/ce462e7c-704c-11e6-8601-34a174303364.jpg)

**Comment by SylvainCorlay** [comment]
Thanks for the very clear report. This is clearly a bug.  I have a shortlist of css / styling issues that I intend to backport to 5.x and I will make a 5.3 release shortly after.

**Comment by patrickhoebeke** [comment]
Cool ! Thanks for your quick reaction.
By the way, the widgets are really great. Very nice job !

**Comment by clupascu** [comment]
Hello, 

I noticed this bug too. When it will be fixed?

Have a nice day!

**Comment by patrickhoebeke** [comment]
Great ! Thanks !

**Comment by clupascu** [comment]
Thanks!
