### ISSUE TITLE
Imperfect 'save notebook with snapshots' 

### ISSUE THREAD

**Issue by oscar6echo** [ipython/ipywidgets#754]
As requested by Sylvain in [this post](https://groups.google.com/forum/#!topic/jupyter/pHgV_V3XoPs) from the [Google Group Jupyter forum](https://groups.google.com/forum/#!forum/jupyter).

When I click the menu 'save notebook with snapshot', I don't get the expected result.
3 different imperfect behaviours in 3 contexts.

1/
After saving the widgets as snapshots, if I reopen the notebook the images appear briefly then disappear and the DOM does not contain any hidden image.

2/
After going through nbviewer, the snapshots do appear, but they are followed in some cases by parasite text.

3/
Seen through the native github .ipyb renedring the snapshots do appear and are followed by either the object name (probably not wanted (?) but at least structured) or in some cases some parasite text.

In order to reproduce, go check this repo: [BlackScholesWidget](https://github.com/oscar6echo/BlackScholesWidget).

You can
1/ run demo_blackscholes_widget.ipynb then save then reopen and see by yourself.
2/ see the nbviewer rendering of the notebook [there](http://nbviewer.jupyter.org/github/oscar6echo/BlackScholesWidget/blob/master/demo_blackscholes_widget.ipynb)
3/ see the the github rendering of demo_blackscholes_widget.ipynb [there](https://github.com/oscar6echo/BlackScholesWidget/blob/master/demo_blackscholes_widget.ipynb)

It might be that some of the parasite text is due to the HTML widget, which contains some js code (to render a 2 or 3d surface)...?

**Comment by oscar6echo** [comment]
Here is another example of imperfect behavior.

This [notebook](https://github.com/oscar6echo/ImageColorReduction/blob/master/Image_Color_Reduction.ipynb) is 'saved with snapshots'.
It is renders perfectly with the github renderer.
The widgets are displayed twice in nbviewer.
There do not show if you open the notebook with jupyter.

Hope this helps.
Overall pretty good, and very convenient !

**Comment by SylvainCorlay** [comment]
The widgets snapshot feature was removed from `ipywidgets` in master. In ipywidgets 6.0 (to be released), notebooks can be saved with the widget state, and widgets will be rendered by tools such as nbviewer can render it.

See e.g. http://nbviewer.jupyter.org/github/ipython/ipywidgets/blob/master/docs/source/examples/Widget%20List.ipynb
