### ISSUE TITLE
Examples/anything for R

### ISSUE THREAD

**Issue by richardbeare** [ipython/ipywidgets#792]
Hi,
Apologies if I've missed an obvious link somewhere describing how this works.

The recent developments mention making the widgets available to other kernels, but I've not found any examples. I'm specifically interested in R. If it isn't ready to go yet, what needs to be done/written/fixed etc.

Thanks

**Comment by gnestor** [comment]
ipywidgets depend on the ipython kernel, so they don't work with IRkernel. However, I found a couple links that might help:

* Using Plotly widgets with IRkernel: https://plot.ly/r/using-r-in-jupyter-notebooks/
* Using declarative-widgets with IRkernel: https://github.com/jupyter-incubator/declarativewidgets

**Comment by richardbeare** [comment]
I guess I was chasing the status of R support mentioned in 5th paragraph of this post:

http://blog.jupyter.org/2016/04/22/ipywidgets5/

FYI - we're trying to produce some commonish notebooks for python and R for the simpleITK project.

**Comment by gnestor** [comment]
The decoupling of jupyter-js-widgets allows kernel authors (and others) to make use of this client-side code to create things like ipywidgets for other kernels, although I don't think anything for R is available yet. It looks like declarativewidgets uses [a very small part](https://github.com/jupyter-incubator/declarativewidgets/search?utf8=%E2%9C%93&q=jupyter-js-widgets). I would suggest taking a look at declarativewidgets as they work with IPython and IRkernel.

**Comment by richardbeare** [comment]
Thanks - will do

**Comment by hoangmt** [comment]
Hi, maybe this one is similar to what you want:
https://rstudio.github.io/shinydashboard/get_started.html
Best,
