### ISSUE TITLE
Help with ipywidgets dev installation

### ISSUE THREAD

**Issue by aggFTW** [ipython/ipywidgets#793]
Hi,

I'm getting `Error: Object 'jupyter.widget' not found in registry` from JupyterLab and `The installed widget Javascript is the wrong version.` from regular Jupyter.

Jupyter info is:

```
The version of the notebook server is 4.2.3 and is running on:
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609]
```

I have two python environments. One for my jupyter server, and a second one for my kernel.

If I do `pip show ipywidgets` for both environments, I get version `6.0.0.dev0`.
If I do `pip show widgetsnbextension` for both environments, I get version `2.0.0.dev0`.

Debugging the javascript for Jupyter on my browser, I see the following code:

```
var version = __webpack_require__(27).version;
var requirement = msg.content.data.version;
```

where `version` ends up being `1.2.0` and `requirement` is `~2.0.0-dev`.

Any idea where version `1.2.0` might be coming from? From names of variables, it would seem that version being seen by the kernel is 1.2.0 and version seen by Jupyter is 2.0.0? Or is it the other way around?

Thanks!

**Comment by aggFTW** [comment]
Turns out I had to remove some folder manually so that the 1.2.6 egg got removed. Now, however, I'm getting a `Widget Javascript not detected. It may not be installed properly. Did you enable the widgetsnbextension? If not, then run "jupyter nbextension enable --py --sys-prefix widgetsnbextension"` even after I have indeed enabled it. Any ideas on how to debug? I am doing a dev install of ipywidgets so that it works with JupyterLab.

What version of JupyterLab do I need for latest ipywidgets?

**Comment by gnestor** [comment]
@SylvainCorlay Are ipywidgets working in Jupyter Lab yet?

**Comment by aggFTW** [comment]
I'm unable to install jupyterlab and ipywidgets and get them to work, even on the same environment (I'm using Anaconda on Windows).

Is there a place that lists:
- What commands/directories do I have to erase to completely delete any trace of ipywidgets in my box?
- What commands/directories do I have to erase to delete serverextension/nbextension/lab extension settings that might be corrupting the environment?
- What commands do I need to run to fresh install JupyterLab and Ipywidgets?

**Comment by aggFTW** [comment]
Even simpler: How do I get ipywidgets dev to work with Jupyter 4.2.0?
Installing results in `Widget Javascript not detected.  It may not be installed properly. Did you enable the widgetsnbextension? If not, then run "jupyter nbextension enable --py --sys-prefix widgetsnbextension"` even though I've run that command before.

Running `jupyter nbextension list` returns:
```
Known nbextensions:
  config dir: /usr/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK
```

**Comment by SylvainCorlay** [comment]
> @SylvainCorlay Are ipywidgets working in Jupyter Lab yet?

We are demoing it today at strata but it is still not in its final form.

**Comment by SylvainCorlay** [comment]
> I'm trying to understand how the different pieces of ipywidgets come together. If there's one python environment for the jupyter server and another python environment for the kernel, which environment needs the widgetnbextension enabled? As of today, I'm enabling on both, but if my understanding is correct, I could get away with just enabling on the jupyter server python environment and get away with just pip installing on the kernel environment. 

That is right. The correct environment to enable the extension is the one of the server.

**Comment by gnestor** [comment]
@SylvainCorlay I've tried pulling from ipywidgets and jupyterlab from master and reinstalling but I'm still getting this error when trying to run one of the ipywidgets example notebooks. What am I missing?

**Comment by aggFTW** [comment]
@SylvainCorlay Yes, running from source

**Comment by hainm** [comment]
I got the same story about 'jupyter.widget not found'

**Comment by gnestor** [comment]
AFAIK, ipywidgets is not working with jupyterlab yet (I'm still seeing "The installed widget Javascript is the wrong version." error).

If you're are still having issues installing from source:

* First uninstall the pip-installed version (e.g. `pip uninstall ipywidgets`). This sometimes requires manually removing the egg files.
* Follow the developer install instructions for the specific project (e.g. [ipywidgets dev install](https://github.com/ipython/ipywidgets/blob/master/docs/source/dev_install.md)).
* When pulling changes upstream, re-run the build instructions for the specific project (e.g. `bash dev-install.sh --sys-prefix` for ipywidgets).
* If building fails, you can try `git clean -xfd` and re-building.

**Comment by hainm** [comment]
> AFAIK, ipywidgets is not working with jupyterlab yet (I'm still seeing "The installed widget Javascript is the wrong version." error).

uhm, I need to wait longer :(. I was so excited to try our [nglview](https://github.com/arose/nglview) with `jupyerlab`

**Comment by gnestor** [comment]
I take that back! ipywidgets is working with jupyterlab! Here are install instructions: https://github.com/ipython/ipywidgets/tree/master/jupyterlab_widgets

**Comment by hainm** [comment]
great. I will try, thanks. Do you test by yourself too?

**Comment by gnestor** [comment]
I did test it myself. I doesn't look like nglview provides a labextension so it will probably not work in jupyterlab until it does ☹️

**Comment by hainm** [comment]
Thanks. We can work on that, just want to make sure ipywidgets does work in lab. Cheers.

**Comment by gnestor** [comment]
To clarify, ipywidgets at master works with jupyterlab: https://github.com/ipython/ipywidgets/tree/master/jupyterlab_widgets

ipywidgets at 5.2.2 does not: https://github.com/ipython/ipywidgets/tree/5.x/jupyterlab_widgets

**Comment by jasongrout** [comment]
Closing as answered. Please reopen if you'd like to continue the conversation.

**Comment by aggFTW** [comment]
Thanks @jasongrout !
