### ISSUE TITLE
Migrate back to the default readthedocs theme for documentation

### ISSUE THREAD

**Issue by gnestor** [ipython/ipywidgets#799]
At the moment, we use a custom sphinx theme, which has the default of not being very maintained. We would like to migrate to the default readthedocs theme. 

However, we will probably need to fork it in the case of ipywidgets to support the rendering of inline widgets in the documentation.

**Comment by willingc** [comment]
@gnestor That's fine with me, but let's take a look at the cloud_sptheme (used by xonsh project @Carreau) as an alternative of the default readthedocs theme. 

- Repo https://bitbucket.org/ecollins/cloud_sptheme
- Docs: http://pythonhosted.org/cloud_sptheme/

**Comment by SylvainCorlay** [comment]
👍 on using the default theme. We could contribute improvements if we find issues, but I don't think that anyone is putting more cycles than them into this.

**Comment by willingc** [comment]
OK then default it is. Bonus points for making the default RTD more beautiful. Thanks!

@gnestor Do you want to work on a more visually appealing front end theme using RTD as the base with the intention of moving it over to jupyter/jupyter as well? 

cc @Carreau @michaelpacer @jdfreder

**Comment by gnestor** [comment]
@willingc Definitely!

**Comment by Carreau** [comment]
+1 on improving the readthedocs theme, it will improve all project that uses rtd.

The couldSphinx looks great as well, the scrollspy is nice.

**Comment by willingc** [comment]
Also a heads up for the front end folks. Sphinx 1.5alpha is dropping support for old browsers, improving LaTeX support, and moving JQuery from 1.11.0 to 3.1.0. Sphinx changelog: https://github.com/sphinx-doc/sphinx/blob/1.5a1/CHANGES
