### ISSUE TITLE
Hands off approach to styling

### ISSUE THREAD

**Issue by gnestor** [ipython/ipywidgets#812]
ipywidgets only provides an API for adding/removing CSS classes and the Style API. The Style API provides the ability to set layout CSS traits in a mutable fashion. All other styling APIs are deprecated.

**Comment by gnestor** [comment]
@SylvainCorlay Has this already been implemented?

**Comment by SylvainCorlay** [comment]
Nope, not yet. We are probably going to enable something similar to the `layout` class.
