### ISSUE TITLE
Order of functions called in WidgetModel

### ISSUE THREAD

**Issue by ssunkara1** [ipython/ipywidgets#829]
Hey all,

This is more of a question than an issue. So. in `WidgetModel` previously, the function `constructor` is called before the function `set`. This is probably what I would have expected.

But in the current master, the function `initialize`, which looks like a replacement for the `constructor`, is called after the function `set`. I wouldn't have expected that. 

I wanted to find out if this change is intentional and if yes, any reason why this was changed?

Thanks.

Version details:
By previously, I meant `ipywidgets` 5.2.2. And now, I am running off `master`.

**Comment by ssunkara1** [comment]
There seems to be a difference between the `constructor` and `initialize`. 

https://github.com/jashkenas/backbone/issues/720

But I guess we want to use `constructor` instead of `initialize`?

**Comment by ssunkara1** [comment]
@jasongrout

**Comment by gnestor** [comment]
@jasongrout It looks like you switched from `constructor` to `initialize` in https://github.com/ipython/ipywidgets/commit/386bcd61f65ba8c80309aaa4080748ae1a6c9088. @ssunkara1 Can you elaborate about your use case (e.g. what you would like to do before initializing the model)?

**Comment by jasongrout** [comment]
Yes, it was intentional. See https://github.com/ipython/ipywidgets/issues/677#issuecomment-253834228 for more details.

**Comment by jasongrout** [comment]
(Happy to discuss further if needed. @ssunkara1 and I discussed this in-person as well.)
