### ISSUE TITLE
Displays widgets out of order

### ISSUE THREAD

**Issue by gnestor** [ipython/ipywidgets#844]
The following code:

``` python
import ipywidgets
from ipywidgets import IntProgress
from IPython.display import display
from time import sleep
p = IntProgress(min=0, max=100, description="First bar is deleted")
p2 = IntProgress(min=0, max=100, description="Second bar always stays")
display(p)
display(p2)
p.bar_style = 'info'
for i in range(100):
    p.value = p.value + 1
    p2.value = p2.value + 1
    sleep(0.01)
```

consistently outputs:

![image](https://cloud.githubusercontent.com/assets/512354/19580609/3faac860-96dc-11e6-8b9c-684f910569a8.png)

The "First bar is deleted" widget should be first and the "Second bar always stays" should be second, but it's reversed.

**Comment by jasongrout** [comment]
I tried this at least 20 times in the classic notebook with a few changes on b74662ffdad876dc2790ae159022059791f55d79, and things worked fine every time:
<img width="696" alt="screen shot 2016-10-21 at 4 23 20 pm" src="https://cloud.githubusercontent.com/assets/192614/19610512/d5adcd0c-97aa-11e6-8974-1fa40178a331.png">

**Comment by gnestor** [comment]
So weird, I'm getting out of order every time. I suppose that it's even stranger that it's not reversed order but first is displayed last:

![image](https://cloud.githubusercontent.com/assets/512354/19614357/580f3f76-97a9-11e6-9419-d33b701b07fc.png)

I tried clearing outputs and manually clearing the `outputs` and `widgets.state` in the notebook but no luck. I'm running notebook and ipywidgets on master.

Any ideas?

**Comment by jasongrout** [comment]
I'm running notebook 4.2.3 - perhaps it's that? I can check on Monday.

**Comment by gnestor** [comment]
I tested again after pulling the ipython/master and the results are mixed now:

![screenshot](http://g.recordit.co/VMifNujFP9.gif)

**Comment by jasongrout** [comment]
@gnestor - we can try taking a look at this tomorrow together.

**Comment by jasongrout** [comment]
@gnestor - we didn't end up looking at this. Is it still an issue? If it is, let's set up a time we can debug it together, since I'm not reproducing it.

**Comment by SylvainCorlay** [comment]
We have the same issue with widget persistence. We only know in which output area a top-level widget is. If the order is not predictable.

**Comment by gnestor** [comment]
@jasongrout I'm still encountering this in the notebook at master. Lab is working as expected. Regarding widget persistence, see https://github.com/ipython/ipywidgets/issues/624#issuecomment-256181338.

**Comment by jasongrout** [comment]
I didn't see it because I was on notebook 4.2.3. Bisecting shows this commit is the problem: 4df331476123aa874a1d321ad945804b6df17e8c

**Comment by jasongrout** [comment]
Indeed, commenting out those lines in master makes the problem go away.

**Comment by gnestor** [comment]
@jasongrout Good find! How strange, though. Do you understand how providing the Promise polyfill via webpack caused an issue with the ordering of widgets vs. providing via bower?

**Comment by jasongrout** [comment]
The Promise polyfill by webpack, to my understanding, was done wrong (it wasn't actually providing a Promise object). I'm very surprised that webpack plugin didn't break everything completely. My guess is that there is some subtle race condition in acting on the messages from the kernel, but I didn't investigate that far.

**Comment by jasongrout** [comment]
Though looking at the es6-promise code, it looks like it should work these days. Now I'm a bit more puzzled - I may dig deeper after all.
