### ISSUE TITLE
Add jupyterlab_widgets to dev_install.sh

### ISSUE THREAD

**Issue by gnestor** [ipython/ipywidgets#854]
Should `dev_install.sh` be updated to include the following commands for installing jupyterlab_widgets?

```
npm run clean
npm install
npm run update
npm run build
pip install -e .
jupyter labextension install --py --symlink $nbExtFlags widgetsnbextension
jupyter labextension enable --py $nbExtFlags widgetsnbextension
```

I suppose that `jupyter labextension` depends on jupyterlab being installed...

**Comment by minrk** [comment]
Probably makes sense. You could check for its presence and run if it's available.
