### ISSUE TITLE
Can widget.Play() animate a plot?

### ISSUE THREAD

**Issue by Yafei777** [ipython/ipywidgets#871]
Is there any possibility to animate a matplotlib plot using the Play widget?

I can only find the example in which a Slider and a Play were linked. But how can I link a plot?

What I want to do is just plot a scatter that the number of points increase when I hit the 'start' button on the Play widget.

Thanks for any possible solution.

**Comment by dmadeka** [comment]
Hello, I'm not sure about matplotlib. But it's very easy using bqplot, the Wealth of Nations example does exactly this actually.

----- Original Message -----
From: 李 亚飞 <reply@reply.github.com>
To: ipywidgets@noreply.github.com
At: 02-Nov-2016 22:08:47


Is there any possibility to animate a matplotlib plot using the Play widget? 
I can only find the example in which a Slider and a Play were linked. But how can I link a plot? 
What I want to do is just plot a scatter that the number of points increase when I hit the 'start' button on the Play widget. 
Thanks for any possible solution.

**Comment by SylvainCorlay** [comment]
[won](https://github.com/bloomberg/bqplot/raw/master/bqplot-screencast.gif)

**Comment by jasongrout** [comment]
Link to Wealth of Nations example: https://github.com/bloomberg/bqplot/blob/master/examples/Applications/Wealth%20of%20Nations.ipynb

Also CC @tcaswell about the matplotlib-specific part of this.

(Closing as answered, but please reopen if you'd like to continue the discussion or have further questions)

**Comment by deeptavker** [comment]
I'm trying to use bqplot for animating a plot but I need multiple scatters on the same figure with different ColorAxis for each on the right-hand side of the figure lined one after the other, not overlapping. The probem is : offset, label_color, etc. are not working for ColorAxis. 

Even if setting the offset is possible, can we have multiple ColorAxis in such fashion? 

Thanks

**Comment by jasongrout** [comment]
@deeptavker - it sounds like you should be asking this in a bqplot issue. Could you repost your question there? https://github.com/bloomberg/bqplot/issues

**Comment by rheiland** [comment]
I've posted a similar question (and example) on the google group, but thought I'd ask here also. I'd really like to do this with mpl as I've got a lot invested in it. Any new ideas for "Play" functionality of a Jupyter interactive widget (with mpl plots)?
