### ISSUE TITLE
Question - Can i use ipywidgets without a notebook

### ISSUE THREAD

**Issue by DonJayamanne** [ipython/ipywidgets#877]
Can I use the [Jupyter_client](https://jupyter-client.readthedocs.io/en/latest/messaging.html#python-api) api to execute code against a kernel and still use ipywidgets?

Currently when I do this, I get the following response from the Kernel:
```
Widget Javascript not detected. It may not be installed properly. Did you enable the widgetsnbextension? If not, then run "jupyter nbextension enable --py --sys-prefix widgetsnbextension"
```

Note: The  widgetsnbextension is already enabled.
```
jupyter nbextension enable --py --sys-prefix widgetsnbextension
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
```

**Comment by SylvainCorlay** [comment]
It is possible to embed widgets in a webpage, just like what you can see here:

jupyter.org/widgets

The equivalent with a connected back end is not supported yet.

**Comment by DonJayamanne** [comment]
@SylvainCorlay 
When you say "It is possible to embed widgets in a **webpage**" just like what you can see here:" 
Don't you mean **notebook** instead of **webpage**

**Comment by SylvainCorlay** [comment]
No I mean that you can embed widgets in your blog or personal website.

**Comment by DonJayamanne** [comment]
@SylvainCorlay 
How's that done? Is that just some hardcoded JavaScript (markup in the webpage) or is the following Python code (executed on the server) to generate the javascript?     
```python
from ipyleaflet import Map
Map(center=[34.6252978589571, -77.34580993652344], zoom=10)
```

Looking at the examples, they are executed in notebooks (which in turn generate javascript rendered on the webpage).  

The widgets to my knowledge is basically a bunch of javascript code + data generated by the Python code executed. So, where is this python code being executed?

**Comment by SylvainCorlay** [comment]
You author your widgets / visualization from the notebook. Then in the menu `Widgets -> Embed Widgets` will give you a copy-pastable snippet of HTML code.

**Comment by jasongrout** [comment]
> Looking at the examples, they are executed in notebooks (which in turn generate javascript rendered on the webpage).

The javascript is loaded independently, it's not generated by the python. The *state* of the widgets is communicated back and forth with python. You can embed the javascript + initial state (which provides some interaction that is entirely in javascript). Check out the [examples](https://github.com/ipython/ipywidgets/tree/master/jupyter-js-widgets) in the jupyter-js-widgets repo, or use the 'Embed Widgets' feature Sylvain mentioned above.

You can also have javascript that starts up a kernel on a python server somewhere and communicates with it, embedding the widgets from that. See the [web3](https://github.com/ipython/ipywidgets/tree/master/jupyter-js-widgets/examples/web3) example for this.

**Comment by jasongrout** [comment]
Closing as answered - please reopen if you have more questions or want to continue the discussion.
