### ISSUE TITLE
Towards a 6.0 Release

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#887]
This is a meta issue for the 6.0 release

1. (DONE) remove widgets snapshot features This will require using live widget embedding in the documentation

2. busy icon for saving embeddable widgets

3. (DONE) Complete css refactoring

     - horizontal space
     - baseline alignment
     - controller widget css
     - UX of checkbox: click on text...

4. (DONE) semver requirement for models

5. (DONE) resize event (PR)

6. Cookiecutte:  jupyterlab_widgets? use new `default` syntax.

8. (DONE) does the output widget work in the legacy notebook? (And does @interact?)

**Comment by SylvainCorlay** [comment]
Closing since we have proper milestones now.

**Comment by blink1073** [comment]
TODO: learn project management.  😜
