### ISSUE TITLE
widgets not displayed in documentation

### ISSUE THREAD

**Issue by denfromufa** [ipython/ipywidgets#892]
https://github.com/ipython/ipywidgets/blob/master/docs/source/examples/Widget%20List.ipynb

**Comment by denfromufa** [comment]
also here:

*Data type cannot be displayed: application/vnd.jupyter.widget*

https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#SelectMultiple

**Comment by colin-svds** [comment]
Still a problem. What's the solution here? Roll it back?

**Comment by jasongrout** [comment]
Wow. The classic notebook ignores data types it can't display. It seems like we should:

(a) make the documentation generator understand the widget mimetype and know how to display it
(b) make whatever is generating the docs ignore the widget mimetype,
(c) or complete the process of moving the classic notebook over to using the widget output type so we can put a text/plain mimetype in that message too.

I think (a) is the best thing moving forward, if possible. @SylvainCorlay, what do you think?

**Comment by jasongrout** [comment]
Or perhaps we should just clear the outputs in the notebook, which should clear out those outputs?

**Comment by SylvainCorlay** [comment]
@jasongrout I am out until the end of the week but the sphinx extension will understand a widgets mimetype. However, as per the [written proposal](https://github.com/ipython/ipywidgets/issues/907), it will not exactly be the same thing as in widgets 5.

**Comment by SylvainCorlay** [comment]
Some progress on the sphinx extension:

![sphinx](https://cloud.githubusercontent.com/assets/2397974/20863758/1ed64e4e-b9d6-11e6-8326-9204b37710ac.gif)

**Comment by SylvainCorlay** [comment]
Now fixed in master:

http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html
