### ISSUE TITLE
Fix alignment of text in widgets

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipywidgets#904]
Some of the widgets have slightly vertically offset text. I checked this using:

```python
from ipywidgets import *

d = 'description: '
v = 'value'
o = [v, 'value2']
VBox([
HBox([
  BoundedFloatText(description='BoundedFloatText: '),
  BoundedIntText(description='BoundedIntText: '),
  Button(description='Button'),
  Checkbox(description='Checkbox: '),
  ColorPicker(description='ColorPicker: '),
]), HBox([
  Dropdown(options=o, description='Dropdown: '),
  FloatProgress(description='FloatProgress: '),
  FloatRangeSlider(description='FloatRangeSlider: '),
  FloatSlider(description='FloatSlider: '),
]), HBox([
  FloatText(description='FloatText: '),
  HTML(value='HTML'),
  IntProgress(description='IntProgress: '),
  IntRangeSlider(description='IntRangeSlider: '),
  IntSlider(description='IntSlider: '),
]), HBox([
  IntText(description='IntText'),
  Label(value='Label'),
  RadioButtons(description='RadioButtons: ', options=o),
  Select(description='Select: ', options=o),
  SelectMultiple(description='SelectMultiple: ', options=o),
]), HBox([
  SelectionSlider(description='SelectionSlider: ', options=o),
  Text(description='Text: ', value=v),
  Textarea(description='Textarea: ', value='\n'.join(o)),
  ToggleButton(description='ToggleButton'),
]), HBox([
  ToggleButtons(description='TogButtons: ', options=o),
  Valid(description='Vaild: '),
])])
```
and then using a horizontal guideline to check vertical alignment of text across all of the widgets.

Here it is on master with Jupyter notebook:

<img width="1409" alt="screen shot 2016-11-16 at 11 36 31 am" src="https://cloud.githubusercontent.com/assets/192614/20356262/ffc3cf1e-abf1-11e6-9124-74a1f1ac9712.png">

and on JupyterLab:

<img width="1423" alt="screen shot 2016-11-16 at 11 47 31 am" src="https://cloud.githubusercontent.com/assets/192614/20356453/8a735f80-abf2-11e6-8d05-9761c61d9a51.png">

**Comment by jasongrout** [comment]
Here is what it looks like after a few tweaks in JLab. I added a horizontal guide one pixel below the baseline for the label.

<img width="1424" alt="screen shot 2016-11-16 at 11 11 35 am" src="https://cloud.githubusercontent.com/assets/192614/20354928/a4e710a0-abed-11e6-86b4-8c055d55016b.png">

**Comment by jasongrout** [comment]
Here's what it looks like in the Jupyter notebook:

<img width="1405" alt="screen shot 2016-11-16 at 11 16 24 am" src="https://cloud.githubusercontent.com/assets/192614/20355098/2edf7126-abee-11e6-8524-1116c71a8b19.png">

**Comment by jasongrout** [comment]
Here's what it looks like in the Jupyter notebook:

<img width="1405" alt="screen shot 2016-11-16 at 11 16 24 am" src="https://cloud.githubusercontent.com/assets/192614/20355098/2edf7126-abee-11e6-8524-1116c71a8b19.png">

**Comment by SylvainCorlay** [comment]
- The selectMultiple is the worst. 
- I guess we should not try to do anything about the HTML widget which is intentionally bare.

**Comment by jasongrout** [comment]
The selectMultiple is also one of the hardest to style.

Point taken about the HTML widget, though it would be nice if by default it at least had the same baseline and/or lineheight.

**Comment by jasongrout** [comment]
Note also that the widths of the controls don't line up very well.

**Comment by jasongrout** [comment]
CC @cameronoelsen

**Comment by jasongrout** [comment]
CC @ellisonbg

**Comment by jasongrout** [comment]
Here's another snippet of code for alignment:

```
from ipywidgets import *

d = 'description: '
v = 'value'
o = [v, 'value2', 'value3', 'value4']
VBox([
HBox([
  BoundedFloatText(description='BoundedFloatText: '),
]), HBox([
  BoundedIntText(description='BoundedIntText: '),
]), HBox([
  Button(description='Button'),
]), HBox([
  Checkbox(description='Checkbox: '),
]), HBox([
  ColorPicker(description='ColorPicker: '),
]), HBox([
  Dropdown(options=o, description='Dropdown: '),
]), HBox([
  FloatProgress(description='FloatProgress: '),
]), HBox([
  FloatRangeSlider(description='FloatRangeSlider: '),
]), HBox([
  FloatSlider(description='FloatSlider: '),
]), HBox([
  FloatText(description='FloatText: '),
]), HBox([
  HTML(value='HTML'),
]), HBox([
  IntProgress(description='IntProgress: '),
]), HBox([
  IntRangeSlider(description='IntRangeSlider: '),
]), HBox([
  IntSlider(description='IntSlider: '),
]), HBox([
  IntText(description='IntText: '),
]), HBox([
  Label(value='Label'),
]), HBox([
  RadioButtons(description='RadioButtons: ', options=o),
]), HBox([
  Select(description='Select: ', options=o),
]), HBox([
  SelectMultiple(description='SelectMultiple: ', options=o),
]), HBox([
  SelectionSlider(description='SelectionSlider: ', options=o),
]), HBox([
  Text(description='Text: ', value=v),
]), HBox([
  Textarea(description='Textarea: ', value='\n'.join(o)),
]), HBox([
  ToggleButton(description='ToggleButton'),
]), HBox([
  ToggleButtons(description='ToggleButtons: ', options=o),
]), HBox([
  Valid(description='Valid: '),
])])
```
