### ISSUE TITLE
Embedding mechanism

### ISSUE THREAD

**Issue by SylvainCorlay** [ipython/ipywidgets#907]
**Current Mechanism used on http://jupyter.org/widgets**

1. Embed manager script tag from cdn
2. Script tag with `type=application/vnd.jupyter-embedded-widgets` containing the widget manager state.

    The format for this state is the one described here:

    https://github.com/ipython/ipywidgets/blob/master/ipywidgets/state.schema.json

    before we wrote the spec, so without the version information.

    Besides, each widget has a `views` attribute of type array. If it is not empty, the widget is a *top-level*  widget.

    This script tag is picked up by the embed manager and replaced by a rendered version of all the top-level widgets in a row.

**Proposed mechanism for web pages**

1. Embed manager script tag from cdn
2. Script tag with `type=application/vnd.jupyter.widget-state+json` containing the widget manager state, following precisely the schema for the manager state

    https://github.com/ipython/ipywidgets/blob/master/ipywidgets/state.schema.json

3. Script tags with `type=application/vnd.jupyter.widget-view+json` containing

    ```json
    {
        "model_id": {
            "type": "string",
            "description": "Model id to be displayed inplace"
        }
    }
    ```

**Proposed mechanism for nbviewer**

1. nbviewer loads the embed manager JavaScript, either from cdn or bundles is

2. Each output area containing widgets gets its `type=application/vnd.jupyter.widget-view+json` tag in the html mime bundle.

3. Global widget state following the state schema is saved in the notebook metadata.

    The html nbconversion picks up that metadata and incorporates a `type=application/vnd.jupyter.widget-state+json`.

**Comment by SylvainCorlay** [comment]
Ping @michaelpacer @minrk @jasongrout

**Comment by jasongrout** [comment]
> type=application/vnd.jupyter-embedded-widgets

We've been using `application/vnd.jupyter.<something>` for mime types, in accordance with https://tools.ietf.org/html/rfc6838#section-3.2. (We should register the `jupyter` name for this to be really official, though...)

**Comment by SylvainCorlay** [comment]
>> type=application/vnd.jupyter-embedded-widgets

> We've been using application/vnd.jupyter.<something> for mime types, in accordance with https://tools.ietf.org/html/rfc6838#section-3.2. (We should register the jupyter name for this to be really official, though...)

OK edited the description.

**Comment by SylvainCorlay** [comment]
@michaelpacer this is orthogonal to the current png repr in the mime bundle that is used to achieve 

this: https://github.com/ipython/ipywidgets/blob/master/docs/source/examples/Factoring.ipynb

**Comment by jasongrout** [comment]
> OK edited the description.

Thanks. The example I quoted still should be changed :).

**Comment by SylvainCorlay** [comment]
>> OK edited the description.

> Thanks. The example I quoted still should be changed :).

...

**Comment by SylvainCorlay** [comment]
^ @jasongrout

**Comment by jasongrout** [comment]
Doh!

**Comment by michaelpacer** [comment]
Ok, thanks for the heads up. 

I'm still not sure what the best way to deal with widgets in static documents is.

I have some thoughts but I'm guessing that looking at the actual code will help to refine those thoughts. Could someone point me to the widget drawing code (for live drawing on display) and the current mechanism for generating the png representations?
