### ISSUE TITLE
Instantiate a widget from javascript

### ISSUE THREAD

**Issue by martinRenou** [ipython/ipywidgets#911]
Hi,

I'm currently developing an nbextension for Jupyter Notebook, and I would like to know if it's possible and what is the proper way to instantiate a widget from javascript. Meaning directly in the render function of my widget, in order to have a complete GUI with some widgets in this widget.

You'll maybe ask me "Why would you want to do that ? Instantiate it on server side !". In fact my GUI will depend on a javascript module that contains all the data, and I want to stay on client side with jslinks between sub widgets.

I hope that it's possible, 
Martin

**Comment by jasongrout** [comment]
Are you wanting to have any communication with objects in the kernel?

**Comment by martinRenou** [comment]
Well, it's not really necessary. In fact, I thought about it and if I just instantiate DOM Elements (the views) of ipywidgets and use my own events on them it would be ok. If data stay on front end (at least for those sub widgets) it's ok for me.

**Comment by martinRenou** [comment]
I decided to create my own DOM elements with JQueryUI, like it's done in ipywidgets, and respecting CSS. So sad that we can't use some widgets without sync with the kernel...
Thanks anyway,
I close it

**Comment by jasongrout** [comment]
I think if I were you, I'd just use the UI elements directly (e.g., directly instantiate a slider where you need it, etc.). I probably wouldn't use widgets at all.

**Comment by martinRenou** [comment]
That's what I did, thanks for your answer
