### ISSUE TITLE
"Using Interact.ipynb" in the docs is not valid JSON and can't be opened

### ISSUE THREAD

**Issue by fkjogu** [ipython/ipywidgets#913]
The file [docs/source/examples/Using Interact.ipynb](https://github.com/ipython/ipywidgets/blob/master/docs/source/examples/Using%20Interact.ipynb) in the docs is not valid JSON and can't be opened. Maybe something went wrong, when exporting it?

**Comment by jasongrout** [comment]
Thanks. That was my fault.
