### ISSUE TITLE
Use python 3's `inspect.signature` method for interacts

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipywidgets#917]
It's smarter about wrapped functions, for example. We might need to use a backport like https://github.com/aliles/funcsigs if we need to support python 2 by the time we implement this.

**Comment by minrk** [comment]
IPython already ships a backport of signatures in `IPython.utils.signatures`, so you could rely on that for Python 2.

**Comment by jasongrout** [comment]
Oh nice, thanks!

**Comment by jdemeyer** [comment]
This was fixed almost 3 years ago: https://github.com/ipython/ipywidgets/commit/61757e3c70ceb9c00355b0bda063a7b50f7b1a3f

So I don't get what this issue is about...

**Comment by jasongrout** [comment]
Weird, I'm not sure why I didn't see that. I agree this is invalid.
