### ISSUE TITLE
Live widgets in documentation seems not to work

### ISSUE THREAD

**Issue by infinity0** [ipython/ipywidgets#923]
Hi, we're trying to package this for Debian. (Doing version 5.2.2 at the moment.) We've managed to get this working in Jupyter Notebook, but the documentation seems to not work. It looks like this is an issue on your end, rather than ours - I'm just asking to confirm this?

I am guessing the images are supposed to be made "live" via this sort of markup:

~~~~
<script type="application/vnd.jupyter-embedded-widgets">[{},{"layout":"IPY_MODEL_d0f3efb99b9c4630930ba1e58d0e265f","min":-10,"description":"x","max":30,"value":10},{},{"children":["IPY_MODEL_cdebfde35e9b446db86d29c692798662"],"layout":"IPY_MODEL_5fea5451413e4bce878c6295f3d22638","_dom_classes":["widget-interact"]}]</script></div>
~~~~

which we're generating correctly I think, based on the generated markup on [readthedocs](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Low%20Level.html).

However, even after applying #922, we're getting many JS errors in the browser like this:

~~~~
WrappedError {stack: "Error: Could not set widget manager state.↵    at …//localhost:8000/_static/built/index.js:33702:30)", message: "Could not set widget manager state.", error_stack: Array[3]}
  error_stack : Array[3]
    0 : Error: Class undefined not found in registry at http://localhost:8000/_static/built/index.js:33668:25 at Object.loadClass (http://localhost:8000/_static/built/index.js:33629:13) at ManagerBase.new_model (http://localhost:8000/_static/built/index.js:35566:32) at http://localhost:8000/_static/built/index.js:35711:30 at Function._.map._.collect (http://localhost:8000/_static/built/index.js:33928:25) at http://localhost:8000/_static/built/index.js:35686:31
    1 : Error: Couldn't create model at new Error (native) at Error.WrappedError (http://localhost:8000/_static/built/index.js:33595:22) at http://localhost:8000/_static/built/index.js:35582:34
    2 : Error: Could not set widget manager state. at new Error (native) at Error.WrappedError (http://localhost:8000/_static/built/index.js:33595:22) at promiseRejection (http://localhost:8000/_static/built/index.js:33702:30)
    length : 3
~~~~

After doing some debugging, I can see that `jupyter-js-widgets/src/embed-webpack.js:replaceTag` reads the contents of that `<script>` element and then passes it down through several function calls, including:

~~~~
    at ManagerBase.set_state (http://localhost:8000/_static/built/index.js:35683:15)
    at ManagerBase.EmbedManager.display_widget_state (http://localhost:8000/_static/built/index.js:39002:18)
    at replaceTag (http://localhost:8000/_static/built/index.js:124:14)
    at renderInlineWidgets (http://localhost:8000/_static/built/index.js:114:10)
    at http://localhost:8000/_static/built/index.js:102:14
    at callback (http://localhost:8000/_static/built/index.js:44006:18)
    at HTMLScriptElement.el.onload.el.onerror.el.(anonymous function) (http://localhost:8000/_static/built/index.js:44040:8)
~~~~

This eventually hits the `// dead comm` branch inside `jupyter-js-widgets/src/manager-base.js` whereby

~~~~
	                    model_name: state[model_id].model_name,
	                    model_module: state[model_id].model_module,
~~~~

are both undefined (since they are not defined in that JSON object on the doc page), which then causes the `WrappedError.error_stack[0]` "Class undefined not found in registry" error described above.

I am asking because we are bypassing webpack to generate `_static/built/index.js` via a different method (that is why all the line numbers above are slightly different from yours), so naturally the chances are that it is us that is Doing It Wrong. However most of the core functionality seems to work for me in my local Jupyter Notebook, including the examples from the documentation - plus my investigation above suggests that the problem here is actually on your end.

Please confirm, and also advise us on how we can do some further tests to check that our webpack-less build is working correctly. Thanks a lot in advance!

**Comment by SylvainCorlay** [comment]
The live documentation now fixed in master

http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html
