### ISSUE TITLE
Dropdown Widget cut off at the end of the notebook

### ISSUE THREAD

**Issue by aneeshvartakavi** [ipython/ipywidgets#94]
I'm facing an issue when the dropdown is cut off the end of the notebook (see attached screenshot). I've worked around this in the past by adding empty cells below this cell, but I currently have a list of 300 options and I'm trying to find a better fix. I'm running IPython Notebook 3.2.1.

![screen shot 2015-07-17 at 3 58 38 pm](https://cloud.githubusercontent.com/assets/4122476/8759523/7cc6cd04-2caa-11e5-8285-17496285f805.png)

**Comment by SylvainCorlay** [comment]
Should we close this?

**Comment by jdfreder** [comment]
No, this  part of the drop down  behavior was left out of #281
