### ISSUE TITLE
Progress bar style not updating if value starts at 0

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipywidgets#946]
With notebook ce575f7a5ab625ea044709659cf6aebe264098e0:

```python
from ipywidgets import IntProgress
from IPython.display import display
p = IntProgress(min=0, max=100, value=0)
p.bar_style = 'info'
p.value = 50
display(p)
```
doesn't display the right color in the progress bar, but this does:
```python
from ipywidgets import IntProgress
from IPython.display import display
p = IntProgress(min=0, max=100, value=50)
p.bar_style = 'info'
display(p)
```
<img width="492" alt="screen shot 2016-12-06 at 1 29 56 pm" src="https://cloud.githubusercontent.com/assets/192614/20944431/48f690c4-bbb8-11e6-9503-353a5283dddd.png">

**Comment by SylvainCorlay** [comment]
Fixed in #1017
