### ISSUE TITLE
Cannot change Tab if embedded in Accordion

### ISSUE THREAD

**Issue by rmenegaux** [ipython/ipywidgets#955]
On ipywidgets master:
If a `Tab` widget is a child of an `Accordion` widget, switching between tabs by clicking does not work:
```python
from ipywidgets import Accordion, Box, Tab
t = Tab([Box(), Box()])
Accordion([t])
```
Changing tabs programmatically (`t.selected_index = 1`) still works as expected.

**Comment by jasongrout** [comment]
The problem is that we are not using phosphor to attach accordion children: https://github.com/ipython/ipywidgets/blob/master/jupyter-js-widgets/src/widget_selectioncontainer.ts#L152.

Working on it...

**Comment by jasongrout** [comment]
This is the subject of #983.

**Comment by jasongrout** [comment]
This now works in master.
