### ISSUE TITLE
Width not working (5.2.2, at least for Button)

### ISSUE THREAD

**Issue by metaperture** [ipython/ipywidgets#962]
Hey, I couldn't find a bug report on this, but in the following code, the width keyword does nothing (even though current docs seem to indicate that it should):

    import ipywidgets as ipw
    print(ipw.__version__) # 5.2.2
    ipw.Button(width=20)

Not sure if this is a known bug?

**Comment by SylvainCorlay** [comment]
So the way to do this is

```python
import ipywidgets as ipw
b = ipw.Button()
b.layout.width = '20px'
```

all the top-level layout attributes are regrouped into the `layout` attribute, which can be assigned globally too

```python
l = Layout(min_width='40px', max_width='160px')
b = Button(layout=l)
s = Slider=(layout=l)
```
