### ISSUE TITLE
Update proxy widget to use Phosphor to attach children widgets

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipywidgets#978]
The proxy widget currently doesn't use the phosphor mechanism, so phosphor messages stop at the proxy widget boundary.

**Comment by SylvainCorlay** [comment]
I think that the widget proxy remains a ad-hoc thing rarely used... moving to 6.1.

**Comment by jasongrout** [comment]
We should fix or deprecate this, then, for 6.0.  In talking with @SylvainCorlay, we decided we could remove the PlaceProxy widget (likely rarely used), and fix the proxy widget that serves as a base class for other widgets.
