### ISSUE TITLE
Tab _titles dictionary keys change from int to string when widget is displayed

### ISSUE THREAD

**Issue by rmenegaux** [ipython/ipywidgets#981]
The following code:

```python
from ipywidgets import Tab, Box
t = Tab([Box()])
t.set_title(0, 'Title 0')
print(t._titles)
```
outputs `{0: 'Title 0'}` as expected.

However if I display `t`, then `t._titles` becomes `{'0': 'Title 0'}`.

This is a problem because `t.set_title(0, 'New Title')` fails with a
```python
ValueError: dict cannot be safely converted to JSON: key collision would lead to dropped values
```

**Comment by jasongrout** [comment]
Thanks - we fixed this in #1066. #1065 is a duplicate report as well.
