### ISSUE TITLE
Readme still mentions gulp... what are the real steps to install on top of jupyter?

### ISSUE THREAD

**Issue by lbustelo** [ipython/ipywidgets#99]
I saw some work went in to remove gulp requirement to intall, but the instructions still mentions it. I tried to just do `pip install -e .` but still not able to run ipywidgets on my install of jupyter.

**Comment by lbustelo** [comment]
Let me expand on what I mean "still not able to run"... After runing `pip install -e .` on ipywidgets, I'm able to go to a notebook using https://github.com/ipython/ipywidgets/blob/master/examples/Using%20Interact.ipynb and run the first cell of imports. I can verify that the functions are getting imported. But, when I get to the cell that has the `interact()` it does nothing. I never get a widget back, and my cell remains in busy state (`In [*]:`)

**Comment by jdfreder** [comment]
Sorry, there was a pull request open just sitting idle that fixed the readme, see https://github.com/ipython/ipywidgets/pull/97 .  I didn't get merged because of a test failure elsewhere.  It's merged now :)

**Comment by jdfreder** [comment]
Fixed by #97 .
