### ISSUE TITLE
Add a .style attribute for control-specific styles

### ISSUE THREAD

**Issue by jasongrout** [ipython/ipywidgets#992]
We don't have a way of changing the button color anymore, for example, and various other attributes of a control. This is frustrating some people trying to move to current master.

@SylvainCorlay and I suggest exploring having a `.style` attribute that contains control-specific style information. For example, a Button's style attribute would be a `ButtonStyle` traitlet that had things like color, font color, font weight, etc. We'll have to pick the attributes carefully, and we don't want to expose the DOM structure.

CC @ssunkara1, @dmadeka, @ccherukuri, @ChakriCherukuri, @rmenegaux

**Comment by jasongrout** [comment]
Everyone, please post comments here with the style attributes we should consider. I think we want to scope these to what we really use.

**Comment by SylvainCorlay** [comment]
I would start with a `Button.style` since it is the simplest. 

 `button_color`
 `text_color`
 `font_weight`

Ruling out font size would simplify things.

**Comment by dmadeka** [comment]
@jasongrout Is this meant as a design for all widget styling or just Buttons?

**Comment by jasongrout** [comment]
I think we imagine different style attributes for different widgets, though some may be shared.
